/*
 * Copyright (c) 2021-2025 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Net.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

using Org.BouncyCastle.Pkcs;
using Org.BouncyCastle.Security;

using cloud.charging.open.protocols.ISO15118.PKI;

using BcCert = Org.BouncyCastle.X509.X509Certificate;

namespace Vanaheimr.V2G.Simulation.Tests.TestData
{
    /// <summary>
    /// A throwaway, test-time V2G certificate hierarchy for the ISO 15118-20 <b>mutual-TLS</b> E2E tests,
    /// generated by the WWCP <c>WWCP_ISO15118_PKI</c> builder (strict-20 profile: ECDSA P-521, secp521r1).
    /// Nothing is checked into git. The SECC presents its <b>SECC</b> leaf (TLS server) and the EVCC its
    /// <b>Vehicle</b> leaf (TLS client); both chains anchor to the same V2G Root, which is how the mutual
    /// handshake validates. See <c>docs/pki-model.md</c>.
    /// </summary>
    public sealed class V2GTestPki : IDisposable
    {
        /// <summary>SECC TLS server certificate (leaf + private key).</summary>
        public X509Certificate2 SeccServerCert { get; }

        /// <summary>EVCC TLS client certificate — the Vehicle cert (leaf + private key).</summary>
        public X509Certificate2 VehicleClientCert { get; }

        /// <summary>Shared V2G Root CA (public cert only), the trust anchor for both sides.</summary>
        public X509Certificate2 Root { get; }

        private readonly X509Certificate2[] _seccIntermediates;
        private readonly X509Certificate2[] _vehicleIntermediates;

        /// <summary>The Vehicle branch intermediate CAs (Sub-CA 2 then Sub-CA 1) — the chain a client must
        /// <b>send over the wire</b> for a root-only SECC (e.g. Josev, which loads just the OEM root) to verify it.</summary>
        public X509Certificate2Collection VehicleIntermediates => new(_vehicleIntermediates);

        /// <summary>SECC-side callback that trusts <b>only</b> the V2G Root and builds the chain purely from the
        /// certificates the peer sent over the wire (no out-of-band intermediates) — so it succeeds only if the
        /// client actually transmitted its intermediate chain. Mirrors Josev's root-only client validation.</summary>
        public RemoteCertificateValidationCallback ValidateVehicleClientWireChainOnly => (_, presented, wireChain, _) =>
        {
            if (presented is not X509Certificate2 leaf || wireChain is null)
                return false;

            using var chain = new X509Chain();
            chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
            chain.ChainPolicy.TrustMode      = X509ChainTrustMode.CustomRootTrust;
            chain.ChainPolicy.CustomTrustStore.Add(Root);
            // Only the intermediates the peer transmitted (present in the SslStream-built chain) — nothing local.
            foreach (var element in wireChain.ChainElements)
                if (!element.Certificate.Equals(leaf))
                    chain.ChainPolicy.ExtraStore.Add(element.Certificate);

            return chain.Build(leaf);
        };

        /// <summary>SECC-side callback: validate the presented Vehicle client cert against the shared V2G Root.</summary>
        public RemoteCertificateValidationCallback ValidateVehicleClient => Make(Root, _vehicleIntermediates);

        /// <summary>EVCC-side callback: validate the presented SECC server cert against the shared V2G Root.</summary>
        public RemoteCertificateValidationCallback ValidateSeccServer => Make(Root, _seccIntermediates);

        private V2GTestPki(V2GHierarchy h)
        {
            SeccServerCert        = WithKey(h.SeccLeaf);
            VehicleClientCert     = WithKey(h.VehicleLeaf);
            Root                  = CertOnly(h.Root.Certificate);
            _seccIntermediates    = [CertOnly(h.CpoSubCa2.Certificate),     CertOnly(h.CpoSubCa1.Certificate)];
            _vehicleIntermediates = [CertOnly(h.VehicleSubCa2.Certificate), CertOnly(h.VehicleSubCa1.Certificate)];
        }

        /// <summary>Builds a fresh strict-20 (ECDSA P-521) hierarchy.</summary>
        public static V2GTestPki CreateStrict20()
            => Create(V2GAlgorithm.EcdsaP521, V2GProfileFlavor.Strict15118_20);

        /// <summary>Builds a hierarchy with the given algorithm/profile (used to probe Schannel curve support).</summary>
        /// <remarks>
        /// Every hierarchy gets a <b>unique CN suffix</b>. Without it each run minted a fresh root carrying
        /// the identical subject <c>CN=V2G Root CA, DC=Root, DC=V2G, O=V2G PKI, C=DE</c>, and Windows'
        /// certificate cache — which indexes by name — would hand a *previous* run's root to a *later*
        /// run's chain build. The keys don't match, so the build reported
        /// <c>NotSignatureValid</c> on the Sub-CA, and the mutual-TLS tests drifted from green to red as
        /// the cache filled up during a session. Distinct names make the runs independent.
        /// </remarks>
        public static V2GTestPki Create(V2GAlgorithm algorithm, V2GProfileFlavor flavor)
            => new(V2GHierarchy.Build(
                       algorithm,
                       new SecureRandom(),
                       CommonNameSuffix:   " " + Guid.NewGuid().ToString("N")[..12],
                       V2GProfileOptions:  new V2GProfileOptions(flavor, algorithm, V2GPolicySet.None)));

        // BouncyCastle leaf + private key → a .NET X509Certificate2 with an exportable private key,
        // via an in-memory PKCS#12 (algorithm-agnostic; works for ECDSA P-521).
        private static X509Certificate2 WithKey(V2GIssued issued)
        {
            var store = new Pkcs12StoreBuilder().Build();
            store.SetKeyEntry("leaf",
                              new AsymmetricKeyEntry(issued.KeyPair.Private),
                              [new X509CertificateEntry(issued.Certificate)]);

            using var ms = new MemoryStream();
            var pw = "pki".ToCharArray();
            store.Save(ms, pw, new SecureRandom());

            return X509CertificateLoader.LoadPkcs12(ms.ToArray(), new string(pw), X509KeyStorageFlags.Exportable);
        }

        private static X509Certificate2 CertOnly(BcCert bc)
            => X509CertificateLoader.LoadCertificate(bc.GetEncoded());

        // Validate a presented leaf against our own V2G Root as a custom trust anchor, supplying the
        // branch intermediates out of band (they need not be sent over the wire for a loopback test).
        //
        // This callback must be TOTAL: it returns a verdict for every input and never throws. A
        // RemoteCertificateValidationCallback that throws does not fail the handshake cleanly — the
        // exception propagates out of SslStream.AuthenticateAs*, so the caller sees a
        // CryptographicException instead of the AuthenticationException a rejected peer should produce.
        // That is what made Secc_RejectsClientWithoutCertificate flaky: under TLS 1.3 a client that
        // offers no certificate can still reach this callback with a non-null but degenerate
        // X509Certificate (empty/unparseable raw data), and building a chain over that throws
        // "An unknown chain building error occurred" instead of simply returning false.
        private static RemoteCertificateValidationCallback Make(X509Certificate2 root, X509Certificate2[] intermediates)
            => (_, presented, _, _) =>
            {
                if (presented is null)
                    return false;

                X509Certificate2 leaf;
                try
                {
                    // An empty certificate message can surface as a non-null certificate with no raw
                    // data; loading or chain-building that is an error, not a validation failure.
                    var raw = presented.GetRawCertData();
                    if (raw is null || raw.Length == 0)
                        return false;

                    leaf = presented as X509Certificate2 ?? X509CertificateLoader.LoadCertificate(raw);
                }
                catch (CryptographicException)
                {
                    return false;
                }

                try
                {
                    using var chain = new X509Chain();
                    chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
                    chain.ChainPolicy.TrustMode      = X509ChainTrustMode.CustomRootTrust;
                    // RevocationMode.NoCheck stops CRL/OCSP but NOT AIA fetching of missing issuers.
                    // Every issuer we need is supplied via ExtraStore, so forbid downloads outright and
                    // keep the check hermetic — no test should depend on network reachability.
                    chain.ChainPolicy.DisableCertificateDownloads = true;
                    chain.ChainPolicy.CustomTrustStore.Add(root);
                    foreach (var i in intermediates)
                        chain.ChainPolicy.ExtraStore.Add(i);

                    return chain.Build(leaf);
                }
                catch (CryptographicException)
                {
                    // A chain engine failure is not a valid chain.
                    return false;
                }
            };

        public void Dispose()
        {
            SeccServerCert.Dispose();
            VehicleClientCert.Dispose();
            Root.Dispose();
            foreach (var c in _seccIntermediates)    c.Dispose();
            foreach (var c in _vehicleIntermediates) c.Dispose();
        }
    }
}
