using System.Net.Security;
using System.Security.Cryptography.X509Certificates;

using Org.BouncyCastle.Pkcs;
using Org.BouncyCastle.Security;

using cloud.charging.open.protocols.ISO15118.PKI;

using BcCert = Org.BouncyCastle.X509.X509Certificate;

namespace Vanaheimr.V2G.Simulation.Tests.TestData
{
    /// <summary>
    /// A throwaway, test-time V2G certificate hierarchy for the ISO 15118-20 <b>mutual-TLS</b> E2E tests,
    /// generated by the WWCP <c>WWCP_ISO15118_PKI</c> builder (strict-20 profile: ECDSA P-521, secp521r1).
    /// Nothing is checked into git. The SECC presents its <b>SECC</b> leaf (TLS server) and the EVCC its
    /// <b>Vehicle</b> leaf (TLS client); both chains anchor to the same V2G Root, which is how the mutual
    /// handshake validates. See <c>docs/pki-model.md</c>.
    /// </summary>
    public sealed class V2GTestPki : IDisposable
    {
        /// <summary>SECC TLS server certificate (leaf + private key).</summary>
        public X509Certificate2 SeccServerCert { get; }

        /// <summary>EVCC TLS client certificate — the Vehicle cert (leaf + private key).</summary>
        public X509Certificate2 VehicleClientCert { get; }

        /// <summary>Shared V2G Root CA (public cert only), the trust anchor for both sides.</summary>
        public X509Certificate2 Root { get; }

        private readonly X509Certificate2[] _seccIntermediates;
        private readonly X509Certificate2[] _vehicleIntermediates;

        /// <summary>SECC-side callback: validate the presented Vehicle client cert against the shared V2G Root.</summary>
        public RemoteCertificateValidationCallback ValidateVehicleClient => Make(Root, _vehicleIntermediates);

        /// <summary>EVCC-side callback: validate the presented SECC server cert against the shared V2G Root.</summary>
        public RemoteCertificateValidationCallback ValidateSeccServer => Make(Root, _seccIntermediates);

        private V2GTestPki(V2GHierarchy h)
        {
            SeccServerCert        = WithKey(h.SeccLeaf);
            VehicleClientCert     = WithKey(h.VehicleLeaf);
            Root                  = CertOnly(h.Root.Certificate);
            _seccIntermediates    = [CertOnly(h.CpoSubCa2.Certificate),     CertOnly(h.CpoSubCa1.Certificate)];
            _vehicleIntermediates = [CertOnly(h.VehicleSubCa2.Certificate), CertOnly(h.VehicleSubCa1.Certificate)];
        }

        /// <summary>Builds a fresh strict-20 (ECDSA P-521) hierarchy.</summary>
        public static V2GTestPki CreateStrict20()
            => Create(V2GAlgorithm.EcdsaP521, V2GProfileFlavor.Strict15118_20);

        /// <summary>Builds a hierarchy with the given algorithm/profile (used to probe Schannel curve support).</summary>
        public static V2GTestPki Create(V2GAlgorithm algorithm, V2GProfileFlavor flavor)
            => new(V2GHierarchy.Build(
                       algorithm,
                       new SecureRandom(),
                       V2GProfileOptions: new V2GProfileOptions(flavor, algorithm, V2GPolicySet.None)));

        // BouncyCastle leaf + private key → a .NET X509Certificate2 with an exportable private key,
        // via an in-memory PKCS#12 (algorithm-agnostic; works for ECDSA P-521).
        private static X509Certificate2 WithKey(V2GIssued issued)
        {
            var store = new Pkcs12StoreBuilder().Build();
            store.SetKeyEntry("leaf",
                              new AsymmetricKeyEntry(issued.KeyPair.Private),
                              [new X509CertificateEntry(issued.Certificate)]);

            using var ms = new MemoryStream();
            var pw = "pki".ToCharArray();
            store.Save(ms, pw, new SecureRandom());

            return X509CertificateLoader.LoadPkcs12(ms.ToArray(), new string(pw), X509KeyStorageFlags.Exportable);
        }

        private static X509Certificate2 CertOnly(BcCert bc)
            => X509CertificateLoader.LoadCertificate(bc.GetEncoded());

        // Validate a presented leaf against our own V2G Root as a custom trust anchor, supplying the
        // branch intermediates out of band (they need not be sent over the wire for a loopback test).
        private static RemoteCertificateValidationCallback Make(X509Certificate2 root, X509Certificate2[] intermediates)
            => (_, presented, _, _) =>
            {
                if (presented is null)
                    return false;

                var leaf = presented as X509Certificate2
                           ?? X509CertificateLoader.LoadCertificate(presented.GetRawCertData());

                using var chain = new X509Chain();
                chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
                chain.ChainPolicy.TrustMode      = X509ChainTrustMode.CustomRootTrust;
                chain.ChainPolicy.CustomTrustStore.Add(root);
                foreach (var i in intermediates)
                    chain.ChainPolicy.ExtraStore.Add(i);

                return chain.Build(leaf);
            };

        public void Dispose()
        {
            SeccServerCert.Dispose();
            VehicleClientCert.Dispose();
            Root.Dispose();
            foreach (var c in _seccIntermediates)    c.Dispose();
            foreach (var c in _vehicleIntermediates) c.Dispose();
        }
    }
}
