using System.Text.Json;
using NUnit.Framework;
using Vanaheimr.V2G.Exi.Tests.Infrastructure;
using Vanaheimr.V2G.Iso15118_2.Generated;

namespace Vanaheimr.V2G.Exi.Tests
{
    /// <summary>
    /// Differential wire conformance for ISO 15118-2: the generated codec must produce exactly the
    /// bytes cbV2G produces for each target message (SessionSetupReq/Res, ServiceDiscoveryReq/Res).
    /// The reference hex is checked in (<c>Vectors/Iso15118_2.vectors.json</c>, emitted by
    /// <c>tools/cbv2g-ref/main_iso2.c</c>); the message for each vector name comes from
    /// <see cref="Iso15118_2Fixtures"/>.
    /// </summary>
    [TestFixture]
    public class Iso15118_2VectorTests
    {
        public sealed record Vec(string Name, string MessageType, string ExpectedHex);

        private static IEnumerable<TestCaseData> Vectors()
        {
            var path = Path.Combine(TestContext.CurrentContext.TestDirectory, "Vectors", "Iso15118_2.vectors.json");
            using var doc = JsonDocument.Parse(File.ReadAllText(path));
            foreach (var v in doc.RootElement.GetProperty("vectors").EnumerateArray())
            {
                var name = v.GetProperty("name").GetString()!;
                yield return new TestCaseData(new Vec(
                    name,
                    v.GetProperty("messageType").GetString()!,
                    v.GetProperty("expectedHex").GetString()!)).SetName(name);
            }
        }

        [TestCaseSource(nameof(Vectors))]
        public void GeneratedCodec_Matches_CbV2G(Vec vector)
        {
            Assert.That(Iso15118_2Fixtures.ByName.ContainsKey(vector.Name), Is.True,
                $"no fixture for vector '{vector.Name}'");

            var message = Iso15118_2Fixtures.ByName[vector.Name];
            var buf = new byte[512];
            Assert.That(message.TryEncode(buf, out int n), Is.True, "encode failed");

            var actual = buf.AsSpan(0, n).ToArray();
            var expected = ParseHex(vector.ExpectedHex);

            if (!actual.AsSpan().SequenceEqual(expected))
                Assert.Fail($"{vector.Name}: generated bytes diverge from cbV2G.\n" +
                            $"  expected ({expected.Length}): {ToHex(expected)}\n" +
                            $"  actual   ({actual.Length}): {ToHex(actual)}");
        }

        private static byte[] ParseHex(string hex)
        {
            var parts = hex.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            var bytes = new byte[parts.Length];
            for (int i = 0; i < parts.Length; i++)
                bytes[i] = Convert.ToByte(parts[i], 16);
            return bytes;
        }

        private static string ToHex(byte[] b) => string.Join(' ', b.Select(x => x.ToString("x2")));
    }
}
