using System.Text.Json;
using NUnit.Framework;
using Vanaheimr.V2G.Exi.Tests.Infrastructure;

namespace Vanaheimr.V2G.Exi.Tests;

/// <summary>
/// Differential wire conformance for ISO 15118-20: the generated codec must produce exactly the
/// bytes cbV2G produces for each target message, across all three Phase-4 message sets
/// (CommonMessages, DC, AC). Each set has its own generated assembly/namespace, its own vector file,
/// and its own <c>Iso15118_20&lt;Set&gt;Fixtures.TryEncode(name, buf, out n)</c> — kept separate so
/// this test file never needs to reference the (colliding) generated types directly.
/// </summary>
[TestFixture]
public class Iso15118_20VectorTests
{
    public sealed record Vec(string Name, string ExpectedHex);

    private static IEnumerable<TestCaseData> Vectors(string fileName)
    {
        var path = Path.Combine(TestContext.CurrentContext.TestDirectory, "Vectors", fileName);
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        foreach (var v in doc.RootElement.GetProperty("vectors").EnumerateArray())
        {
            var name = v.GetProperty("name").GetString()!;
            yield return new TestCaseData(new Vec(name, v.GetProperty("expectedHex").GetString()!)).SetName(name);
        }
    }

    private static IEnumerable<TestCaseData> CommonVectors() => Vectors("Iso15118_20.CommonMessages.vectors.json");
    private static IEnumerable<TestCaseData> DcVectors() => Vectors("Iso15118_20.DC.vectors.json");
    private static IEnumerable<TestCaseData> AcVectors() => Vectors("Iso15118_20.AC.vectors.json");

    [TestCaseSource(nameof(CommonVectors))]
    public void CommonMessages_Matches_CbV2G(Vec vector) =>
        AssertMatches(vector, Iso15118_20CommonFixtures.TryEncode);

    [TestCaseSource(nameof(DcVectors))]
    public void DC_Matches_CbV2G(Vec vector) =>
        AssertMatches(vector, Iso15118_20DcFixtures.TryEncode);

    [TestCaseSource(nameof(AcVectors))]
    public void AC_Matches_CbV2G(Vec vector) =>
        AssertMatches(vector, Iso15118_20AcFixtures.TryEncode);

    private delegate bool TryEncodeFn(string vectorName, byte[] dest, out int bytesWritten);

    private static void AssertMatches(Vec vector, TryEncodeFn tryEncode)
    {
        var buf = new byte[512];
        Assert.That(tryEncode(vector.Name, buf, out int n), Is.True, "encode failed");

        var actual = buf.AsSpan(0, n).ToArray();
        var expected = ParseHex(vector.ExpectedHex);

        if (!actual.AsSpan().SequenceEqual(expected))
            Assert.Fail($"{vector.Name}: generated bytes diverge from cbV2G.\n" +
                        $"  expected ({expected.Length}): {ToHex(expected)}\n" +
                        $"  actual   ({actual.Length}): {ToHex(actual)}");
    }

    private static byte[] ParseHex(string hex)
    {
        var parts = hex.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var bytes = new byte[parts.Length];
        for (int i = 0; i < parts.Length; i++)
            bytes[i] = Convert.ToByte(parts[i], 16);
        return bytes;
    }

    private static string ToHex(byte[] b) => string.Join(' ', b.Select(x => x.ToString("x2")));
}
