using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Vanaheimr.V2G.Exi.SourceGenerator.Grammar;

namespace Vanaheimr.V2G.Exi.SourceGenerator.Emit;

/// <summary>
/// Produces C# source from a <see cref="SchemaPlan"/>.
/// One emitted file per schema, containing record types, enum types, and a
/// static codec class. The generated codec mirrors the structure of the
/// hand-written <c>SupportedAppProtocolCodec</c> so the AppProtocol bytes
/// are byte-equivalent.
///
/// <para>
/// <b>Wire model: non-strict schema-informed EXI grammar</b>, as produced by
/// EVerest's cbexigen / libcbv2g (the de-facto ISO 15118 reference). Every
/// structural transition carries an explicit event code:
/// </para>
/// <list type="bullet">
///   <item>Document element selector: <c>ceil(log2(globals+1))</c> bits (cbexigen
///         reserves one slot for the generic production).</item>
///   <item>Simple child element: SE (1 bit = 0), value-start (1 bit = 0), value,
///         child EE (1 bit = 0).</item>
///   <item>Complex child element: SE (1 bit = 0) then the nested content (which
///         emits its own element EE).</item>
///   <item>Required list: first item 1-bit SE, following items and the terminator
///         a 2-bit event code (item = 0, EE = 1).</item>
///   <item>Trailing optional element: 2-bit event code (present = 0, EE = 1).</item>
///   <item>Element EE of a sequence that does not end in a list/optional: 1 bit = 0.</item>
/// </list>
/// </summary>
internal sealed class CodecEmitter
{
    private const string GeneratedNamespace = "Vanaheimr.V2G.AppProtocol.Generated";

    private readonly StringBuilder _sb = new();
    private readonly SchemaPlan _plan;
    private readonly HashSet<string> _emittedRecords = new(StringComparer.Ordinal);
    private readonly Dictionary<string, SequencePlan> _byRecordName = new(StringComparer.Ordinal);

    private CodecEmitter(SchemaPlan plan)
    {
        _plan = plan;
        foreach (var sp in plan.ComplexTypes.Values)
            _byRecordName[sp.CSharpRecordName] = sp;
    }

    public static string Emit(SchemaPlan plan) => new CodecEmitter(plan).Run();

    private string Run()
    {
        _sb.AppendLine("// <auto-generated/>");
        _sb.AppendLine("// Generated by Vanaheimr.V2G.Exi.SourceGenerator. Do not edit by hand.");
        _sb.AppendLine("#nullable enable");
        _sb.AppendLine("using System;");
        _sb.AppendLine("using System.Collections.Generic;");
        _sb.AppendLine("using System.IO;");
        _sb.AppendLine("using Vanaheimr.V2G.Exi;");
        _sb.AppendLine();
        _sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        _sb.AppendLine();

        EmitEnums();
        EmitRecords();
        EmitCodec();

        return _sb.ToString();
    }

    // -----------------------------------------------------------------------
    //  Enums — declaration order; the enum value IS the EXI n-bit index.
    // -----------------------------------------------------------------------

    private void EmitEnums()
    {
        foreach (var e in _plan.Enums)
        {
            _sb.Append("public enum ").Append(e.Name).AppendLine(" : byte");
            _sb.AppendLine("{");
            for (int i = 0; i < e.Members.Count; i++)
            {
                _sb.Append("    ").Append(e.Members[i]).Append(" = ").Append(i);
                _sb.AppendLine(i + 1 < e.Members.Count ? "," : "");
            }
            _sb.AppendLine("}");
            _sb.AppendLine();
        }
    }

    // -----------------------------------------------------------------------
    //  Records — emit dependencies first, deduplicated
    // -----------------------------------------------------------------------

    private void EmitRecords()
    {
        foreach (var sp in _plan.ComplexTypes.Values
                                  .OrderBy(s => DependencyDepth(s)))
        {
            EmitRecord(sp);
        }
    }

    private int DependencyDepth(SequencePlan sp)
    {
        int max = 0;
        foreach (var c in sp.Children)
        {
            if (c.Value is ValueEncoding.ComplexRef cr &&
                _plan.ComplexTypes.TryGetValue(cr.TypeName, out var inner))
            {
                max = Math.Max(max, 1 + DependencyDepth(inner));
            }
        }
        return max;
    }

    private void EmitRecord(SequencePlan sp)
    {
        if (!_emittedRecords.Add(sp.CSharpRecordName)) return;

        string keyword = sp.IsAbstract ? "abstract" : "sealed";

        // Inheritance: the first N flattened children are the base type's, so they are passed
        // straight through to the base record's constructor (C# positional-record pattern).
        string baseClause = "";
        if (sp.BaseRecordName is not null)
        {
            var baseArgs = _byRecordName.TryGetValue(sp.BaseRecordName, out var basePlan)
                ? string.Join(", ", basePlan.Children.Select(bc => bc.FieldName))
                : "";
            baseClause = $" : {sp.BaseRecordName}({baseArgs})";
        }

        // Parameters: optional attributes first (nullable), then the content particles.
        var parameters = new List<string>();
        if (sp.Attributes is not null)
            foreach (var a in sp.Attributes)
                parameters.Add($"{a.CSharpType}? {a.FieldName}");
        if (sp.SimpleContent is not null)
            parameters.Add($"{sp.SimpleContentType} Value");
        foreach (var c in sp.Children)
        {
            string typeText = c.Shape switch
            {
                ChildShape.BoundedRepeating => $"IReadOnlyList<{c.CSharpType}>",
                ChildShape.OptionalSingle   => c.CSharpType + "?",
                _                           => c.CSharpType,
            };
            parameters.Add($"{typeText} {c.FieldName}");
        }

        if (parameters.Count == 0)
        {
            _sb.Append("public ").Append(keyword).Append(" record ").Append(sp.CSharpRecordName)
               .Append("()").Append(baseClause).AppendLine(";");
            _sb.AppendLine();
            return;
        }

        _sb.Append("public ").Append(keyword).Append(" record ").Append(sp.CSharpRecordName).AppendLine("(");
        for (int i = 0; i < parameters.Count; i++)
        {
            _sb.Append("    ").Append(parameters[i]);
            _sb.AppendLine(i + 1 < parameters.Count ? "," : "");
        }
        _sb.Append(")").Append(baseClause).AppendLine(";");
        _sb.AppendLine();
    }

    // -----------------------------------------------------------------------
    //  Codec
    // -----------------------------------------------------------------------

    private void EmitCodec()
    {
        _sb.AppendLine("public static class SupportedAppProtocolCodec");
        _sb.AppendLine("{");
        _sb.AppendLine("    public const byte ExiHeader = 0x80;");
        _sb.AppendLine();

        var globals = _plan.GlobalElements
                           .OrderBy(g => g.XsdName, StringComparer.Ordinal)
                           .ToList();
        // Non-strict document grammar: reserve one extra production slot.
        int docBits = BitsForChoices(globals.Count + 1);

        // Public encode entry points (one extension method per global element).
        for (int idx = 0; idx < globals.Count; idx++)
            EmitEncodeEntryPoint(globals[idx], idx, docBits);

        // DecodeAny dispatcher.
        EmitDecodeDispatcher(globals, docBits);

        // Per-complex-type encode/decode methods, deduplicated by record name.
        var seenComplex = new HashSet<string>(StringComparer.Ordinal);
        foreach (var sp in _plan.ComplexTypes.Values
                                  .OrderBy(s => s.CSharpRecordName, StringComparer.Ordinal))
        {
            if (!seenComplex.Add(sp.CSharpRecordName)) continue;
            EmitEncodeMethod(sp);
            EmitDecodeMethod(sp);
        }

        _sb.AppendLine("}");
    }

    private void EmitEncodeEntryPoint(GlobalElementPlan g, int idx, int docBits)
    {
        _sb.Append("    public static bool TryEncode(this ")
           .Append(g.CSharpTypeName)
           .AppendLine(" msg, Span<byte> dest, out int bytesWritten)");
        _sb.AppendLine("    {");
        _sb.AppendLine("        bytesWritten = 0;");
        _sb.AppendLine("        if (dest.Length < 1) return false;");
        _sb.AppendLine("        dest[0] = ExiHeader;");
        _sb.AppendLine("        var w = new BitWriter(dest[1..]);");
        if (docBits > 0)
            _sb.Append("        w.WriteBits(").Append(idx).Append(", ").Append(docBits).AppendLine(");   // document element selector");
        _sb.Append("        Encode_").Append(g.Body.CSharpRecordName).AppendLine("(ref w, msg);");
        _sb.AppendLine("        w.AlignToByte();");
        _sb.AppendLine("        bytesWritten = 1 + w.BytesWritten;");
        _sb.AppendLine("        return true;");
        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    private void EmitDecodeDispatcher(List<GlobalElementPlan> globals, int docBits)
    {
        _sb.AppendLine("    public static object DecodeAny(ReadOnlySpan<byte> src, out int bytesConsumed)");
        _sb.AppendLine("    {");
        _sb.AppendLine("        if (src.Length < 1 || src[0] != ExiHeader)");
        _sb.AppendLine("            throw new InvalidDataException(\"Invalid EXI header.\");");
        _sb.AppendLine("        var r = new BitReader(src[1..]);");

        if (docBits > 0)
        {
            _sb.Append("        uint sel = r.ReadBits(").Append(docBits).AppendLine(");");
            _sb.AppendLine("        object result = sel switch");
            _sb.AppendLine("        {");
            for (int idx = 0; idx < globals.Count; idx++)
            {
                _sb.Append("            ").Append(idx).Append("u => Decode_")
                   .Append(globals[idx].Body.CSharpRecordName).AppendLine("(ref r),");
            }
            _sb.AppendLine("            _ => throw new InvalidDataException($\"Unknown document index {sel}.\"),");
            _sb.AppendLine("        };");
        }
        else
        {
            _sb.Append("        object result = Decode_")
               .Append(globals[0].Body.CSharpRecordName).AppendLine("(ref r);");
        }

        _sb.AppendLine("        bytesConsumed = 1 + r.BytesConsumed;");
        _sb.AppendLine("        return result;");
        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    // -----------------------------------------------------------------------
    //  Encode_<RecordName>
    // -----------------------------------------------------------------------

    private void EmitEncodeMethod(SequencePlan sp)
    {
        _sb.Append("    private static void Encode_").Append(sp.CSharpRecordName)
           .Append("(ref BitWriter w, ").Append(sp.CSharpRecordName).AppendLine(" msg)");
        _sb.AppendLine("    {");

        if (IsBoundedRepeating(sp, out var rep))
        {
            _sb.Append("        var list = msg.").Append(rep.FieldName).AppendLine(";");
            _sb.Append("        if (list.Count is < ").Append(Math.Max(1, sp.ListMin))
               .Append(" or > ").Append(sp.ListMax)
               .AppendLine(") throw new ArgumentOutOfRangeException(nameof(msg));");
            _sb.AppendLine("        for (int i = 0; i < list.Count; i++)");
            _sb.AppendLine("        {");
            _sb.AppendLine("            w.WriteBits(0, i == 0 ? 1 : 2);   // SE(item): 1-bit first, 2-bit loop");
            EmitEncodeContent(rep, "list[i]", "            ");
            _sb.AppendLine("        }");
            _sb.AppendLine("        w.WriteBits(1, 2);   // list terminator / element EE");
        }
        else if (sp.SimpleContent is not null)
        {
            EmitRequiredAttributePrefix(sp);   // no-op when there are no attributes
            var valueChild = new ChildPlan("Value", sp.SimpleContentType!, false,
                                           ChildShape.RequiredSingle, sp.SimpleContent!);
            _sb.AppendLine("        w.WriteBits(0, 1);   // CONTENT event");
            EmitWriteValue(valueChild, "msg.Value", "        ");
            _sb.AppendLine("        w.WriteBits(0, 1);   // element EE");
        }
        else if (sp.Attributes is { Count: 1 } && sp.Attributes[0].Required)
        {
            EmitRequiredAttributePrefix(sp);
            EmitEncodeContentBody(sp);
        }
        else if (sp.Attributes is not null)
        {
            EmitEncodeWithAttributes(sp);   // optional attribute (merged with the first content SE)
        }
        else
        {
            EmitEncodeContentBody(sp);
        }

        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    /// <summary>A required attribute is always present: a 1-bit AT event, then its value.</summary>
    private void EmitRequiredAttributePrefix(SequencePlan sp)
    {
        if (sp.Attributes is not { Count: 1 } || !sp.Attributes[0].Required) return;
        var attr = sp.Attributes[0];
        _sb.AppendLine("        w.WriteBits(0, 1);   // AT(required attribute)");
        _sb.Append("        ExiPrimitives.WriteStringValue(ref w, msg.").Append(attr.FieldName).AppendLine("!);");
    }

    /// <summary>Emit a complex type's content (an xs:choice or an xs:sequence) plus its element EE.</summary>
    private void EmitEncodeContentBody(SequencePlan sp)
    {
        if (sp.IsChoice)
        {
            EmitEncodeChoice(sp);
            _sb.AppendLine("        w.WriteBits(0, 1);   // element EE");
            return;
        }

        bool lastTerminates = LastChildTerminatesElement(sp);
        for (int ci = 0; ci < sp.Children.Count; ci++)
        {
            var c = sp.Children[ci];
            if (c.Shape == ChildShape.OptionalSingle)
            {
                if (ci != sp.Children.Count - 1)
                    throw new NotSupportedException(
                        $"complexType '{sp.CSharpRecordName}': optional element '{c.FieldName}' " +
                        "is only supported as the final child of a sequence in this prototype.");
                EmitEncodeOptionalTrailing(c);
            }
            else if (c.Shape == ChildShape.BoundedRepeating)
            {
                EmitEncodeRepeatingChild(c, "        ");
            }
            else if (c.Value is ValueEncoding.SubstitutionChoice sc)
            {
                EmitEncodeSubstitution(c, sc);
            }
            else
            {
                _sb.AppendLine("        w.WriteBits(0, 1);   // SE");
                EmitEncodeContent(c, "msg." + c.FieldName, "        ");
            }
        }
        if (!lastTerminates)
            _sb.AppendLine("        w.WriteBits(0, 1);   // element EE");
    }

    /// <summary>
    /// xs:choice: exactly one alternative is set. An n-bit event code (declaration order)
    /// selects it, followed by its content (no surrounding SE — the code is the selector).
    /// </summary>
    private void EmitEncodeChoice(SequencePlan sp)
    {
        int width = BitsForChoices(sp.Children.Count + 1);
        for (int i = 0; i < sp.Children.Count; i++)
        {
            var c = sp.Children[i];
            string accessor = c.IsCSharpNullable ? $"msg.{c.FieldName}!.Value" : $"msg.{c.FieldName}!";
            _sb.Append("        ").Append(i == 0 ? "if" : "else if")
               .Append(" (msg.").Append(c.FieldName).AppendLine(" is not null)");
            _sb.AppendLine("        {");
            _sb.Append("            w.WriteBits(").Append(i).Append(", ").Append(width)
               .Append(");   // ").AppendLine(c.FieldName);
            EmitEncodeContent(c, accessor, "            ");
            _sb.AppendLine("        }");
        }
        _sb.Append("        else throw new ArgumentException(\"no choice alternative set for ")
           .Append(sp.CSharpRecordName).AppendLine("\");");
    }

    /// <summary>
    /// Emits the content of a child element after its SE event has been written:
    /// for a complex child the nested encode call (which contains its own EE);
    /// for a simple child the value-start event, the value, and the child EE.
    /// </summary>
    private void EmitEncodeContent(ChildPlan c, string accessor, string indent)
    {
        if (c.Value is ValueEncoding.ComplexRef cr)
        {
            _sb.Append(indent).Append("Encode_").Append(cr.TypeName)
               .Append("(ref w, ").Append(accessor).AppendLine(");");
        }
        else
        {
            _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // value-start");
            EmitWriteValue(c, accessor, indent);
            _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // child EE");
        }
    }

    /// <summary>
    /// Substitution-group choice: an n-bit event code selects the concrete member type, then
    /// its content is encoded directly (no surrounding SE/EE — the event code IS the selector).
    /// Dispatch is by runtime type; the abstract head has a production slot but no case.
    /// </summary>
    private void EmitEncodeSubstitution(ChildPlan c, ValueEncoding.SubstitutionChoice sc)
    {
        _sb.Append("        switch (msg.").Append(c.FieldName).AppendLine(")");
        _sb.AppendLine("        {");
        for (int i = 0; i < sc.Members.Count; i++)
        {
            var m = sc.Members[i];
            if (m.IsAbstractHead) continue; // abstract — never a runtime instance
            _sb.Append("            case ").Append(m.CSharpTypeName).Append(" v:");
            _sb.AppendLine();
            _sb.Append("                w.WriteBits(").Append(i).Append(", ").Append(sc.BitWidth)
               .Append(");   // ").Append(m.ElementName).AppendLine();
            _sb.Append("                Encode_").Append(m.CSharpTypeName).AppendLine("(ref w, v);");
            _sb.AppendLine("                break;");
        }
        _sb.Append("            default: throw new ArgumentException(\"Unsupported substitution member for ")
           .Append(c.FieldName).AppendLine("\");");
        _sb.AppendLine("        }");
    }

    // -----------------------------------------------------------------------
    //  Attributes (AT events): a single optional attribute preceding the content.
    //  The initial grammar state chooses between AT(attr) and SE(first content); when the
    //  attribute is absent the same n-bit code doubles as that first SE (cbexigen model,
    //  verified against CertificateChainType). Attribute values carry no value-start bit.
    // -----------------------------------------------------------------------

    private void EmitEncodeWithAttributes(SequencePlan sp)
    {
        var a = SingleStringAttribute(sp);
        int w = BitsForChoices(sp.Attributes!.Count + 2);
        int absentCode = sp.Attributes.Count;

        _sb.Append("        if (msg.").Append(a.FieldName).AppendLine(" is not null)");
        _sb.AppendLine("        {");
        _sb.Append("            w.WriteBits(0, ").Append(w).AppendLine(");   // AT(attribute)");
        _sb.Append("            ExiPrimitives.WriteStringValue(ref w, msg.").Append(a.FieldName).AppendLine("!);");
        _sb.AppendLine("            w.WriteBits(0, 1);   // SE(first content)");
        EmitEncodeContentTail(sp, "            ");
        _sb.AppendLine("        }");
        _sb.AppendLine("        else");
        _sb.AppendLine("        {");
        _sb.Append("            w.WriteBits(").Append(absentCode).Append(", ").Append(w)
           .AppendLine(");   // SE(first content), attribute absent");
        EmitEncodeContentTail(sp, "            ");
        _sb.AppendLine("        }");
    }

    /// <summary>Encode the content particles after the first child's SE has already been written.</summary>
    private void EmitEncodeContentTail(SequencePlan sp, string indent)
    {
        var c0 = sp.Children[0];
        EmitEncodeContent(c0, "msg." + c0.FieldName, indent);

        bool endsWithOptional = sp.Children[sp.Children.Count - 1].Shape == ChildShape.OptionalSingle;
        for (int i = 1; i < sp.Children.Count; i++)
        {
            var c = sp.Children[i];
            if (c.Shape == ChildShape.OptionalSingle)
            {
                if (i != sp.Children.Count - 1)
                    throw new NotSupportedException(
                        $"{sp.CSharpRecordName}: optional element '{c.FieldName}' must be the last child.");
                EmitEncodeOptionalTrailing(c);
            }
            else
            {
                _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // SE");
                EmitEncodeContent(c, "msg." + c.FieldName, indent);
            }
        }
        if (!endsWithOptional)
            _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // element EE");
    }

    private void EmitDecodeWithAttributes(SequencePlan sp)
    {
        var a = SingleStringAttribute(sp);
        int w = BitsForChoices(sp.Attributes!.Count + 2);
        int absentCode = sp.Attributes.Count;
        var c0 = sp.Children[0];

        _sb.Append("        ").Append(a.CSharpType).Append("? _").Append(a.FieldName).AppendLine(" = default;");
        _sb.Append("        ").Append(c0.CSharpType).Append(" _").Append(c0.FieldName).AppendLine(" = default!;");
        _sb.Append("        switch (r.ReadBits(").Append(w).AppendLine("))");
        _sb.AppendLine("        {");
        _sb.AppendLine("            case 0u:   // AT(attribute) present");
        _sb.Append("                _").Append(a.FieldName).AppendLine(" = ExiPrimitives.ReadStringValue(ref r);");
        _sb.AppendLine("                r.ReadBits(1);   // SE(first content)");
        EmitDecodeContent(c0, "_" + c0.FieldName, "                ", declare: false);
        _sb.AppendLine("                break;");
        _sb.Append("            case ").Append(absentCode).AppendLine("u:   // SE(first content), attribute absent");
        EmitDecodeContent(c0, "_" + c0.FieldName, "                ", declare: false);
        _sb.AppendLine("                break;");
        _sb.AppendLine("            default: throw new InvalidDataException(\"invalid attribute/first-element event code\");");
        _sb.AppendLine("        }");

        var locals = new List<string> { "_" + a.FieldName, "_" + c0.FieldName };
        bool endsWithOptional = sp.Children[sp.Children.Count - 1].Shape == ChildShape.OptionalSingle;
        for (int i = 1; i < sp.Children.Count; i++)
        {
            var c = sp.Children[i];
            string local = "_" + c.FieldName;
            locals.Add(local);
            if (c.Shape == ChildShape.OptionalSingle)
            {
                _sb.Append("        ").Append(c.CSharpType).Append("? ").Append(local).AppendLine(" = default;");
                _sb.AppendLine("        {");
                _sb.AppendLine("            uint ec = r.ReadBits(2);   // present = 0, EE = 1");
                _sb.AppendLine("            if (ec == 0)");
                _sb.AppendLine("            {");
                EmitDecodeContent(c, local, "                ", declare: false);
                _sb.AppendLine("                r.ReadBits(1);   // element EE");
                _sb.AppendLine("            }");
                _sb.AppendLine("        }");
            }
            else
            {
                _sb.AppendLine("        r.ReadBits(1);   // SE");
                EmitDecodeContent(c, local, "        ", declare: true);
            }
        }
        if (!endsWithOptional)
            _sb.AppendLine("        r.ReadBits(1);   // element EE");

        _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
           .Append(string.Join(", ", locals)).AppendLine(");");
    }

    private static AttrPlan SingleStringAttribute(SequencePlan sp)
    {
        if (sp.Attributes!.Count != 1)
            throw new NotSupportedException($"{sp.CSharpRecordName}: only a single attribute is supported yet.");
        if (sp.Children.Count == 0)
            throw new NotSupportedException($"{sp.CSharpRecordName}: attribute-only complex types are not supported yet.");
        var a = sp.Attributes[0];
        if (a.Value is not ValueEncoding.StringValue)
            throw new NotSupportedException($"{sp.CSharpRecordName}: only string-typed attributes are supported yet.");
        var c0 = sp.Children[0];
        if (c0.Shape != ChildShape.RequiredSingle || c0.Value is ValueEncoding.SubstitutionChoice)
            throw new NotSupportedException($"{sp.CSharpRecordName}: the first content child must be a required, non-substitution element.");
        foreach (var c in sp.Children)
            if (c.Shape == ChildShape.BoundedRepeating)
                throw new NotSupportedException($"{sp.CSharpRecordName}: attributes with repeating content are not supported yet.");
        return a;
    }

    private static bool LastChildTerminatesElement(SequencePlan sp)
    {
        if (sp.Children.Count == 0) return false;
        var last = sp.Children[sp.Children.Count - 1].Shape;
        return last is ChildShape.OptionalSingle or ChildShape.BoundedRepeating;
    }

    /// <summary>
    /// A repeating element occurring as the last child of a sequence: the first item is
    /// preceded by a 1-bit SE, each further item by a 2-bit loop code, and a 2-bit code
    /// terminates the list (which also serves as the element EE).
    /// </summary>
    private void EmitEncodeRepeatingChild(ChildPlan c, string indent)
    {
        string list = c.FieldName + "_list";
        _sb.Append(indent).Append("var ").Append(list).Append(" = msg.").Append(c.FieldName).AppendLine(";");
        _sb.Append(indent).Append("if (").Append(list).Append(".Count is < ").Append(Math.Max(1, c.ListMin))
           .Append(" or > ").Append(c.ListMax).AppendLine(") throw new ArgumentOutOfRangeException(nameof(msg));");
        _sb.Append(indent).Append("for (int i = 0; i < ").Append(list).AppendLine(".Count; i++)");
        _sb.Append(indent).AppendLine("{");
        _sb.Append(indent).AppendLine("    w.WriteBits(0, i == 0 ? 1 : 2);   // SE(item): 1-bit first, 2-bit loop");
        EmitEncodeContent(c, list + "[i]", indent + "    ");
        _sb.Append(indent).AppendLine("}");
        _sb.Append(indent).AppendLine("w.WriteBits(1, 2);   // list terminator / element EE");
    }

    private void EmitDecodeRepeatingChild(ChildPlan c, string local, string indent)
    {
        _sb.Append(indent).Append("var ").Append(local).Append(" = new List<").Append(c.CSharpType).AppendLine(">();");
        _sb.Append(indent).AppendLine("r.ReadBits(1);   // SE(item) first");
        EmitDecodeContent(c, local + "_first", indent, declare: true);
        _sb.Append(indent).Append(local).Append(".Add(").Append(local).AppendLine("_first);");
        _sb.Append(indent).AppendLine("while (true)");
        _sb.Append(indent).AppendLine("{");
        _sb.Append(indent).AppendLine("    uint ec = r.ReadBits(2);");
        _sb.Append(indent).AppendLine("    if (ec == 1) break;   // element EE");
        _sb.Append(indent).Append("    if (ec != 0 || ").Append(local).Append(".Count >= ").Append(c.ListMax)
           .AppendLine(") throw new InvalidDataException(\"invalid repeating-element event code\");");
        EmitDecodeContent(c, local + "_next", indent + "    ", declare: true);
        _sb.Append(indent).Append("    ").Append(local).Append(".Add(").Append(local).AppendLine("_next);");
        _sb.Append(indent).AppendLine("}");
    }

    private void EmitEncodeOptionalTrailing(ChildPlan c)
    {
        string presence = c.IsCSharpNullable
            ? $"msg.{c.FieldName}.HasValue"
            : $"msg.{c.FieldName} is not null";
        string accessor = c.IsCSharpNullable
            ? $"msg.{c.FieldName}!.Value"
            : $"msg.{c.FieldName}!";

        _sb.Append("        if (").Append(presence).AppendLine(")");
        _sb.AppendLine("        {");
        _sb.AppendLine("            w.WriteBits(0, 2);   // SE(optional present)");
        EmitEncodeContent(c, accessor, "            ");
        _sb.AppendLine("            w.WriteBits(0, 1);   // element EE");
        _sb.AppendLine("        }");
        _sb.AppendLine("        else { w.WriteBits(1, 2); }   // element EE (optional absent)");
    }

    private void EmitWriteValue(ChildPlan c, string accessor, string indent)
    {
        switch (c.Value)
        {
            case ValueEncoding.UnsignedInt:
                _sb.Append(indent).Append("ExiPrimitives.WriteUnsignedInteger(ref w, (ulong)")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.SignedInt:
                _sb.Append(indent).Append("ExiPrimitives.WriteSignedInteger(ref w, (long)")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.Binary:
                _sb.Append(indent).Append("ExiPrimitives.WriteBinary(ref w, ")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.StringValue:
                _sb.Append(indent).Append("ExiPrimitives.WriteStringValue(ref w, ")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.NBitUnsigned nb when nb.Bias != 0:
                _sb.Append(indent).Append("w.WriteBits((uint)((long)")
                   .Append(accessor).Append(" - ").Append(nb.Bias).Append("), ")
                   .Append(nb.BitWidth).AppendLine(");");
                break;
            case ValueEncoding.NBitUnsigned nb:
                _sb.Append(indent).Append("w.WriteBits((uint)").Append(accessor)
                   .Append(", ").Append(nb.BitWidth).AppendLine(");");
                break;
            case ValueEncoding.EnumIndex ei:
                // The C# enum value equals the XSD declaration index == the EXI n-bit index.
                _sb.Append(indent).Append("w.WriteBits((uint)").Append(accessor)
                   .Append(", ").Append(ei.BitWidth).AppendLine(");");
                break;
        }
    }

    // -----------------------------------------------------------------------
    //  Decode_<RecordName>
    // -----------------------------------------------------------------------

    private void EmitDecodeMethod(SequencePlan sp)
    {
        _sb.Append("    private static ").Append(sp.CSharpRecordName)
           .Append(" Decode_").Append(sp.CSharpRecordName).AppendLine("(ref BitReader r)");
        _sb.AppendLine("    {");

        if (IsBoundedRepeating(sp, out var rep))
        {
            _sb.Append("        var list = new List<").Append(rep.CSharpType).AppendLine(">();");
            _sb.AppendLine("        r.ReadBits(1);   // SE(item) first");
            EmitDecodeContent(rep, "first", "        ", declare: true);
            _sb.AppendLine("        list.Add(first);");
            _sb.AppendLine("        while (true)");
            _sb.AppendLine("        {");
            _sb.AppendLine("            uint ec = r.ReadBits(2);");
            _sb.AppendLine("            if (ec == 1) break;   // element EE");
            _sb.Append("            if (ec != 0 || list.Count >= ").Append(sp.ListMax)
               .AppendLine(") throw new InvalidDataException(\"Invalid AppProtocol list event code.\");");
            EmitDecodeContent(rep, "next", "            ", declare: true);
            _sb.AppendLine("            list.Add(next);");
            _sb.AppendLine("        }");
            _sb.Append("        return new ").Append(sp.CSharpRecordName).AppendLine("(list);");
        }
        else if (sp.SimpleContent is not null)
        {
            var locals = new List<string>();
            if (sp.Attributes is { Count: 1 } && sp.Attributes[0].Required)
            {
                var attr = sp.Attributes[0];
                _sb.AppendLine("        r.ReadBits(1);   // AT(required attribute)");
                _sb.Append("        var _").Append(attr.FieldName).AppendLine(" = ExiPrimitives.ReadStringValue(ref r);");
                locals.Add("_" + attr.FieldName);
            }
            _sb.AppendLine("        r.ReadBits(1);   // CONTENT event");
            var valueChild = new ChildPlan("Value", sp.SimpleContentType!, false,
                                           ChildShape.RequiredSingle, sp.SimpleContent!);
            _sb.Append("        var _Value = ");
            AppendReadValueExpr(valueChild);
            _sb.AppendLine(";");
            locals.Add("_Value");
            _sb.AppendLine("        r.ReadBits(1);   // element EE");
            _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
               .Append(string.Join(", ", locals)).AppendLine(");");
        }
        else if (sp.Attributes is { Count: 1 } && sp.Attributes[0].Required)
        {
            var attr = sp.Attributes[0];
            _sb.AppendLine("        r.ReadBits(1);   // AT(required attribute)");
            _sb.Append("        var _").Append(attr.FieldName).AppendLine(" = ExiPrimitives.ReadStringValue(ref r);");
            EmitDecodeContentBody(sp, new List<string> { "_" + attr.FieldName });
        }
        else if (sp.Attributes is not null)
        {
            EmitDecodeWithAttributes(sp);
        }
        else
        {
            EmitDecodeContentBody(sp, new List<string>());
        }

        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    /// <summary>Decode a complex type's content (xs:choice or xs:sequence) and emit the record return.</summary>
    private void EmitDecodeContentBody(SequencePlan sp, List<string> prefixLocals)
    {
        var locals = new List<string>(prefixLocals);

        if (sp.IsChoice)
        {
            int width = BitsForChoices(sp.Children.Count + 1);
            foreach (var c in sp.Children)
            {
                _sb.Append("        ").Append(c.CSharpType).Append("? _").Append(c.FieldName).AppendLine(" = default;");
                locals.Add("_" + c.FieldName);
            }
            _sb.Append("        switch (r.ReadBits(").Append(width).AppendLine("))");
            _sb.AppendLine("        {");
            for (int i = 0; i < sp.Children.Count; i++)
            {
                var c = sp.Children[i];
                _sb.Append("            case ").Append(i).AppendLine("u:");
                EmitDecodeContent(c, "_" + c.FieldName, "                ", declare: false);
                _sb.AppendLine("                break;");
            }
            _sb.AppendLine("            default: throw new InvalidDataException(\"unknown choice event code\");");
            _sb.AppendLine("        }");
            _sb.AppendLine("        r.ReadBits(1);   // element EE");
            _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
               .Append(string.Join(", ", locals)).AppendLine(");");
            return;
        }

        bool lastTerminates = LastChildTerminatesElement(sp);
        foreach (var c in sp.Children)
        {
            string local = "_" + c.FieldName;
            locals.Add(local);

            if (c.Shape == ChildShape.OptionalSingle)
            {
                _sb.Append("        ").Append(c.CSharpType).Append("? ").Append(local).AppendLine(" = default;");
                _sb.AppendLine("        {");
                _sb.AppendLine("            uint ec = r.ReadBits(2);   // present = 0, EE = 1");
                _sb.AppendLine("            if (ec == 0)");
                _sb.AppendLine("            {");
                EmitDecodeContent(c, local, "                ", declare: false);
                _sb.AppendLine("                r.ReadBits(1);   // element EE");
                _sb.AppendLine("            }");
                _sb.AppendLine("        }");
            }
            else if (c.Shape == ChildShape.BoundedRepeating)
            {
                EmitDecodeRepeatingChild(c, local, "        ");
            }
            else if (c.Value is ValueEncoding.SubstitutionChoice sc)
            {
                EmitDecodeSubstitution(c, local, sc);
            }
            else
            {
                _sb.AppendLine("        r.ReadBits(1);   // SE");
                EmitDecodeContent(c, local, "        ", declare: true);
            }
        }

        if (!lastTerminates)
            _sb.AppendLine("        r.ReadBits(1);   // element EE");

        _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
           .Append(string.Join(", ", locals)).AppendLine(");");
    }

    /// <summary>
    /// Reads the content of a child element after its SE event has been consumed.
    /// Complex child: nested decode (consumes its own EE). Simple child: value-start,
    /// value, child EE. When <paramref name="declare"/> is false the value is assigned
    /// to an existing local (used for optional elements).
    /// </summary>
    private void EmitDecodeContent(ChildPlan c, string local, string indent, bool declare)
    {
        if (c.Value is ValueEncoding.ComplexRef cr)
        {
            _sb.Append(indent);
            _sb.Append(declare ? "var " : "").Append(local).Append(" = Decode_")
               .Append(cr.TypeName).AppendLine("(ref r);");
            return;
        }

        _sb.Append(indent).AppendLine("r.ReadBits(1);   // value-start");
        _sb.Append(indent);
        _sb.Append(declare ? "var " : "").Append(local).Append(" = ");
        AppendReadValueExpr(c);
        _sb.AppendLine(";");
        _sb.Append(indent).AppendLine("r.ReadBits(1);   // child EE");
    }

    /// <summary>Decode side of <see cref="EmitEncodeSubstitution"/>: read the event code and
    /// dispatch to the selected member's decoder.</summary>
    private void EmitDecodeSubstitution(ChildPlan c, string local, ValueEncoding.SubstitutionChoice sc)
    {
        _sb.Append("        ").Append(c.CSharpType).Append(' ').Append(local).AppendLine(";");
        _sb.Append("        switch (r.ReadBits(").Append(sc.BitWidth).AppendLine("))");
        _sb.AppendLine("        {");
        for (int i = 0; i < sc.Members.Count; i++)
        {
            var m = sc.Members[i];
            if (m.IsAbstractHead)
                _sb.Append("            case ").Append(i)
                   .AppendLine("u: throw new InvalidDataException(\"abstract substitution head cannot be decoded\");");
            else
                _sb.Append("            case ").Append(i).Append("u: ").Append(local)
                   .Append(" = Decode_").Append(m.CSharpTypeName).AppendLine("(ref r); break;");
        }
        _sb.AppendLine("            default: throw new InvalidDataException(\"unknown substitution index\");");
        _sb.AppendLine("        }");
    }

    private void AppendReadValueExpr(ChildPlan c)
    {
        switch (c.Value)
        {
            case ValueEncoding.UnsignedInt:
                _sb.Append('(').Append(c.CSharpType)
                   .Append(")ExiPrimitives.ReadUnsignedInteger(ref r)");
                break;
            case ValueEncoding.SignedInt:
                _sb.Append('(').Append(c.CSharpType)
                   .Append(")ExiPrimitives.ReadSignedInteger(ref r)");
                break;
            case ValueEncoding.Binary:
                _sb.Append("ExiPrimitives.ReadBinary(ref r)");
                break;
            case ValueEncoding.StringValue:
                _sb.Append("ExiPrimitives.ReadStringValue(ref r)");
                break;
            case ValueEncoding.NBitUnsigned nb when nb.Bias != 0:
                _sb.Append('(').Append(c.CSharpType).Append(")((long)r.ReadBits(")
                   .Append(nb.BitWidth).Append(") + ").Append(nb.Bias).Append(')');
                break;
            case ValueEncoding.NBitUnsigned nb:
                _sb.Append('(').Append(c.CSharpType).Append(")r.ReadBits(").Append(nb.BitWidth).Append(')');
                break;
            case ValueEncoding.EnumIndex ei:
                _sb.Append('(').Append(ei.EnumName).Append(")r.ReadBits(").Append(ei.BitWidth).Append(')');
                break;
        }
    }

    // -----------------------------------------------------------------------
    //  Helpers
    // -----------------------------------------------------------------------

    private static bool IsBoundedRepeating(SequencePlan sp, out ChildPlan rep)
    {
        if (sp.Children.Count == 1 && sp.Children[0].Shape == ChildShape.BoundedRepeating)
        {
            rep = sp.Children[0];
            return true;
        }
        rep = default!;
        return false;
    }

    private static int BitsForChoices(int n)
    {
        if (n <= 1) return 0;
        int bits = 0;
        int v = n - 1;
        while (v > 0) { bits++; v >>= 1; }
        return bits;
    }
}
