using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Vanaheimr.V2G.Exi.SourceGenerator.Grammar;

namespace Vanaheimr.V2G.Exi.SourceGenerator.Emit;

/// <summary>
/// Produces C# source from a <see cref="SchemaPlan"/>.
/// One emitted file per schema, containing record types, enum types, and a
/// static codec class. The generated codec mirrors the structure of the
/// hand-written <c>SupportedAppProtocolCodec</c> so the AppProtocol bytes
/// are byte-equivalent.
///
/// <para>
/// <b>Wire model: non-strict schema-informed EXI grammar</b>, as produced by
/// EVerest's cbexigen / libcbv2g (the de-facto ISO 15118 reference). Every
/// structural transition carries an explicit event code:
/// </para>
/// <list type="bullet">
///   <item>Document element selector: <c>ceil(log2(globals+1))</c> bits (cbexigen
///         reserves one slot for the generic production).</item>
///   <item>Simple child element: SE (1 bit = 0), value-start (1 bit = 0), value,
///         child EE (1 bit = 0).</item>
///   <item>Complex child element: SE (1 bit = 0) then the nested content (which
///         emits its own element EE).</item>
///   <item>Required list: first item 1-bit SE, following items and the terminator
///         a 2-bit event code (item = 0, EE = 1).</item>
///   <item>Trailing optional element: 2-bit event code (present = 0, EE = 1).</item>
///   <item>Element EE of a sequence that does not end in a list/optional: 1 bit = 0.</item>
/// </list>
/// </summary>
internal sealed class CodecEmitter
{
    private const string GeneratedNamespace = "Vanaheimr.V2G.AppProtocol.Generated";

    private readonly StringBuilder _sb = new();
    private readonly SchemaPlan _plan;
    private readonly HashSet<string> _emittedRecords = new(StringComparer.Ordinal);
    private readonly Dictionary<string, SequencePlan> _byRecordName = new(StringComparer.Ordinal);

    private CodecEmitter(SchemaPlan plan)
    {
        _plan = plan;
        foreach (var sp in plan.ComplexTypes.Values)
            _byRecordName[sp.CSharpRecordName] = sp;
    }

    public static string Emit(SchemaPlan plan) => new CodecEmitter(plan).Run();

    private string Run()
    {
        _sb.AppendLine("// <auto-generated/>");
        _sb.AppendLine("// Generated by Vanaheimr.V2G.Exi.SourceGenerator. Do not edit by hand.");
        _sb.AppendLine("#nullable enable");
        _sb.AppendLine("using System;");
        _sb.AppendLine("using System.Collections.Generic;");
        _sb.AppendLine("using System.IO;");
        _sb.AppendLine("using Vanaheimr.V2G.Exi;");
        _sb.AppendLine();
        _sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        _sb.AppendLine();

        EmitEnums();
        EmitRecords();
        EmitCodec();

        return _sb.ToString();
    }

    // -----------------------------------------------------------------------
    //  Enums — declaration order; the enum value IS the EXI n-bit index.
    // -----------------------------------------------------------------------

    private void EmitEnums()
    {
        foreach (var e in _plan.Enums)
        {
            _sb.Append("public enum ").Append(e.Name).AppendLine(" : byte");
            _sb.AppendLine("{");
            for (int i = 0; i < e.Members.Count; i++)
            {
                _sb.Append("    ").Append(e.Members[i]).Append(" = ").Append(i);
                _sb.AppendLine(i + 1 < e.Members.Count ? "," : "");
            }
            _sb.AppendLine("}");
            _sb.AppendLine();
        }
    }

    // -----------------------------------------------------------------------
    //  Records — emit dependencies first, deduplicated
    // -----------------------------------------------------------------------

    private void EmitRecords()
    {
        foreach (var sp in _plan.ComplexTypes.Values
                                  .OrderBy(s => DependencyDepth(s)))
        {
            EmitRecord(sp);
        }
    }

    private int DependencyDepth(SequencePlan sp)
    {
        int max = 0;
        foreach (var c in sp.Children)
        {
            if (c.Value is ValueEncoding.ComplexRef cr &&
                _plan.ComplexTypes.TryGetValue(cr.TypeName, out var inner))
            {
                max = Math.Max(max, 1 + DependencyDepth(inner));
            }
        }
        return max;
    }

    private void EmitRecord(SequencePlan sp)
    {
        if (!_emittedRecords.Add(sp.CSharpRecordName)) return;

        string keyword = sp.IsAbstract ? "abstract" : "sealed";

        // Inheritance: the first N flattened children are the base type's, so they are passed
        // straight through to the base record's constructor (C# positional-record pattern).
        string baseClause = "";
        if (sp.BaseRecordName is not null)
        {
            var baseArgs = _byRecordName.TryGetValue(sp.BaseRecordName, out var basePlan)
                ? string.Join(", ", basePlan.Children.Select(bc => bc.FieldName))
                : "";
            baseClause = $" : {sp.BaseRecordName}({baseArgs})";
        }

        if (sp.Children.Count == 0)
        {
            _sb.Append("public ").Append(keyword).Append(" record ").Append(sp.CSharpRecordName)
               .Append("()").Append(baseClause).AppendLine(";");
            _sb.AppendLine();
            return;
        }

        _sb.Append("public ").Append(keyword).Append(" record ").Append(sp.CSharpRecordName).AppendLine("(");

        for (int i = 0; i < sp.Children.Count; i++)
        {
            var c = sp.Children[i];
            string typeText = c.Shape switch
            {
                ChildShape.BoundedRepeating => $"IReadOnlyList<{c.CSharpType}>",
                ChildShape.OptionalSingle   => c.CSharpType + "?",
                _                           => c.CSharpType,
            };
            _sb.Append("    ").Append(typeText).Append(' ').Append(c.FieldName);
            _sb.AppendLine(i + 1 < sp.Children.Count ? "," : "");
        }
        _sb.Append(")").Append(baseClause).AppendLine(";");
        _sb.AppendLine();
    }

    // -----------------------------------------------------------------------
    //  Codec
    // -----------------------------------------------------------------------

    private void EmitCodec()
    {
        _sb.AppendLine("public static class SupportedAppProtocolCodec");
        _sb.AppendLine("{");
        _sb.AppendLine("    public const byte ExiHeader = 0x80;");
        _sb.AppendLine();

        var globals = _plan.GlobalElements
                           .OrderBy(g => g.XsdName, StringComparer.Ordinal)
                           .ToList();
        // Non-strict document grammar: reserve one extra production slot.
        int docBits = BitsForChoices(globals.Count + 1);

        // Public encode entry points (one extension method per global element).
        for (int idx = 0; idx < globals.Count; idx++)
            EmitEncodeEntryPoint(globals[idx], idx, docBits);

        // DecodeAny dispatcher.
        EmitDecodeDispatcher(globals, docBits);

        // Per-complex-type encode/decode methods, deduplicated by record name.
        var seenComplex = new HashSet<string>(StringComparer.Ordinal);
        foreach (var sp in _plan.ComplexTypes.Values
                                  .OrderBy(s => s.CSharpRecordName, StringComparer.Ordinal))
        {
            if (!seenComplex.Add(sp.CSharpRecordName)) continue;
            EmitEncodeMethod(sp);
            EmitDecodeMethod(sp);
        }

        _sb.AppendLine("}");
    }

    private void EmitEncodeEntryPoint(GlobalElementPlan g, int idx, int docBits)
    {
        _sb.Append("    public static bool TryEncode(this ")
           .Append(g.CSharpTypeName)
           .AppendLine(" msg, Span<byte> dest, out int bytesWritten)");
        _sb.AppendLine("    {");
        _sb.AppendLine("        bytesWritten = 0;");
        _sb.AppendLine("        if (dest.Length < 1) return false;");
        _sb.AppendLine("        dest[0] = ExiHeader;");
        _sb.AppendLine("        var w = new BitWriter(dest[1..]);");
        if (docBits > 0)
            _sb.Append("        w.WriteBits(").Append(idx).Append(", ").Append(docBits).AppendLine(");   // document element selector");
        _sb.Append("        Encode_").Append(g.Body.CSharpRecordName).AppendLine("(ref w, msg);");
        _sb.AppendLine("        w.AlignToByte();");
        _sb.AppendLine("        bytesWritten = 1 + w.BytesWritten;");
        _sb.AppendLine("        return true;");
        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    private void EmitDecodeDispatcher(List<GlobalElementPlan> globals, int docBits)
    {
        _sb.AppendLine("    public static object DecodeAny(ReadOnlySpan<byte> src, out int bytesConsumed)");
        _sb.AppendLine("    {");
        _sb.AppendLine("        if (src.Length < 1 || src[0] != ExiHeader)");
        _sb.AppendLine("            throw new InvalidDataException(\"Invalid EXI header.\");");
        _sb.AppendLine("        var r = new BitReader(src[1..]);");

        if (docBits > 0)
        {
            _sb.Append("        uint sel = r.ReadBits(").Append(docBits).AppendLine(");");
            _sb.AppendLine("        object result = sel switch");
            _sb.AppendLine("        {");
            for (int idx = 0; idx < globals.Count; idx++)
            {
                _sb.Append("            ").Append(idx).Append("u => Decode_")
                   .Append(globals[idx].Body.CSharpRecordName).AppendLine("(ref r),");
            }
            _sb.AppendLine("            _ => throw new InvalidDataException($\"Unknown document index {sel}.\"),");
            _sb.AppendLine("        };");
        }
        else
        {
            _sb.Append("        object result = Decode_")
               .Append(globals[0].Body.CSharpRecordName).AppendLine("(ref r);");
        }

        _sb.AppendLine("        bytesConsumed = 1 + r.BytesConsumed;");
        _sb.AppendLine("        return result;");
        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    // -----------------------------------------------------------------------
    //  Encode_<RecordName>
    // -----------------------------------------------------------------------

    private void EmitEncodeMethod(SequencePlan sp)
    {
        _sb.Append("    private static void Encode_").Append(sp.CSharpRecordName)
           .Append("(ref BitWriter w, ").Append(sp.CSharpRecordName).AppendLine(" msg)");
        _sb.AppendLine("    {");

        if (IsBoundedRepeating(sp, out var rep))
        {
            _sb.Append("        var list = msg.").Append(rep.FieldName).AppendLine(";");
            _sb.Append("        if (list.Count is < ").Append(Math.Max(1, sp.ListMin))
               .Append(" or > ").Append(sp.ListMax)
               .AppendLine(") throw new ArgumentOutOfRangeException(nameof(msg));");
            _sb.AppendLine("        for (int i = 0; i < list.Count; i++)");
            _sb.AppendLine("        {");
            _sb.AppendLine("            w.WriteBits(0, i == 0 ? 1 : 2);   // SE(item): 1-bit first, 2-bit loop");
            EmitEncodeContent(rep, "list[i]", "            ");
            _sb.AppendLine("        }");
            _sb.AppendLine("        w.WriteBits(1, 2);   // list terminator / element EE");
        }
        else
        {
            bool endsWithOptional = sp.Children.Count > 0 &&
                                    sp.Children[sp.Children.Count - 1].Shape == ChildShape.OptionalSingle;
            for (int ci = 0; ci < sp.Children.Count; ci++)
            {
                var c = sp.Children[ci];
                if (c.Shape == ChildShape.OptionalSingle)
                {
                    if (ci != sp.Children.Count - 1)
                        throw new NotSupportedException(
                            $"complexType '{sp.CSharpRecordName}': optional element '{c.FieldName}' " +
                            "is only supported as the final child of a sequence in this prototype.");
                    EmitEncodeOptionalTrailing(c);
                }
                else if (c.Value is ValueEncoding.SubstitutionChoice sc)
                {
                    EmitEncodeSubstitution(c, sc);
                }
                else
                {
                    _sb.AppendLine("        w.WriteBits(0, 1);   // SE");
                    EmitEncodeContent(c, "msg." + c.FieldName, "        ");
                }
            }
            if (!endsWithOptional)
                _sb.AppendLine("        w.WriteBits(0, 1);   // element EE");
        }

        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    /// <summary>
    /// Emits the content of a child element after its SE event has been written:
    /// for a complex child the nested encode call (which contains its own EE);
    /// for a simple child the value-start event, the value, and the child EE.
    /// </summary>
    private void EmitEncodeContent(ChildPlan c, string accessor, string indent)
    {
        if (c.Value is ValueEncoding.ComplexRef cr)
        {
            _sb.Append(indent).Append("Encode_").Append(cr.TypeName)
               .Append("(ref w, ").Append(accessor).AppendLine(");");
        }
        else
        {
            _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // value-start");
            EmitWriteValue(c, accessor, indent);
            _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // child EE");
        }
    }

    /// <summary>
    /// Substitution-group choice: an n-bit event code selects the concrete member type, then
    /// its content is encoded directly (no surrounding SE/EE — the event code IS the selector).
    /// Dispatch is by runtime type; the abstract head has a production slot but no case.
    /// </summary>
    private void EmitEncodeSubstitution(ChildPlan c, ValueEncoding.SubstitutionChoice sc)
    {
        _sb.Append("        switch (msg.").Append(c.FieldName).AppendLine(")");
        _sb.AppendLine("        {");
        for (int i = 0; i < sc.Members.Count; i++)
        {
            var m = sc.Members[i];
            if (m.IsAbstractHead) continue; // abstract — never a runtime instance
            _sb.Append("            case ").Append(m.CSharpTypeName).Append(" v:");
            _sb.AppendLine();
            _sb.Append("                w.WriteBits(").Append(i).Append(", ").Append(sc.BitWidth)
               .Append(");   // ").Append(m.ElementName).AppendLine();
            _sb.Append("                Encode_").Append(m.CSharpTypeName).AppendLine("(ref w, v);");
            _sb.AppendLine("                break;");
        }
        _sb.Append("            default: throw new ArgumentException(\"Unsupported substitution member for ")
           .Append(c.FieldName).AppendLine("\");");
        _sb.AppendLine("        }");
    }

    private void EmitEncodeOptionalTrailing(ChildPlan c)
    {
        string presence = c.IsCSharpNullable
            ? $"msg.{c.FieldName}.HasValue"
            : $"msg.{c.FieldName} is not null";
        string accessor = c.IsCSharpNullable
            ? $"msg.{c.FieldName}!.Value"
            : $"msg.{c.FieldName}!";

        _sb.Append("        if (").Append(presence).AppendLine(")");
        _sb.AppendLine("        {");
        _sb.AppendLine("            w.WriteBits(0, 2);   // SE(optional present)");
        EmitEncodeContent(c, accessor, "            ");
        _sb.AppendLine("            w.WriteBits(0, 1);   // element EE");
        _sb.AppendLine("        }");
        _sb.AppendLine("        else { w.WriteBits(1, 2); }   // element EE (optional absent)");
    }

    private void EmitWriteValue(ChildPlan c, string accessor, string indent)
    {
        switch (c.Value)
        {
            case ValueEncoding.UnsignedInt:
                _sb.Append(indent).Append("ExiPrimitives.WriteUnsignedInteger(ref w, (ulong)")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.SignedInt:
                _sb.Append(indent).Append("ExiPrimitives.WriteSignedInteger(ref w, (long)")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.Binary:
                _sb.Append(indent).Append("ExiPrimitives.WriteBinary(ref w, ")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.StringValue:
                _sb.Append(indent).Append("ExiPrimitives.WriteStringValue(ref w, ")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.NBitUnsigned nb when nb.Bias != 0:
                _sb.Append(indent).Append("w.WriteBits((uint)((long)")
                   .Append(accessor).Append(" - ").Append(nb.Bias).Append("), ")
                   .Append(nb.BitWidth).AppendLine(");");
                break;
            case ValueEncoding.NBitUnsigned nb:
                _sb.Append(indent).Append("w.WriteBits((uint)").Append(accessor)
                   .Append(", ").Append(nb.BitWidth).AppendLine(");");
                break;
            case ValueEncoding.EnumIndex ei:
                // The C# enum value equals the XSD declaration index == the EXI n-bit index.
                _sb.Append(indent).Append("w.WriteBits((uint)").Append(accessor)
                   .Append(", ").Append(ei.BitWidth).AppendLine(");");
                break;
        }
    }

    // -----------------------------------------------------------------------
    //  Decode_<RecordName>
    // -----------------------------------------------------------------------

    private void EmitDecodeMethod(SequencePlan sp)
    {
        _sb.Append("    private static ").Append(sp.CSharpRecordName)
           .Append(" Decode_").Append(sp.CSharpRecordName).AppendLine("(ref BitReader r)");
        _sb.AppendLine("    {");

        if (IsBoundedRepeating(sp, out var rep))
        {
            _sb.Append("        var list = new List<").Append(rep.CSharpType).AppendLine(">();");
            _sb.AppendLine("        r.ReadBits(1);   // SE(item) first");
            EmitDecodeContent(rep, "first", "        ", declare: true);
            _sb.AppendLine("        list.Add(first);");
            _sb.AppendLine("        while (true)");
            _sb.AppendLine("        {");
            _sb.AppendLine("            uint ec = r.ReadBits(2);");
            _sb.AppendLine("            if (ec == 1) break;   // element EE");
            _sb.Append("            if (ec != 0 || list.Count >= ").Append(sp.ListMax)
               .AppendLine(") throw new InvalidDataException(\"Invalid AppProtocol list event code.\");");
            EmitDecodeContent(rep, "next", "            ", declare: true);
            _sb.AppendLine("            list.Add(next);");
            _sb.AppendLine("        }");
            _sb.Append("        return new ").Append(sp.CSharpRecordName).AppendLine("(list);");
        }
        else
        {
            var locals = new List<string>();
            bool endsWithOptional = sp.Children.Count > 0 &&
                                    sp.Children[sp.Children.Count - 1].Shape == ChildShape.OptionalSingle;

            foreach (var c in sp.Children)
            {
                string local = "_" + c.FieldName;
                locals.Add(local);

                if (c.Shape == ChildShape.OptionalSingle)
                {
                    _sb.Append("        ").Append(c.CSharpType).Append("? ").Append(local).AppendLine(" = default;");
                    _sb.AppendLine("        {");
                    _sb.AppendLine("            uint ec = r.ReadBits(2);   // present = 0, EE = 1");
                    _sb.AppendLine("            if (ec == 0)");
                    _sb.AppendLine("            {");
                    EmitDecodeContent(c, local, "                ", declare: false);
                    _sb.AppendLine("                r.ReadBits(1);   // element EE");
                    _sb.AppendLine("            }");
                    _sb.AppendLine("        }");
                }
                else if (c.Value is ValueEncoding.SubstitutionChoice sc)
                {
                    EmitDecodeSubstitution(c, local, sc);
                }
                else
                {
                    _sb.AppendLine("        r.ReadBits(1);   // SE");
                    EmitDecodeContent(c, local, "        ", declare: true);
                }
            }

            if (!endsWithOptional)
                _sb.AppendLine("        r.ReadBits(1);   // element EE");

            _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
               .Append(string.Join(", ", locals)).AppendLine(");");
        }

        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    /// <summary>
    /// Reads the content of a child element after its SE event has been consumed.
    /// Complex child: nested decode (consumes its own EE). Simple child: value-start,
    /// value, child EE. When <paramref name="declare"/> is false the value is assigned
    /// to an existing local (used for optional elements).
    /// </summary>
    private void EmitDecodeContent(ChildPlan c, string local, string indent, bool declare)
    {
        if (c.Value is ValueEncoding.ComplexRef cr)
        {
            _sb.Append(indent);
            _sb.Append(declare ? "var " : "").Append(local).Append(" = Decode_")
               .Append(cr.TypeName).AppendLine("(ref r);");
            return;
        }

        _sb.Append(indent).AppendLine("r.ReadBits(1);   // value-start");
        _sb.Append(indent);
        _sb.Append(declare ? "var " : "").Append(local).Append(" = ");
        AppendReadValueExpr(c);
        _sb.AppendLine(";");
        _sb.Append(indent).AppendLine("r.ReadBits(1);   // child EE");
    }

    /// <summary>Decode side of <see cref="EmitEncodeSubstitution"/>: read the event code and
    /// dispatch to the selected member's decoder.</summary>
    private void EmitDecodeSubstitution(ChildPlan c, string local, ValueEncoding.SubstitutionChoice sc)
    {
        _sb.Append("        ").Append(c.CSharpType).Append(' ').Append(local).AppendLine(";");
        _sb.Append("        switch (r.ReadBits(").Append(sc.BitWidth).AppendLine("))");
        _sb.AppendLine("        {");
        for (int i = 0; i < sc.Members.Count; i++)
        {
            var m = sc.Members[i];
            if (m.IsAbstractHead)
                _sb.Append("            case ").Append(i)
                   .AppendLine("u: throw new InvalidDataException(\"abstract substitution head cannot be decoded\");");
            else
                _sb.Append("            case ").Append(i).Append("u: ").Append(local)
                   .Append(" = Decode_").Append(m.CSharpTypeName).AppendLine("(ref r); break;");
        }
        _sb.AppendLine("            default: throw new InvalidDataException(\"unknown substitution index\");");
        _sb.AppendLine("        }");
    }

    private void AppendReadValueExpr(ChildPlan c)
    {
        switch (c.Value)
        {
            case ValueEncoding.UnsignedInt:
                _sb.Append('(').Append(c.CSharpType)
                   .Append(")ExiPrimitives.ReadUnsignedInteger(ref r)");
                break;
            case ValueEncoding.SignedInt:
                _sb.Append('(').Append(c.CSharpType)
                   .Append(")ExiPrimitives.ReadSignedInteger(ref r)");
                break;
            case ValueEncoding.Binary:
                _sb.Append("ExiPrimitives.ReadBinary(ref r)");
                break;
            case ValueEncoding.StringValue:
                _sb.Append("ExiPrimitives.ReadStringValue(ref r)");
                break;
            case ValueEncoding.NBitUnsigned nb when nb.Bias != 0:
                _sb.Append('(').Append(c.CSharpType).Append(")((long)r.ReadBits(")
                   .Append(nb.BitWidth).Append(") + ").Append(nb.Bias).Append(')');
                break;
            case ValueEncoding.NBitUnsigned nb:
                _sb.Append('(').Append(c.CSharpType).Append(")r.ReadBits(").Append(nb.BitWidth).Append(')');
                break;
            case ValueEncoding.EnumIndex ei:
                _sb.Append('(').Append(ei.EnumName).Append(")r.ReadBits(").Append(ei.BitWidth).Append(')');
                break;
        }
    }

    // -----------------------------------------------------------------------
    //  Helpers
    // -----------------------------------------------------------------------

    private static bool IsBoundedRepeating(SequencePlan sp, out ChildPlan rep)
    {
        if (sp.Children.Count == 1 && sp.Children[0].Shape == ChildShape.BoundedRepeating)
        {
            rep = sp.Children[0];
            return true;
        }
        rep = default!;
        return false;
    }

    private static int BitsForChoices(int n)
    {
        if (n <= 1) return 0;
        int bits = 0;
        int v = n - 1;
        while (v > 0) { bits++; v >>= 1; }
        return bits;
    }
}
