using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Vanaheimr.V2G.Exi.SourceGenerator.Grammar;

namespace Vanaheimr.V2G.Exi.SourceGenerator.Emit;

/// <summary>
/// Produces C# source from a <see cref="SchemaPlan"/>.
/// One emitted file per schema, containing record types, enum types, and a
/// static codec class. The generated codec mirrors the structure of the
/// hand-written <c>SupportedAppProtocolCodec</c> so the AppProtocol bytes
/// are byte-equivalent.
///
/// <para>
/// <b>Wire model: non-strict schema-informed EXI grammar</b>, as produced by
/// EVerest's cbexigen / libcbv2g (the de-facto ISO 15118 reference). Every
/// structural transition carries an explicit event code:
/// </para>
/// <list type="bullet">
///   <item>Document element selector: <c>ceil(log2(globals+1))</c> bits (cbexigen
///         reserves one slot for the generic production).</item>
///   <item>Simple child element: SE (1 bit = 0), value-start (1 bit = 0), value,
///         child EE (1 bit = 0).</item>
///   <item>Complex child element: SE (1 bit = 0) then the nested content (which
///         emits its own element EE).</item>
///   <item>Required list: first item 1-bit SE, following items and the terminator
///         a 2-bit event code (item = 0, EE = 1).</item>
///   <item>Trailing optional element: 2-bit event code (present = 0, EE = 1).</item>
///   <item>Element EE of a sequence that does not end in a list/optional: 1 bit = 0.</item>
/// </list>
/// </summary>
internal sealed class CodecEmitter
{
    private const string GeneratedNamespace = "Vanaheimr.V2G.AppProtocol.Generated";

    private readonly StringBuilder _sb = new();
    private readonly SchemaPlan _plan;
    private readonly HashSet<string> _emittedRecords = new(StringComparer.Ordinal);
    private readonly Dictionary<string, SequencePlan> _byRecordName = new(StringComparer.Ordinal);
    private int _runCounter; // unique suffixes for optional-run state locals
    private int _tmpCounter; // unique suffixes for decode temporaries

    private CodecEmitter(SchemaPlan plan)
    {
        _plan = plan;
        foreach (var sp in plan.ComplexTypes.Values)
            _byRecordName[sp.CSharpRecordName] = sp;
    }

    public static string Emit(SchemaPlan plan) => new CodecEmitter(plan).Run();

    private string Run()
    {
        _sb.AppendLine("// <auto-generated/>");
        _sb.AppendLine("// Generated by Vanaheimr.V2G.Exi.SourceGenerator. Do not edit by hand.");
        _sb.AppendLine("#nullable enable");
        _sb.AppendLine("using System;");
        _sb.AppendLine("using System.Collections.Generic;");
        _sb.AppendLine("using System.IO;");
        _sb.AppendLine("using Vanaheimr.V2G.Exi;");
        _sb.AppendLine();
        _sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        _sb.AppendLine();

        EmitEnums();
        EmitOpaqueTypes();
        EmitRecords();
        EmitCodec();

        return _sb.ToString();
    }

    // -----------------------------------------------------------------------
    //  Opaque placeholder records — for references into an un-modelled namespace
    //  (XMLDSig). They exist so the containing record is structurally typed and
    //  round-trips while the element is absent; a present instance fails loud.
    // -----------------------------------------------------------------------

    private void EmitOpaqueTypes()
    {
        foreach (var t in _plan.OpaqueTypes)
        {
            _sb.Append("/// <summary>Opaque placeholder for the un-modelled XMLDSig element <c>")
               .Append(t).AppendLine("</c> (full grammar deferred to Phase 3).</summary>");
            _sb.Append("public sealed record ").Append(t).AppendLine("();");
            _sb.AppendLine();
        }
    }

    // -----------------------------------------------------------------------
    //  Enums — declaration order; the enum value IS the EXI n-bit index.
    // -----------------------------------------------------------------------

    private void EmitEnums()
    {
        foreach (var e in _plan.Enums)
        {
            _sb.Append("public enum ").Append(e.Name).AppendLine(" : byte");
            _sb.AppendLine("{");
            for (int i = 0; i < e.Members.Count; i++)
            {
                _sb.Append("    ").Append(e.Members[i]).Append(" = ").Append(i);
                _sb.AppendLine(i + 1 < e.Members.Count ? "," : "");
            }
            _sb.AppendLine("}");
            _sb.AppendLine();
        }
    }

    // -----------------------------------------------------------------------
    //  Records — emit dependencies first, deduplicated
    // -----------------------------------------------------------------------

    private void EmitRecords()
    {
        foreach (var sp in _plan.ComplexTypes.Values
                                  .OrderBy(s => DependencyDepth(s)))
        {
            EmitRecord(sp);
        }
    }

    private int DependencyDepth(SequencePlan sp)
    {
        int max = 0;
        foreach (var c in sp.Children)
        {
            if (c.Value is ValueEncoding.ComplexRef cr &&
                _plan.ComplexTypes.TryGetValue(cr.TypeName, out var inner))
            {
                max = Math.Max(max, 1 + DependencyDepth(inner));
            }
        }
        return max;
    }

    private void EmitRecord(SequencePlan sp)
    {
        if (!_emittedRecords.Add(sp.CSharpRecordName)) return;

        string keyword = sp.IsAbstract ? "abstract" : "sealed";

        // Inheritance: the first N flattened children are the base type's, so they are passed
        // straight through to the base record's constructor (C# positional-record pattern).
        string baseClause = "";
        if (sp.BaseRecordName is not null)
        {
            var baseArgs = _byRecordName.TryGetValue(sp.BaseRecordName, out var basePlan)
                ? string.Join(", ", basePlan.Children.Select(bc => bc.FieldName))
                : "";
            baseClause = $" : {sp.BaseRecordName}({baseArgs})";
        }

        // Parameters: optional attributes first (nullable), then the content particles.
        var parameters = new List<string>();
        if (sp.Attributes is not null)
            foreach (var a in sp.Attributes)
                parameters.Add($"{a.CSharpType}? {a.FieldName}");
        if (sp.SimpleContent is not null)
            parameters.Add($"{sp.SimpleContentType} Value");
        foreach (var c in sp.Children)
        {
            string typeText = c.Shape switch
            {
                ChildShape.BoundedRepeating => $"IReadOnlyList<{c.CSharpType}>",
                ChildShape.OptionalSingle   => c.CSharpType + "?",
                _                           => c.CSharpType,
            };
            parameters.Add($"{typeText} {c.FieldName}");
        }

        if (parameters.Count == 0)
        {
            _sb.Append("public ").Append(keyword).Append(" record ").Append(sp.CSharpRecordName)
               .Append("()").Append(baseClause).AppendLine(";");
            _sb.AppendLine();
            return;
        }

        _sb.Append("public ").Append(keyword).Append(" record ").Append(sp.CSharpRecordName).AppendLine("(");
        for (int i = 0; i < parameters.Count; i++)
        {
            _sb.Append("    ").Append(parameters[i]);
            _sb.AppendLine(i + 1 < parameters.Count ? "," : "");
        }
        _sb.Append(")").Append(baseClause).AppendLine(";");
        _sb.AppendLine();
    }

    // -----------------------------------------------------------------------
    //  Codec
    // -----------------------------------------------------------------------

    private void EmitCodec()
    {
        _sb.AppendLine("public static class SupportedAppProtocolCodec");
        _sb.AppendLine("{");
        _sb.AppendLine("    public const byte ExiHeader = 0x80;");
        _sb.AppendLine();

        var globals = _plan.GlobalElements
                           .OrderBy(g => g.XsdName, StringComparer.Ordinal)
                           .ToList();
        // Non-strict document grammar: reserve one extra production slot.
        int docBits = BitsForChoices(globals.Count + 1);

        // Public encode entry points (one extension method per global element).
        for (int idx = 0; idx < globals.Count; idx++)
            EmitEncodeEntryPoint(globals[idx], idx, docBits);

        // DecodeAny dispatcher.
        EmitDecodeDispatcher(globals, docBits);

        // Per-complex-type encode/decode methods, deduplicated by record name. Abstract types
        // (substitution heads, extension bases) are never encoded/decoded directly — only their
        // concrete members are — so emitting their codec methods would just be dead, uncompilable
        // code (a `new AbstractType(...)`). Skip them.
        var seenComplex = new HashSet<string>(StringComparer.Ordinal);
        foreach (var sp in _plan.ComplexTypes.Values
                                  .OrderBy(s => s.CSharpRecordName, StringComparer.Ordinal))
        {
            if (sp.IsAbstract) continue;
            if (!seenComplex.Add(sp.CSharpRecordName)) continue;
            EmitEncodeMethod(sp);
            EmitDecodeMethod(sp);
        }

        _sb.AppendLine("}");
    }

    private void EmitEncodeEntryPoint(GlobalElementPlan g, int idx, int docBits)
    {
        _sb.Append("    public static bool TryEncode(this ")
           .Append(g.CSharpTypeName)
           .AppendLine(" msg, Span<byte> dest, out int bytesWritten)");
        _sb.AppendLine("    {");
        _sb.AppendLine("        bytesWritten = 0;");
        _sb.AppendLine("        if (dest.Length < 1) return false;");
        _sb.AppendLine("        dest[0] = ExiHeader;");
        _sb.AppendLine("        var w = new BitWriter(dest[1..]);");
        if (docBits > 0)
            _sb.Append("        w.WriteBits(").Append(idx).Append(", ").Append(docBits).AppendLine(");   // document element selector");
        _sb.Append("        Encode_").Append(g.Body.CSharpRecordName).AppendLine("(ref w, msg);");
        _sb.AppendLine("        w.AlignToByte();");
        _sb.AppendLine("        bytesWritten = 1 + w.BytesWritten;");
        _sb.AppendLine("        return true;");
        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    private void EmitDecodeDispatcher(List<GlobalElementPlan> globals, int docBits)
    {
        _sb.AppendLine("    public static object DecodeAny(ReadOnlySpan<byte> src, out int bytesConsumed)");
        _sb.AppendLine("    {");
        _sb.AppendLine("        if (src.Length < 1 || src[0] != ExiHeader)");
        _sb.AppendLine("            throw new InvalidDataException(\"Invalid EXI header.\");");
        _sb.AppendLine("        var r = new BitReader(src[1..]);");

        if (docBits > 0)
        {
            _sb.Append("        uint sel = r.ReadBits(").Append(docBits).AppendLine(");");
            _sb.AppendLine("        object result = sel switch");
            _sb.AppendLine("        {");
            for (int idx = 0; idx < globals.Count; idx++)
            {
                _sb.Append("            ").Append(idx).Append("u => Decode_")
                   .Append(globals[idx].Body.CSharpRecordName).AppendLine("(ref r),");
            }
            _sb.AppendLine("            _ => throw new InvalidDataException($\"Unknown document index {sel}.\"),");
            _sb.AppendLine("        };");
        }
        else
        {
            _sb.Append("        object result = Decode_")
               .Append(globals[0].Body.CSharpRecordName).AppendLine("(ref r);");
        }

        _sb.AppendLine("        bytesConsumed = 1 + r.BytesConsumed;");
        _sb.AppendLine("        return result;");
        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    // -----------------------------------------------------------------------
    //  Encode_<RecordName>
    // -----------------------------------------------------------------------

    private void EmitEncodeMethod(SequencePlan sp)
    {
        _sb.Append("    private static void Encode_").Append(sp.CSharpRecordName)
           .Append("(ref BitWriter w, ").Append(sp.CSharpRecordName).AppendLine(" msg)");
        _sb.AppendLine("    {");

        if (IsBoundedRepeating(sp, out var rep))
        {
            _sb.Append("        var list = msg.").Append(rep.FieldName).AppendLine(";");
            _sb.Append("        if (list.Count is < ").Append(Math.Max(1, sp.ListMin))
               .Append(" or > ").Append(sp.ListMax)
               .AppendLine(") throw new ArgumentOutOfRangeException(nameof(msg));");
            _sb.AppendLine("        for (int i = 0; i < list.Count; i++)");
            _sb.AppendLine("        {");
            _sb.AppendLine("            w.WriteBits(0, i == 0 ? 1 : 2);   // SE(item): 1-bit first, 2-bit loop");
            EmitEncodeContent(rep, "list[i]", "            ");
            _sb.AppendLine("        }");
            _sb.AppendLine("        w.WriteBits(1, 2);   // list terminator / element EE");
        }
        else if (sp.SimpleContent is not null)
        {
            EmitRequiredAttributePrefix(sp);   // no-op when there are no attributes
            var valueChild = new ChildPlan("Value", sp.SimpleContentType!, false,
                                           ChildShape.RequiredSingle, sp.SimpleContent!);
            _sb.AppendLine("        w.WriteBits(0, 1);   // CONTENT event");
            EmitWriteValue(valueChild, "msg.Value", "        ");
            _sb.AppendLine("        w.WriteBits(0, 1);   // element EE");
        }
        else if (sp.Attributes is { Count: 1 } && sp.Attributes[0].Required)
        {
            EmitRequiredAttributePrefix(sp);
            EmitEncodeContentBody(sp);
        }
        else if (sp.Attributes is not null)
        {
            // Optional attribute(s): the AT event is the first production of the content's initial
            // grammar state — i.e. the attribute is simply the leading optional of the content run
            // (cbexigen model, verified against AuthorizationReqType grammar 222/223 and
            // CertificateChainType). Prepend it and reuse the general optional-run machine.
            var children = WithOptionalAttributes(sp);
            bool terminated = EmitEncodeSequenceChildren(children, "        ");
            if (!terminated)
                _sb.AppendLine("        w.WriteBits(0, 1);   // element EE");
        }
        else
        {
            EmitEncodeContentBody(sp);
        }

        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    /// <summary>
    /// Prepends a type's optional attributes to its content as leading optional "children" whose
    /// value is a bare AT string. This unifies the optional-attribute grammar with the general
    /// optional-run machine. Attributes are already sorted lexicographically by the grammar builder.
    /// </summary>
    private static IReadOnlyList<ChildPlan> WithOptionalAttributes(SequencePlan sp)
    {
        var list = new List<ChildPlan>();
        foreach (var a in sp.Attributes!)
        {
            if (a.Required)
                throw new NotSupportedException(
                    $"{sp.CSharpRecordName}: mixing required and optional attributes is not supported yet.");
            if (a.Value is not ValueEncoding.StringValue)
                throw new NotSupportedException(
                    $"{sp.CSharpRecordName}: only string-typed optional attributes are supported yet.");
            list.Add(new ChildPlan(a.FieldName, a.CSharpType, IsCSharpNullable: false,
                                   ChildShape.OptionalSingle, new ValueEncoding.AttributeValue()));
        }
        if (sp.IsChoice)
            throw new NotSupportedException(
                $"{sp.CSharpRecordName}: optional attributes with xs:choice content are not supported yet.");
        list.AddRange(sp.Children);
        return list;
    }

    /// <summary>A required attribute is always present: a 1-bit AT event, then its value.</summary>
    private void EmitRequiredAttributePrefix(SequencePlan sp)
    {
        if (sp.Attributes is not { Count: 1 } || !sp.Attributes[0].Required) return;
        var attr = sp.Attributes[0];
        _sb.AppendLine("        w.WriteBits(0, 1);   // AT(required attribute)");
        _sb.Append("        ExiPrimitives.WriteStringValue(ref w, msg.").Append(attr.FieldName).AppendLine("!);");
    }

    /// <summary>Emit a complex type's content (an xs:choice or an xs:sequence) plus its element EE.</summary>
    private void EmitEncodeContentBody(SequencePlan sp)
    {
        if (sp.IsChoice)
        {
            EmitEncodeChoice(sp);
            _sb.AppendLine("        w.WriteBits(0, 1);   // element EE");
            return;
        }

        bool terminated = EmitEncodeSequenceChildren(sp.Children, "        ");
        if (!terminated)
            _sb.AppendLine("        w.WriteBits(0, 1);   // element EE");
    }

    /// <summary>
    /// Walks a sequence's particles left to right, emitting each segment: a required element
    /// (1-bit SE + content or a substitution machine), a bounded-repeating list (its own EE),
    /// or a run of consecutive optional elements (a flat grammar-state machine, see
    /// <see cref="EmitEncodeOptionalRun"/>). Returns whether the element's END event has already
    /// been written (a list terminator or an EE-terminated optional run doubles as it).
    /// </summary>
    private bool EmitEncodeSequenceChildren(IReadOnlyList<ChildPlan> children, string indent)
    {
        bool terminated = false;
        int i = 0;
        while (i < children.Count)
        {
            var c = children[i];
            switch (c.Shape)
            {
                case ChildShape.BoundedRepeating when c.ListMin > 0:
                    EmitEncodeRepeatingChild(c, indent);   // required list: 1-bit first / 2-bit loop
                    terminated = true;
                    i++;
                    break;

                case ChildShape.RequiredSingle:
                    if (c.Value is ValueEncoding.SubstitutionChoice sc)
                        EmitEncodeSubstitution(c, sc);
                    else
                    {
                        _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // SE");
                        EmitEncodeContent(c, "msg." + c.FieldName, indent);
                    }
                    terminated = false;
                    i++;
                    break;

                default: // OptionalSingle (or an optional bounded-repeating list) — the head of a run
                    int j = RunEnd(children, i);
                    bool endsElement = j == children.Count;
                    EmitEncodeOptionalRun(children, i, j, indent);
                    terminated = endsElement;
                    i = endsElement ? j : j + 1;
                    break;
            }
        }
        return terminated;
    }

    /// <summary>
    /// Emits the flat EXI grammar-state machine for a run of optional particles
    /// <c>children[s..e)</c> terminated by the element EE (when the run ends the sequence) or the
    /// following required particle <c>children[e]</c>. Each particle contributes one grammar
    /// production, except a substitution reference, which flattens into one production per member
    /// (and the abstract head); the event-code width at each state is
    /// <c>ceil(log2(totalProductions + 1))</c> — cbexigen's non-strict grammar, verified against
    /// MessageHeaderType, CurrentDemandResType, PowerDeliveryReqType and ChargeParameterDiscoveryResType.
    /// State <c>k</c> covers optional particles from cursor <c>s+k</c> plus the terminator; choosing
    /// a production advances the cursor past its particle. The terminator's content is emitted here;
    /// the caller continues after <c>children[e]</c>.
    /// </summary>
    private void EmitEncodeOptionalRun(IReadOnlyList<ChildPlan> children, int s, int e, string indent)
    {
        int m = e - s;                       // number of optional particles in the run
        bool endsElement = e == children.Count;
        ChildPlan? term = endsElement ? null : children[e];
        if (term is not null && term.Shape != ChildShape.RequiredSingle)
            throw new NotSupportedException(
                $"optional run before '{term.FieldName}': the terminator must be the element EE or a required particle.");
        // A bounded-repeating member is only supported as the last member of an EE-terminated run
        // (its loop consumes the element EE).
        for (int p = s; p < e; p++)
            if (children[p].Shape == ChildShape.BoundedRepeating && (p != e - 1 || !endsElement))
                throw new NotSupportedException(
                    $"repeating element '{children[p].FieldName}' in an optional run must be its last member and end the sequence.");

        int id = _runCounter++;
        string st = "_ost" + id, done = "_odone" + id;
        string inner = indent + "    ";
        string body = inner + "    ";
        string br   = body + "    ";

        _sb.Append(indent).Append("int ").Append(st).AppendLine(" = 0;");
        _sb.Append(indent).Append("bool ").Append(done).AppendLine(" = false;");
        _sb.Append(indent).Append("while (!").Append(done).AppendLine(")");
        _sb.Append(indent).AppendLine("{");
        _sb.Append(inner).Append("switch (").Append(st).AppendLine(")");
        _sb.Append(inner).AppendLine("{");

        for (int k = 0; k <= m; k++)   // state k: cursor at optional particle s+k (k==m: terminator only)
        {
            int totalProd = endsElement ? 1 : ProductionCount(term!);
            for (int i = k; i < m; i++) totalProd += ProductionCount(children[s + i]);
            int width = BitsForChoices(totalProd + 1);

            _sb.Append(body).Append("case ").Append(k).AppendLine(":");
            _sb.Append(body).AppendLine("{");
            int code = 0;
            bool first = true;

            for (int i = k; i < m; i++)
            {
                // A repeating member enters its own loop and ends the element; others advance the cursor.
                string after = children[s + i].Shape == ChildShape.BoundedRepeating
                    ? done + " = true;"
                    : st + " = " + (i + 1) + ";";
                code = EmitEncodeRunParticle(children[s + i], code, width, ref first, br, after);
            }

            // Terminator productions occupy the highest event codes.
            if (endsElement)
                EmitEncodeRunTail(first, br, "w.WriteBits(" + code + ", " + width + ");   // element EE", done);
            else if (term!.Value is ValueEncoding.SubstitutionChoice)
            {
                code = EmitEncodeRunParticle(term, code, width, ref first, br, done + " = true;");
                _sb.Append(br).Append("else throw new ArgumentException(\"no value set for ")
                   .Append(term.FieldName).AppendLine("\");");
            }
            else
                EmitEncodeRunTail(first, br, "w.WriteBits(" + code + ", " + width + ");   // SE(" + term.FieldName + ")",
                                  done, term);
            _sb.Append(body).AppendLine("    break;");
            _sb.Append(body).AppendLine("}");
        }

        _sb.Append(inner).AppendLine("}");
        _sb.Append(indent).AppendLine("}");
    }

    /// <summary>Emits the presence/type-dispatch branch(es) for one run particle: an optional
    /// element (one production), or a substitution reference (one production per concrete member,
    /// with the abstract head reserving a code slot but no branch). Returns the next event code.</summary>
    private int EmitEncodeRunParticle(ChildPlan p, int code, int width, ref bool first, string indent, string after)
    {
        if (p.Shape == ChildShape.BoundedRepeating)
        {
            // First item takes this state's event code; further items and the terminating EE use the
            // 2-bit loop code {item = 0, EE = 1} (cbexigen model).
            string list = "msg." + p.FieldName;
            _sb.Append(indent).Append(first ? "if" : "else if").Append(" (").Append(list).AppendLine(".Count > 0)");
            _sb.Append(indent).AppendLine("{");
            _sb.Append(indent).Append("    if (").Append(list).Append(".Count > ").Append(p.ListMax)
               .AppendLine(") throw new ArgumentOutOfRangeException(nameof(msg));");
            _sb.Append(indent).Append("    w.WriteBits(").Append(code).Append(", ").Append(width)
               .Append(");   // ").AppendLine(p.FieldName);
            EmitEncodeContent(p, list + "[0]", indent + "    ");
            _sb.Append(indent).Append("    for (int ci = 1; ci < ").Append(list).AppendLine(".Count; ci++)");
            _sb.Append(indent).AppendLine("    {");
            _sb.Append(indent).Append("        w.WriteBits(0, 2);   // ").AppendLine(p.FieldName);
            EmitEncodeContent(p, list + "[ci]", indent + "        ");
            _sb.Append(indent).AppendLine("    }");
            _sb.Append(indent).AppendLine("    w.WriteBits(1, 2);   // element EE (list end)");
            _sb.Append(indent).Append("    ").AppendLine(after);
            _sb.Append(indent).AppendLine("}");
            first = false;
            return code + 1;
        }

        if (p.Value is ValueEncoding.SubstitutionChoice sc)
        {
            foreach (var mbr in sc.Members)
            {
                if (mbr.IsAbstractHead) { code++; continue; }   // abstract — reserve the slot, no runtime branch
                string v = "v" + code;   // unique per branch (pattern variables share the case scope)
                _sb.Append(indent).Append(first ? "if" : "else if")
                   .Append(" (msg.").Append(p.FieldName).Append(" is ").Append(mbr.CSharpTypeName)
                   .Append(' ').Append(v).AppendLine(")");
                _sb.Append(indent).AppendLine("{");
                _sb.Append(indent).Append("    w.WriteBits(").Append(code).Append(", ").Append(width)
                   .Append(");   // ").AppendLine(mbr.ElementName);
                _sb.Append(indent).Append("    Encode_").Append(mbr.CSharpTypeName).Append("(ref w, ").Append(v).AppendLine(");");
                _sb.Append(indent).Append("    ").AppendLine(after);
                _sb.Append(indent).AppendLine("}");
                first = false; code++;
            }
            return code;
        }

        string presence = p.IsCSharpNullable ? $"msg.{p.FieldName}.HasValue" : $"msg.{p.FieldName} is not null";
        string accessor = p.IsCSharpNullable ? $"msg.{p.FieldName}!.Value" : $"msg.{p.FieldName}!";
        _sb.Append(indent).Append(first ? "if" : "else if").Append(" (").Append(presence).AppendLine(")");
        _sb.Append(indent).AppendLine("{");
        _sb.Append(indent).Append("    w.WriteBits(").Append(code).Append(", ").Append(width)
           .Append(");   // ").AppendLine(p.FieldName);
        EmitEncodeContent(p, accessor, indent + "    ");
        _sb.Append(indent).Append("    ").AppendLine(after);
        _sb.Append(indent).AppendLine("}");
        first = false;
        return code + 1;
    }

    /// <summary>Emits the terminator (element EE, or a required simple/complex element) as either a
    /// standalone block (when no optional branch preceded it) or the trailing <c>else</c>.</summary>
    private void EmitEncodeRunTail(bool first, string indent, string writeBits, string done, ChildPlan? content = null)
    {
        if (!first) _sb.Append(indent).AppendLine("else");
        _sb.Append(indent).AppendLine("{");
        _sb.Append(indent).Append("    ").Append(writeBits).AppendLine();
        if (content is not null)
            EmitEncodeContent(content, "msg." + content.FieldName, indent + "    ");
        _sb.Append(indent).Append("    ").Append(done).AppendLine(" = true;");
        _sb.Append(indent).AppendLine("}");
    }

    private static int ProductionCount(ChildPlan c) =>
        c.Value is ValueEncoding.SubstitutionChoice sc ? sc.Members.Count : 1;

    /// <summary>
    /// The exclusive end of the optional run starting at <paramref name="i"/>: consecutive
    /// <see cref="ChildShape.OptionalSingle"/> particles, plus one trailing optional
    /// (<c>minOccurs=0</c>) bounded-repeating list — its first item is a production of the run's
    /// grammar state and further items loop (cbexigen model, verified against SalesTariffEntryType).
    /// </summary>
    private static int RunEnd(IReadOnlyList<ChildPlan> children, int i)
    {
        int j = i;
        while (j < children.Count && children[j].Shape == ChildShape.OptionalSingle) j++;
        if (j < children.Count && children[j].Shape == ChildShape.BoundedRepeating && children[j].ListMin == 0) j++;
        return j;
    }

    /// <summary>
    /// xs:choice: exactly one alternative is set. An n-bit event code (declaration order)
    /// selects it, followed by its content (no surrounding SE — the code is the selector).
    /// </summary>
    private void EmitEncodeChoice(SequencePlan sp)
    {
        int width = BitsForChoices(sp.Children.Count + 1);
        for (int i = 0; i < sp.Children.Count; i++)
        {
            var c = sp.Children[i];
            string accessor = c.IsCSharpNullable ? $"msg.{c.FieldName}!.Value" : $"msg.{c.FieldName}!";
            _sb.Append("        ").Append(i == 0 ? "if" : "else if")
               .Append(" (msg.").Append(c.FieldName).AppendLine(" is not null)");
            _sb.AppendLine("        {");
            _sb.Append("            w.WriteBits(").Append(i).Append(", ").Append(width)
               .Append(");   // ").AppendLine(c.FieldName);
            EmitEncodeContent(c, accessor, "            ");
            _sb.AppendLine("        }");
        }
        _sb.Append("        else throw new ArgumentException(\"no choice alternative set for ")
           .Append(sp.CSharpRecordName).AppendLine("\");");
    }

    /// <summary>
    /// Emits the content of a child element after its SE event has been written:
    /// for a complex child the nested encode call (which contains its own EE);
    /// for a simple child the value-start event, the value, and the child EE.
    /// </summary>
    private void EmitEncodeContent(ChildPlan c, string accessor, string indent)
    {
        if (c.Value is ValueEncoding.AttributeValue)
        {
            // AT value: a bare string, no value-start / child-EE (the run's event code was the AT event).
            _sb.Append(indent).Append("ExiPrimitives.WriteStringValue(ref w, ").Append(accessor).AppendLine(");");
        }
        else if (c.Value is ValueEncoding.OpaqueElement oe)
        {
            // Reached only if a present (signed) instance is supplied — not modelled in Phase 2.
            _sb.Append(indent).Append("throw new NotSupportedException(\"Encoding a present ")
               .Append(oe.TypeName).AppendLine(" (XMLDSig) is deferred to Phase 3.\");");
        }
        else if (c.Value is ValueEncoding.ComplexRef cr)
        {
            _sb.Append(indent).Append("Encode_").Append(cr.TypeName)
               .Append("(ref w, ").Append(accessor).AppendLine(");");
        }
        else
        {
            _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // value-start");
            EmitWriteValue(c, accessor, indent);
            _sb.Append(indent).AppendLine("w.WriteBits(0, 1);   // child EE");
        }
    }

    /// <summary>
    /// Substitution-group choice: an n-bit event code selects the concrete member type, then
    /// its content is encoded directly (no surrounding SE/EE — the event code IS the selector).
    /// Dispatch is by runtime type; the abstract head has a production slot but no case.
    /// </summary>
    private void EmitEncodeSubstitution(ChildPlan c, ValueEncoding.SubstitutionChoice sc)
    {
        _sb.Append("        switch (msg.").Append(c.FieldName).AppendLine(")");
        _sb.AppendLine("        {");
        for (int i = 0; i < sc.Members.Count; i++)
        {
            var m = sc.Members[i];
            if (m.IsAbstractHead) continue; // abstract — never a runtime instance
            _sb.Append("            case ").Append(m.CSharpTypeName).Append(" v:");
            _sb.AppendLine();
            _sb.Append("                w.WriteBits(").Append(i).Append(", ").Append(sc.BitWidth)
               .Append(");   // ").Append(m.ElementName).AppendLine();
            _sb.Append("                Encode_").Append(m.CSharpTypeName).AppendLine("(ref w, v);");
            _sb.AppendLine("                break;");
        }
        _sb.Append("            default: throw new ArgumentException(\"Unsupported substitution member for ")
           .Append(c.FieldName).AppendLine("\");");
        _sb.AppendLine("        }");
    }

    // -----------------------------------------------------------------------
    //  Attributes (AT events): a single optional attribute preceding the content.
    //  The initial grammar state chooses between AT(attr) and SE(first content); when the
    //  attribute is absent the same n-bit code doubles as that first SE (cbexigen model,
    //  verified against CertificateChainType). Attribute values carry no value-start bit.
    // -----------------------------------------------------------------------

    /// <summary>
    /// A repeating element occurring as the last child of a sequence: the first item is
    /// preceded by a 1-bit SE, each further item by a 2-bit loop code, and a 2-bit code
    /// terminates the list (which also serves as the element EE).
    /// </summary>
    private void EmitEncodeRepeatingChild(ChildPlan c, string indent)
    {
        string list = c.FieldName + "_list";
        _sb.Append(indent).Append("var ").Append(list).Append(" = msg.").Append(c.FieldName).AppendLine(";");
        _sb.Append(indent).Append("if (").Append(list).Append(".Count is < ").Append(Math.Max(1, c.ListMin))
           .Append(" or > ").Append(c.ListMax).AppendLine(") throw new ArgumentOutOfRangeException(nameof(msg));");
        _sb.Append(indent).Append("for (int i = 0; i < ").Append(list).AppendLine(".Count; i++)");
        _sb.Append(indent).AppendLine("{");
        _sb.Append(indent).AppendLine("    w.WriteBits(0, i == 0 ? 1 : 2);   // SE(item): 1-bit first, 2-bit loop");
        EmitEncodeContent(c, list + "[i]", indent + "    ");
        _sb.Append(indent).AppendLine("}");
        _sb.Append(indent).AppendLine("w.WriteBits(1, 2);   // list terminator / element EE");
    }

    private void EmitDecodeRepeatingChild(ChildPlan c, string local, string indent)
    {
        _sb.Append(indent).Append("var ").Append(local).Append(" = new List<").Append(c.CSharpType).AppendLine(">();");
        _sb.Append(indent).AppendLine("r.ReadBits(1);   // SE(item) first");
        EmitDecodeContent(c, local + "_first", indent, declare: true);
        _sb.Append(indent).Append(local).Append(".Add(").Append(local).AppendLine("_first);");
        _sb.Append(indent).AppendLine("while (true)");
        _sb.Append(indent).AppendLine("{");
        _sb.Append(indent).AppendLine("    uint ec = r.ReadBits(2);");
        _sb.Append(indent).AppendLine("    if (ec == 1) break;   // element EE");
        _sb.Append(indent).Append("    if (ec != 0 || ").Append(local).Append(".Count >= ").Append(c.ListMax)
           .AppendLine(") throw new InvalidDataException(\"invalid repeating-element event code\");");
        EmitDecodeContent(c, local + "_next", indent + "    ", declare: true);
        _sb.Append(indent).Append("    ").Append(local).Append(".Add(").Append(local).AppendLine("_next);");
        _sb.Append(indent).AppendLine("}");
    }

    private void EmitWriteValue(ChildPlan c, string accessor, string indent)
    {
        switch (c.Value)
        {
            case ValueEncoding.UnsignedInt:
                _sb.Append(indent).Append("ExiPrimitives.WriteUnsignedInteger(ref w, (ulong)")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.SignedInt:
                _sb.Append(indent).Append("ExiPrimitives.WriteSignedInteger(ref w, (long)")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.Binary:
                _sb.Append(indent).Append("ExiPrimitives.WriteBinary(ref w, ")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.StringValue:
                _sb.Append(indent).Append("ExiPrimitives.WriteStringValue(ref w, ")
                   .Append(accessor).AppendLine(");");
                break;
            case ValueEncoding.NBitUnsigned nb when nb.Bias != 0:
                _sb.Append(indent).Append("w.WriteBits((uint)((long)")
                   .Append(accessor).Append(" - ").Append(nb.Bias).Append("), ")
                   .Append(nb.BitWidth).AppendLine(");");
                break;
            case ValueEncoding.NBitUnsigned nb:
                _sb.Append(indent).Append("w.WriteBits((uint)").Append(accessor)
                   .Append(", ").Append(nb.BitWidth).AppendLine(");");
                break;
            case ValueEncoding.EnumIndex ei:
                // The C# enum value equals the XSD declaration index == the EXI n-bit index.
                _sb.Append(indent).Append("w.WriteBits((uint)").Append(accessor)
                   .Append(", ").Append(ei.BitWidth).AppendLine(");");
                break;
        }
    }

    // -----------------------------------------------------------------------
    //  Decode_<RecordName>
    // -----------------------------------------------------------------------

    private void EmitDecodeMethod(SequencePlan sp)
    {
        _sb.Append("    private static ").Append(sp.CSharpRecordName)
           .Append(" Decode_").Append(sp.CSharpRecordName).AppendLine("(ref BitReader r)");
        _sb.AppendLine("    {");

        if (IsBoundedRepeating(sp, out var rep))
        {
            _sb.Append("        var list = new List<").Append(rep.CSharpType).AppendLine(">();");
            _sb.AppendLine("        r.ReadBits(1);   // SE(item) first");
            EmitDecodeContent(rep, "first", "        ", declare: true);
            _sb.AppendLine("        list.Add(first);");
            _sb.AppendLine("        while (true)");
            _sb.AppendLine("        {");
            _sb.AppendLine("            uint ec = r.ReadBits(2);");
            _sb.AppendLine("            if (ec == 1) break;   // element EE");
            _sb.Append("            if (ec != 0 || list.Count >= ").Append(sp.ListMax)
               .AppendLine(") throw new InvalidDataException(\"Invalid AppProtocol list event code.\");");
            EmitDecodeContent(rep, "next", "            ", declare: true);
            _sb.AppendLine("            list.Add(next);");
            _sb.AppendLine("        }");
            _sb.Append("        return new ").Append(sp.CSharpRecordName).AppendLine("(list);");
        }
        else if (sp.SimpleContent is not null)
        {
            var locals = new List<string>();
            if (sp.Attributes is { Count: 1 } && sp.Attributes[0].Required)
            {
                var attr = sp.Attributes[0];
                _sb.AppendLine("        r.ReadBits(1);   // AT(required attribute)");
                _sb.Append("        var _").Append(attr.FieldName).AppendLine(" = ExiPrimitives.ReadStringValue(ref r);");
                locals.Add("_" + attr.FieldName);
            }
            _sb.AppendLine("        r.ReadBits(1);   // CONTENT event");
            var valueChild = new ChildPlan("Value", sp.SimpleContentType!, false,
                                           ChildShape.RequiredSingle, sp.SimpleContent!);
            _sb.Append("        var _Value = ");
            AppendReadValueExpr(valueChild);
            _sb.AppendLine(";");
            locals.Add("_Value");
            _sb.AppendLine("        r.ReadBits(1);   // element EE");
            _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
               .Append(string.Join(", ", locals)).AppendLine(");");
        }
        else if (sp.Attributes is { Count: 1 } && sp.Attributes[0].Required)
        {
            var attr = sp.Attributes[0];
            _sb.AppendLine("        r.ReadBits(1);   // AT(required attribute)");
            _sb.Append("        var _").Append(attr.FieldName).AppendLine(" = ExiPrimitives.ReadStringValue(ref r);");
            EmitDecodeContentBody(sp, new List<string> { "_" + attr.FieldName });
        }
        else if (sp.Attributes is not null)
        {
            // Optional attribute(s) unified into the content run (see the encode counterpart).
            var children = WithOptionalAttributes(sp);
            var locals = new List<string>();
            bool terminated = EmitDecodeSequenceChildren(children, "        ", locals);
            if (!terminated)
                _sb.AppendLine("        r.ReadBits(1);   // element EE");
            _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
               .Append(string.Join(", ", locals)).AppendLine(");");
        }
        else
        {
            EmitDecodeContentBody(sp, new List<string>());
        }

        _sb.AppendLine("    }");
        _sb.AppendLine();
    }

    /// <summary>Decode a complex type's content (xs:choice or xs:sequence) and emit the record return.</summary>
    private void EmitDecodeContentBody(SequencePlan sp, List<string> prefixLocals)
    {
        var locals = new List<string>(prefixLocals);

        if (sp.IsChoice)
        {
            int width = BitsForChoices(sp.Children.Count + 1);
            foreach (var c in sp.Children)
            {
                _sb.Append("        ").Append(c.CSharpType).Append("? _").Append(c.FieldName).AppendLine(" = default;");
                locals.Add("_" + c.FieldName);
            }
            _sb.Append("        switch (r.ReadBits(").Append(width).AppendLine("))");
            _sb.AppendLine("        {");
            for (int i = 0; i < sp.Children.Count; i++)
            {
                var c = sp.Children[i];
                _sb.Append("            case ").Append(i).AppendLine("u:");
                EmitDecodeContent(c, "_" + c.FieldName, "                ", declare: false);
                _sb.AppendLine("                break;");
            }
            _sb.AppendLine("            default: throw new InvalidDataException(\"unknown choice event code\");");
            _sb.AppendLine("        }");
            _sb.AppendLine("        r.ReadBits(1);   // element EE");
            _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
               .Append(string.Join(", ", locals)).AppendLine(");");
            return;
        }

        bool terminated = EmitDecodeSequenceChildren(sp.Children, "        ", locals);
        if (!terminated)
            _sb.AppendLine("        r.ReadBits(1);   // element EE");

        _sb.Append("        return new ").Append(sp.CSharpRecordName).Append('(')
           .Append(string.Join(", ", locals)).AppendLine(");");
    }

    /// <summary>
    /// Decode mirror of <see cref="EmitEncodeSequenceChildren"/>: walks the sequence, declaring a
    /// local per particle (in record-constructor order) and reading each segment. Returns whether
    /// the element's END event was already consumed.
    /// </summary>
    private bool EmitDecodeSequenceChildren(IReadOnlyList<ChildPlan> children, string indent, List<string> locals)
    {
        bool terminated = false;
        int i = 0;
        while (i < children.Count)
        {
            var c = children[i];
            string local = "_" + c.FieldName;
            switch (c.Shape)
            {
                case ChildShape.BoundedRepeating when c.ListMin > 0:
                    EmitDecodeRepeatingChild(c, local, indent);   // required list
                    locals.Add(local);
                    terminated = true;
                    i++;
                    break;

                case ChildShape.RequiredSingle:
                    if (c.Value is ValueEncoding.SubstitutionChoice sc)
                        EmitDecodeSubstitution(c, local, sc);
                    else
                    {
                        _sb.Append(indent).AppendLine("r.ReadBits(1);   // SE");
                        EmitDecodeContent(c, local, indent, declare: true);
                    }
                    locals.Add(local);
                    terminated = false;
                    i++;
                    break;

                default: // OptionalSingle (or an optional bounded-repeating list) — head of a run
                    int j = RunEnd(children, i);
                    bool endsElement = j == children.Count;
                    EmitDecodeOptionalRun(children, i, j, indent, locals);
                    terminated = endsElement;
                    i = endsElement ? j : j + 1;
                    break;
            }
        }
        return terminated;
    }

    /// <summary>Decode side of <see cref="EmitEncodeOptionalRun"/>. Declares a local per particle
    /// (in record-constructor order), then reads the flat state machine: at each state it reads the
    /// width-bit event code and dispatches it to the production it selects (an optional element, a
    /// substitution member, the required terminator, or the element EE).</summary>
    private void EmitDecodeOptionalRun(IReadOnlyList<ChildPlan> children, int s, int e, string indent, List<string> locals)
    {
        int m = e - s;
        bool endsElement = e == children.Count;
        ChildPlan? term = endsElement ? null : children[e];
        if (term is not null && term.Shape != ChildShape.RequiredSingle)
            throw new NotSupportedException(
                $"optional run before '{term.FieldName}': the terminator must be the element EE or a required particle.");

        // Declare the locals in record order: each optional (nullable), a repeating member as a
        // list, then the terminator.
        for (int p = s; p < e; p++)
        {
            var o = children[p];
            if (o.Shape == ChildShape.BoundedRepeating)
                _sb.Append(indent).Append("var _").Append(o.FieldName)
                   .Append(" = new List<").Append(o.CSharpType).AppendLine(">();");
            else
                _sb.Append(indent).Append(o.CSharpType).Append("? _").Append(o.FieldName).AppendLine(" = default;");
            locals.Add("_" + o.FieldName);
        }
        if (term is not null)
        {
            _sb.Append(indent).Append(term.CSharpType).Append(" _").Append(term.FieldName).AppendLine(" = default!;");
            locals.Add("_" + term.FieldName);
        }

        int id = _runCounter++;
        string st = "_ist" + id, done = "_idone" + id, code = "_ic" + id;
        string inner = indent + "    ";
        string body = inner + "    ";
        string sw = body + "    ";
        string ca = sw + "    ";

        _sb.Append(indent).Append("int ").Append(st).AppendLine(" = 0;");
        _sb.Append(indent).Append("bool ").Append(done).AppendLine(" = false;");
        _sb.Append(indent).Append("while (!").Append(done).AppendLine(")");
        _sb.Append(indent).AppendLine("{");
        _sb.Append(inner).Append("switch (").Append(st).AppendLine(")");
        _sb.Append(inner).AppendLine("{");

        for (int k = 0; k <= m; k++)
        {
            int totalProd = endsElement ? 1 : ProductionCount(term!);
            for (int i = k; i < m; i++) totalProd += ProductionCount(children[s + i]);
            int width = BitsForChoices(totalProd + 1);

            _sb.Append(body).Append("case ").Append(k).AppendLine(":");
            _sb.Append(body).AppendLine("{");
            _sb.Append(sw).Append("uint ").Append(code).Append(" = r.ReadBits(").Append(width).AppendLine(");");
            _sb.Append(sw).Append("switch (").Append(code).AppendLine(")");
            _sb.Append(sw).AppendLine("{");

            int c = 0;
            for (int i = k; i < m; i++)
            {
                string after = children[s + i].Shape == ChildShape.BoundedRepeating
                    ? done + " = true;"
                    : st + " = " + (i + 1) + ";";
                c = EmitDecodeRunParticle(children[s + i], c, ca, after);
            }

            if (endsElement)
            {
                _sb.Append(ca).Append("case ").Append(c).AppendLine("u:");   // element EE
                _sb.Append(ca).Append("    ").Append(done).AppendLine(" = true; break;");
            }
            else
            {
                c = EmitDecodeRunParticle(term!, c, ca, done + " = true;");
            }

            _sb.Append(ca).AppendLine("default: throw new InvalidDataException(\"invalid optional-run event code\");");
            _sb.Append(sw).AppendLine("}");
            _sb.Append(sw).AppendLine("break;");
            _sb.Append(body).AppendLine("}");
        }

        _sb.Append(inner).AppendLine("}");
        _sb.Append(indent).AppendLine("}");
    }

    /// <summary>Emits the decode <c>switch</c> case(s) for one run particle: an optional element
    /// (one case reading its content), or a substitution reference (one case per member, decoding
    /// into the base-typed local; the abstract head's slot throws). Returns the next event code.</summary>
    private int EmitDecodeRunParticle(ChildPlan p, int code, string indent, string after)
    {
        string local = "_" + p.FieldName;
        if (p.Shape == ChildShape.BoundedRepeating)
        {
            string it0 = "_it" + _tmpCounter++;
            string itn = "_it" + _tmpCounter++;
            _sb.Append(indent).Append("case ").Append(code).AppendLine("u:");
            _sb.Append(indent).AppendLine("{");
            EmitDecodeContent(p, it0, indent + "    ", declare: true);   // first item (event code was its SE)
            _sb.Append(indent).Append("    ").Append(local).Append(".Add(").Append(it0).AppendLine(");");
            _sb.Append(indent).AppendLine("    while (true)");
            _sb.Append(indent).AppendLine("    {");
            _sb.Append(indent).AppendLine("        uint lc = r.ReadBits(2);");
            _sb.Append(indent).AppendLine("        if (lc == 1) break;   // element EE (list end)");
            _sb.Append(indent).Append("        if (lc != 0 || ").Append(local).Append(".Count >= ").Append(p.ListMax)
               .AppendLine(") throw new InvalidDataException(\"invalid repeating-element event code\");");
            EmitDecodeContent(p, itn, indent + "        ", declare: true);
            _sb.Append(indent).Append("        ").Append(local).Append(".Add(").Append(itn).AppendLine(");");
            _sb.Append(indent).AppendLine("    }");
            _sb.Append(indent).Append("    ").AppendLine(after);
            _sb.Append(indent).AppendLine("    break;");
            _sb.Append(indent).AppendLine("}");
            return code + 1;
        }
        if (p.Value is ValueEncoding.SubstitutionChoice sc)
        {
            foreach (var mbr in sc.Members)
            {
                _sb.Append(indent).Append("case ").Append(code).AppendLine("u:");
                if (mbr.IsAbstractHead)
                    _sb.Append(indent).AppendLine("    throw new InvalidDataException(\"abstract substitution head cannot be decoded\");");
                else
                {
                    _sb.Append(indent).Append("    ").Append(local).Append(" = Decode_")
                       .Append(mbr.CSharpTypeName).AppendLine("(ref r);");
                    _sb.Append(indent).Append("    ").AppendLine(after);
                    _sb.Append(indent).AppendLine("    break;");
                }
                code++;
            }
            return code;
        }

        _sb.Append(indent).Append("case ").Append(code).AppendLine("u:");
        EmitDecodeContent(p, local, indent + "    ", declare: false);
        _sb.Append(indent).Append("    ").AppendLine(after);
        _sb.Append(indent).AppendLine("    break;");
        return code + 1;
    }

    /// <summary>
    /// Reads the content of a child element after its SE event has been consumed.
    /// Complex child: nested decode (consumes its own EE). Simple child: value-start,
    /// value, child EE. When <paramref name="declare"/> is false the value is assigned
    /// to an existing local (used for optional elements).
    /// </summary>
    private void EmitDecodeContent(ChildPlan c, string local, string indent, bool declare)
    {
        if (c.Value is ValueEncoding.AttributeValue)
        {
            // AT value: a bare string, no value-start / child-EE.
            _sb.Append(indent).Append(declare ? "var " : "").Append(local)
               .AppendLine(" = ExiPrimitives.ReadStringValue(ref r);");
            return;
        }
        if (c.Value is ValueEncoding.OpaqueElement oe)
        {
            // Reached only if the wire carries a present (signed) instance — not modelled in Phase 2.
            if (declare)
                _sb.Append(indent).Append(oe.TypeName).Append(' ').Append(local).AppendLine(" = default!;");
            _sb.Append(indent).Append("throw new NotSupportedException(\"Decoding a present ")
               .Append(oe.TypeName).AppendLine(" (XMLDSig) is deferred to Phase 3.\");");
            return;
        }
        if (c.Value is ValueEncoding.ComplexRef cr)
        {
            _sb.Append(indent);
            _sb.Append(declare ? "var " : "").Append(local).Append(" = Decode_")
               .Append(cr.TypeName).AppendLine("(ref r);");
            return;
        }

        _sb.Append(indent).AppendLine("r.ReadBits(1);   // value-start");
        _sb.Append(indent);
        _sb.Append(declare ? "var " : "").Append(local).Append(" = ");
        AppendReadValueExpr(c);
        _sb.AppendLine(";");
        _sb.Append(indent).AppendLine("r.ReadBits(1);   // child EE");
    }

    /// <summary>Decode side of <see cref="EmitEncodeSubstitution"/>: read the event code and
    /// dispatch to the selected member's decoder.</summary>
    private void EmitDecodeSubstitution(ChildPlan c, string local, ValueEncoding.SubstitutionChoice sc)
    {
        _sb.Append("        ").Append(c.CSharpType).Append(' ').Append(local).AppendLine(";");
        _sb.Append("        switch (r.ReadBits(").Append(sc.BitWidth).AppendLine("))");
        _sb.AppendLine("        {");
        for (int i = 0; i < sc.Members.Count; i++)
        {
            var m = sc.Members[i];
            if (m.IsAbstractHead)
                _sb.Append("            case ").Append(i)
                   .AppendLine("u: throw new InvalidDataException(\"abstract substitution head cannot be decoded\");");
            else
                _sb.Append("            case ").Append(i).Append("u: ").Append(local)
                   .Append(" = Decode_").Append(m.CSharpTypeName).AppendLine("(ref r); break;");
        }
        _sb.AppendLine("            default: throw new InvalidDataException(\"unknown substitution index\");");
        _sb.AppendLine("        }");
    }

    private void AppendReadValueExpr(ChildPlan c)
    {
        switch (c.Value)
        {
            case ValueEncoding.UnsignedInt:
                _sb.Append('(').Append(c.CSharpType)
                   .Append(")ExiPrimitives.ReadUnsignedInteger(ref r)");
                break;
            case ValueEncoding.SignedInt:
                _sb.Append('(').Append(c.CSharpType)
                   .Append(")ExiPrimitives.ReadSignedInteger(ref r)");
                break;
            case ValueEncoding.Binary:
                _sb.Append("ExiPrimitives.ReadBinary(ref r)");
                break;
            case ValueEncoding.StringValue:
                _sb.Append("ExiPrimitives.ReadStringValue(ref r)");
                break;
            case ValueEncoding.NBitUnsigned nb when nb.Bias != 0:
                _sb.Append('(').Append(c.CSharpType).Append(")((long)r.ReadBits(")
                   .Append(nb.BitWidth).Append(") + ").Append(nb.Bias).Append(')');
                break;
            case ValueEncoding.NBitUnsigned nb:
                _sb.Append('(').Append(c.CSharpType).Append(")r.ReadBits(").Append(nb.BitWidth).Append(')');
                break;
            case ValueEncoding.EnumIndex ei:
                _sb.Append('(').Append(ei.EnumName).Append(")r.ReadBits(").Append(ei.BitWidth).Append(')');
                break;
        }
    }

    // -----------------------------------------------------------------------
    //  Helpers
    // -----------------------------------------------------------------------

    private static bool IsBoundedRepeating(SequencePlan sp, out ChildPlan rep)
    {
        if (sp.Children.Count == 1 && sp.Children[0].Shape == ChildShape.BoundedRepeating)
        {
            rep = sp.Children[0];
            return true;
        }
        rep = default!;
        return false;
    }

    private static int BitsForChoices(int n)
    {
        if (n <= 1) return 0;
        int bits = 0;
        int v = n - 1;
        while (v > 0) { bits++; v >>= 1; }
        return bits;
    }
}
