using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Vanaheimr.V2G.Exi.SourceGenerator.Grammar;

namespace Vanaheimr.V2G.Exi.SourceGenerator.Emit
{
    /// <summary>
    /// Kotlin back end — the second target through <see cref="ICodecEmitter"/>, and the proof
    /// that the front end is genuinely language-neutral.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Scope: deliberately partial.</b> This covers the constructs the AppProtocol schema
    /// exercises — enums, records, required/optional/repeating children, and the
    /// string / unsigned-integer / n-bit / enum-index value encodings. Everything else
    /// (substitution groups, inline choices, attributes, simple content, opaque elements,
    /// fragments) throws <see cref="NotSupportedException"/> rather than emitting something
    /// plausible, following the generator's fail-loud rule: an unhandled construct must break
    /// the build, never produce silently wrong bytes.
    /// </para>
    /// <para>
    /// Bit-level behaviour mirrors <see cref="CodecEmitter"/> exactly — same event codes, same
    /// widths, same order — because both are driven by the same <see cref="SchemaPlan"/>. The
    /// vectors under <c>Vanaheimr.V2G.Exi.Tests/Vectors/</c> are the shared oracle.
    /// </para>
    /// </remarks>
    internal sealed class KotlinCodecEmitter : ICodecEmitter
    {
        public static readonly KotlinCodecEmitter Instance = new();

        public string Language      => "kotlin";
        public string FileExtension => ".kt";

        public string Emit(SchemaPlan plan, string targetNamespace, string codecClassName) =>
            new Writer(plan, targetNamespace, codecClassName).Run();

        private sealed class Writer(SchemaPlan plan, string package, string codecObject)
        {
            private readonly StringBuilder _sb = new();
            private readonly HashSet<string> _emitted = new(StringComparer.Ordinal);
            private readonly HashSet<string> _codecs  = new(StringComparer.Ordinal);
            private int _run;

            public string Run()
            {
                Reject(plan);

                _sb.AppendLine("// <auto-generated/>");
                _sb.AppendLine("// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.");
                _sb.AppendLine();
                _sb.Append("package ").AppendLine(package);
                _sb.AppendLine();
                _sb.AppendLine("import cloud.charging.v2g.exi.BitReader");
                _sb.AppendLine("import cloud.charging.v2g.exi.BitWriter");
                _sb.AppendLine("import cloud.charging.v2g.exi.ExiPrimitives");
                _sb.AppendLine();

                EmitEnums();
                EmitRecords();
                EmitCodec();
                return _sb.ToString();
            }

            /// <summary>Fail loud on anything this back end does not model yet.</summary>
            private static void Reject(SchemaPlan p)
            {
                if (p.Fragments.Count != 0)
                    throw new NotSupportedException("Kotlin back end: EXI fragment codecs (XMLDSig) are not implemented yet.");
                if (p.OpaqueTypes.Count != 0)
                    throw new NotSupportedException("Kotlin back end: opaque (un-modelled) elements are not implemented yet.");

                foreach (var sp in p.ComplexTypes.Values)
                {
                    if (sp.Attributes is { Count: > 0 })
                        throw new NotSupportedException($"Kotlin back end: attributes ('{sp.RecordName}') are not implemented yet.");
                    if (sp.IsChoice)
                        throw new NotSupportedException($"Kotlin back end: xs:choice content ('{sp.RecordName}') is not implemented yet.");
                    if (sp.SimpleContent is not null)
                        throw new NotSupportedException($"Kotlin back end: xs:simpleContent ('{sp.RecordName}') is not implemented yet.");
                    if (sp.IsAbstract || sp.BaseRecordName is not null)
                        throw new NotSupportedException($"Kotlin back end: type extension/abstraction ('{sp.RecordName}') is not implemented yet.");

                    foreach (var c in sp.Children)
                    {
                        if (c.IsWildcardAny)
                            throw new NotSupportedException($"Kotlin back end: xs:any wildcards ('{sp.RecordName}.{c.FieldName}') are not implemented yet.");
                        _ = c.Value switch
                        {
                            ValueEncoding.StringValue or ValueEncoding.UnsignedInt or ValueEncoding.SignedInt
                                or ValueEncoding.Binary or ValueEncoding.NBitUnsigned or ValueEncoding.EnumIndex
                                or ValueEncoding.ComplexRef => true,
                            _ => throw new NotSupportedException(
                                     $"Kotlin back end: value encoding {c.Value.GetType().Name} " +
                                     $"('{sp.RecordName}.{c.FieldName}') is not implemented yet."),
                        };
                    }
                }
            }

            // ---------------------------------------------------------------- naming

            /// <summary>Kotlin properties are camelCase; the plan's field names are PascalCase.</summary>
            private static string Prop(string pascal) =>
                pascal.Length == 0 ? pascal : char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);

            private static string Type(TypeRef t) => t switch
            {
                TypeRef.Primitive p => p.Kind switch
                {
                    PrimitiveKind.Bool   => "Boolean",
                    PrimitiveKind.Int8   => "Byte",
                    PrimitiveKind.Int16  => "Short",
                    PrimitiveKind.Int32  => "Int",
                    PrimitiveKind.Int64  => "Long",
                    PrimitiveKind.UInt8  => "UByte",
                    PrimitiveKind.UInt16 => "UShort",
                    PrimitiveKind.UInt32 => "UInt",
                    PrimitiveKind.UInt64 => "ULong",
                    PrimitiveKind.String => "String",
                    PrimitiveKind.Binary => "ByteArray",
                    _ => throw new NotSupportedException($"Kotlin back end: primitive {p.Kind}."),
                },
                TypeRef.Named n => n.Name,
                _ => throw new NotSupportedException("Kotlin back end: untyped child."),
            };

            /// <summary>Declared type of a child, including Kotlin's nullability / list wrapping.</summary>
            private static string DeclType(ChildPlan c) => c.Shape switch
            {
                ChildShape.BoundedRepeating => $"List<{Type(c.Type)}>",
                ChildShape.OptionalSingle   => Type(c.Type) + "?",
                _                           => Type(c.Type),
            };

            // ---------------------------------------------------------------- types

            private void EmitEnums()
            {
                foreach (var e in plan.Enums)
                {
                    _sb.Append("enum class ").Append(e.Name).AppendLine(" {");
                    for (var i = 0; i < e.Members.Count; i++)
                        _sb.Append("    ").Append(e.Members[i]).AppendLine(i == e.Members.Count - 1 ? "" : ",");
                    _sb.AppendLine("}");
                    _sb.AppendLine();
                }
            }

            private void EmitRecords()
            {
                foreach (var ge in plan.GlobalElements)
                    EmitRecord(ge.Body, ge.TypeName);
                foreach (var sp in plan.ComplexTypes.Values)
                    EmitRecord(sp, sp.RecordName);
            }

            private void EmitRecord(SequencePlan sp, string name)
            {
                if (!_emitted.Add(name)) return;

                // Nested complex types first, so declarations read top-down.
                foreach (var c in sp.Children)
                    if (c.Value is ValueEncoding.ComplexRef cr && plan.ComplexTypes.TryGetValue(cr.TypeName, out var nested))
                        EmitRecord(nested, nested.RecordName);

                _sb.Append("data class ").Append(name).AppendLine("(");
                for (var i = 0; i < sp.Children.Count; i++)
                {
                    var c = sp.Children[i];
                    _sb.Append("    val ").Append(Prop(c.FieldName)).Append(": ").Append(DeclType(c));
                    _sb.AppendLine(i == sp.Children.Count - 1 ? "" : ",");
                }
                _sb.AppendLine(")");
                _sb.AppendLine();
            }

            // ---------------------------------------------------------------- codec

            private void EmitCodec()
            {
                _sb.Append("object ").Append(codecObject).AppendLine(" {");
                _sb.AppendLine();
                _sb.AppendLine("    const val EXI_HEADER: Byte = 0x80.toByte()");
                _sb.AppendLine();
                _sb.AppendLine("    /** Generous upper bound; encode() returns a right-sized copy. */");
                _sb.AppendLine("    private const val MAX_MESSAGE_BYTES = 65536");
                _sb.AppendLine();

                foreach (var ge in plan.GlobalElements)
                {
                    _sb.Append("    fun encode(msg: ").Append(ge.TypeName).AppendLine("): ByteArray {");
                    _sb.AppendLine("        val buf = ByteArray(MAX_MESSAGE_BYTES)");
                    _sb.AppendLine("        buf[0] = EXI_HEADER");
                    _sb.AppendLine("        val w = BitWriter(buf, 1)");
                    _sb.Append("        w.writeBits(").Append(ge.DocumentIndex).Append("u, ")
                       .Append(plan.DocumentSelectorBits).AppendLine(")   // document element selector");
                    _sb.Append("        encode").Append(ge.TypeName).AppendLine("(w, msg)");
                    _sb.AppendLine("        w.alignToByte()");
                    _sb.AppendLine("        return buf.copyOf(1 + w.bytesWritten)");
                    _sb.AppendLine("    }");
                    _sb.AppendLine();
                }

                _sb.AppendLine("    fun decodeAny(src: ByteArray): Any {");
                _sb.AppendLine("        require(src.isNotEmpty() && src[0] == EXI_HEADER) { \"Invalid EXI header.\" }");
                _sb.AppendLine("        val r = BitReader(src, 1)");
                _sb.Append("        return when (val sel = r.readBits(").Append(plan.DocumentSelectorBits).AppendLine(")) {");
                foreach (var ge in plan.GlobalElements)
                    _sb.Append("            ").Append(ge.DocumentIndex).Append("u -> decode")
                       .Append(ge.TypeName).AppendLine("(r)");
                _sb.AppendLine("            else -> throw IllegalArgumentException(\"Unknown document index $sel.\")");
                _sb.AppendLine("        }");
                _sb.AppendLine("    }");
                _sb.AppendLine();

                foreach (var sp in plan.ComplexTypes.Values)
                    EmitSequenceCodec(sp, sp.RecordName);
                foreach (var ge in plan.GlobalElements)
                    EmitSequenceCodec(ge.Body, ge.TypeName);

                _sb.AppendLine("}");
            }

            /// <summary>
            /// A global element's body is also registered in <c>ComplexTypes</c>, so the two
            /// emission loops overlap; emit each codec pair once.
            /// </summary>
            private void EmitSequenceCodec(SequencePlan sp, string name)
            {
                if (!_codecs.Add(name)) return;
                EmitEncode(sp, name);
                EmitDecode(sp, name);
            }

            private void EmitEncode(SequencePlan sp, string name)
            {
                _sb.Append("    private fun encode").Append(name).Append("(w: BitWriter, msg: ")
                   .Append(name).AppendLine(") {");

                var kids = sp.Children;
                for (var i = 0; i < kids.Count;)
                {
                    var c = kids[i];
                    if (c.Shape == ChildShape.BoundedRepeating)
                    {
                        if (kids.Count != 1)
                            throw new NotSupportedException(
                                $"Kotlin back end: a repeating child among siblings ('{name}.{c.FieldName}') is not implemented yet.");
                        EmitEncodeList(c, sp);
                        i++;
                        continue;
                    }
                    if (c.Shape == ChildShape.OptionalSingle)
                    {
                        // The remainder of the sequence must be an optional run — that is the only
                        // shape this back end models.
                        for (var j = i; j < kids.Count; j++)
                            if (kids[j].Shape != ChildShape.OptionalSingle)
                                throw new NotSupportedException(
                                    $"Kotlin back end: '{name}' mixes optional and non-optional children after index {i}.");
                        EmitEncodeOptionalRun(kids, i);
                        i = kids.Count;
                        continue;
                    }

                    _sb.AppendLine("        w.writeBits(0u, 1)   // SE");
                    EmitEncodeValue(c, "msg." + Prop(c.FieldName), "        ");
                    i++;
                    if (i == kids.Count)
                        _sb.AppendLine("        w.writeBits(0u, 1)   // element EE");
                }

                if (kids.Count == 0)
                    _sb.AppendLine("        w.writeBits(0u, 1)   // element EE");

                _sb.AppendLine("    }");
                _sb.AppendLine();
            }

            /// <summary>
            /// A repeating child: first item takes a 1-bit SE, every following item and the
            /// terminator a 2-bit event code (item = 0, EE = 1). Mirrors <c>CodecEmitter</c>.
            /// </summary>
            private void EmitEncodeList(ChildPlan c, SequencePlan sp)
            {
                var (min, max) = ListBounds(c, sp);
                var prop = "msg." + Prop(c.FieldName);
                _sb.Append("        val list = ").AppendLine(prop);
                _sb.Append("        require(list.size in ").Append(min).Append("..")
                   .Append(max).AppendLine(") { \"list size out of schema range\" }");
                _sb.AppendLine("        for (i in list.indices) {");
                _sb.AppendLine("            w.writeBits(0u, if (i == 0) 1 else 2)   // SE(item)");
                EmitEncodeValue(c, "list[i]", "            ", inList: true);
                _sb.AppendLine("        }");
                _sb.AppendLine("        w.writeBits(1u, 2)   // list terminator / element EE");
            }

            /// <summary>
            /// A trailing run of optional children. At each state the event-code width covers the
            /// still-possible productions plus the non-strict phantom, exactly as
            /// <c>CodecEmitter</c> computes it.
            /// </summary>
            private void EmitEncodeOptionalRun(IReadOnlyList<ChildPlan> kids, int start)
            {
                var id = _run++;
                _sb.Append("        var st").Append(id).AppendLine(" = 0");
                _sb.Append("        var done").Append(id).AppendLine(" = false");
                _sb.Append("        while (!done").Append(id).AppendLine(") {");
                _sb.Append("            when (st").Append(id).AppendLine(") {");

                for (var s = start; s <= kids.Count; s++)
                {
                    var remaining = kids.Count - s;          // optionals still available
                    var width     = BitsFor(remaining + 1 + 1); // + EE + phantom
                    _sb.Append("                ").Append(s - start).AppendLine(" -> {");

                    if (s < kids.Count)
                    {
                        var c = kids[s];
                        _sb.Append("                    if (msg.").Append(Prop(c.FieldName)).AppendLine(" != null) {");
                        _sb.Append("                        w.writeBits(0u, ").Append(width).Append(")   // ")
                           .AppendLine(c.FieldName);
                        EmitEncodeValue(c, "msg." + Prop(c.FieldName) + "!!", "                        ");
                        _sb.Append("                        st").Append(id).Append(" = ").Append(s - start + 1).AppendLine();
                        _sb.AppendLine("                    } else {");
                        _sb.Append("                        w.writeBits(1u, ").Append(width).AppendLine(")   // element EE");
                        _sb.Append("                        done").Append(id).AppendLine(" = true");
                        _sb.AppendLine("                    }");
                    }
                    else
                    {
                        _sb.Append("                    w.writeBits(0u, ").Append(width).AppendLine(")   // element EE");
                        _sb.Append("                    done").Append(id).AppendLine(" = true");
                    }

                    _sb.AppendLine("                }");
                }

                _sb.AppendLine("            }");
                _sb.AppendLine("        }");
            }

            private void EmitEncodeValue(ChildPlan c, string accessor, string indent, bool inList = false)
            {
                if (c.Value is ValueEncoding.ComplexRef cr)
                {
                    _sb.Append(indent).Append("encode").Append(cr.TypeName).Append("(w, ").Append(accessor).AppendLine(")");
                    return;
                }

                _sb.Append(indent).AppendLine("w.writeBits(0u, 1)   // value-start");
                switch (c.Value)
                {
                    case ValueEncoding.StringValue:
                        _sb.Append(indent).Append("ExiPrimitives.writeStringValue(w, ").Append(accessor).AppendLine(")");
                        break;
                    case ValueEncoding.UnsignedInt:
                        _sb.Append(indent).Append("ExiPrimitives.writeUnsignedInteger(w, ").Append(accessor).AppendLine(".toULong())");
                        break;
                    case ValueEncoding.SignedInt:
                        _sb.Append(indent).Append("ExiPrimitives.writeSignedInteger(w, ").Append(accessor).AppendLine(".toLong())");
                        break;
                    case ValueEncoding.Binary:
                        _sb.Append(indent).Append("ExiPrimitives.writeBinary(w, ").Append(accessor).AppendLine(")");
                        break;
                    case ValueEncoding.EnumIndex ei:
                        _sb.Append(indent).Append("w.writeBits(").Append(accessor).Append(".ordinal.toUInt(), ")
                           .Append(ei.BitWidth).AppendLine(")");
                        break;
                    case ValueEncoding.NBitUnsigned nb:
                        var expr = nb.Bias == 0
                                       ? accessor + ".toLong()"
                                       : "(" + accessor + ".toLong() - " + nb.Bias + "L)";
                        _sb.Append(indent).Append("w.writeBits(").Append(expr).Append(".toUInt(), ")
                           .Append(nb.BitWidth).AppendLine(")");
                        break;
                    default:
                        throw new NotSupportedException($"Kotlin back end: value encoding {c.Value.GetType().Name}.");
                }
                _sb.Append(indent).AppendLine("w.writeBits(0u, 1)   // child EE");
            }

            private void EmitDecode(SequencePlan sp, string name)
            {
                _sb.Append("    private fun decode").Append(name).Append("(r: BitReader): ")
                   .Append(name).AppendLine(" {");

                var kids = sp.Children;
                var ctor = new List<string>();

                for (var i = 0; i < kids.Count;)
                {
                    var c = kids[i];
                    if (c.Shape == ChildShape.BoundedRepeating)
                    {
                        _sb.Append("        val list = ArrayList<").Append(Type(c.Type)).AppendLine(">()");
                        _sb.AppendLine("        r.readBits(1)   // SE(item) first");
                        _sb.Append("        list.add(").Append(DecodeValueExpr(c)).AppendLine(")");
                        _sb.AppendLine("        while (true) {");
                        _sb.AppendLine("            val ec = r.readBits(2)");
                        _sb.AppendLine("            if (ec == 1u) break   // element EE");
                        _sb.Append("            require(ec == 0u && list.size < ").Append(ListBounds(c, sp).Max)
                           .AppendLine(") { \"invalid repeating-element event code\" }");
                        _sb.Append("            list.add(").Append(DecodeValueExpr(c)).AppendLine(")");
                        _sb.AppendLine("        }");
                        ctor.Add("list");
                        i++;
                        continue;
                    }
                    if (c.Shape == ChildShape.OptionalSingle)
                    {
                        EmitDecodeOptionalRun(kids, i, ctor);
                        i = kids.Count;
                        continue;
                    }

                    _sb.AppendLine("        r.readBits(1)   // SE");
                    var v = "_" + Prop(c.FieldName);
                    if (c.Value is ValueEncoding.ComplexRef)
                    {
                        _sb.Append("        val ").Append(v).Append(" = ").AppendLine(DecodeValueExpr(c));
                    }
                    else
                    {
                        _sb.AppendLine("        r.readBits(1)   // value-start");
                        _sb.Append("        val ").Append(v).Append(" = ").AppendLine(DecodeValueExpr(c));
                        _sb.AppendLine("        r.readBits(1)   // child EE");
                    }
                    ctor.Add(v);
                    i++;
                    if (i == kids.Count)
                        _sb.AppendLine("        r.readBits(1)   // element EE");
                }

                if (kids.Count == 0)
                    _sb.AppendLine("        r.readBits(1)   // element EE");

                _sb.Append("        return ").Append(name).Append("(").Append(string.Join(", ", ctor)).AppendLine(")");
                _sb.AppendLine("    }");
                _sb.AppendLine();
            }

            private void EmitDecodeOptionalRun(IReadOnlyList<ChildPlan> kids, int start, List<string> ctor)
            {
                var id = _run++;
                for (var s = start; s < kids.Count; s++)
                {
                    var c = kids[s];
                    _sb.Append("        var _").Append(Prop(c.FieldName)).Append(": ").Append(DeclType(c))
                       .AppendLine(" = null");
                    ctor.Add("_" + Prop(c.FieldName));
                }

                _sb.Append("        var st").Append(id).AppendLine(" = 0");
                _sb.Append("        var done").Append(id).AppendLine(" = false");
                _sb.Append("        while (!done").Append(id).AppendLine(") {");
                _sb.Append("            when (st").Append(id).AppendLine(") {");

                for (var s = start; s <= kids.Count; s++)
                {
                    var remaining = kids.Count - s;
                    var width     = BitsFor(remaining + 1 + 1);
                    _sb.Append("                ").Append(s - start).AppendLine(" -> {");
                    _sb.Append("                    when (r.readBits(").Append(width).AppendLine(")) {");

                    if (s < kids.Count)
                    {
                        var c = kids[s];
                        _sb.AppendLine("                        0u -> {");
                        if (c.Value is ValueEncoding.ComplexRef)
                        {
                            _sb.Append("                            _").Append(Prop(c.FieldName)).Append(" = ")
                               .AppendLine(DecodeValueExpr(c));
                        }
                        else
                        {
                            _sb.AppendLine("                            r.readBits(1)   // value-start");
                            _sb.Append("                            _").Append(Prop(c.FieldName)).Append(" = ")
                               .AppendLine(DecodeValueExpr(c));
                            _sb.AppendLine("                            r.readBits(1)   // child EE");
                        }
                        _sb.Append("                            st").Append(id).Append(" = ").Append(s - start + 1).AppendLine();
                        _sb.AppendLine("                        }");
                        _sb.Append("                        1u -> done").Append(id).AppendLine(" = true");
                    }
                    else
                    {
                        _sb.Append("                        0u -> done").Append(id).AppendLine(" = true");
                    }

                    _sb.AppendLine("                        else -> throw IllegalArgumentException(\"invalid optional-run event code\")");
                    _sb.AppendLine("                    }");
                    _sb.AppendLine("                }");
                }

                _sb.AppendLine("            }");
                _sb.AppendLine("        }");
            }

            private string DecodeValueExpr(ChildPlan c) => c.Value switch
            {
                ValueEncoding.ComplexRef cr  => $"decode{cr.TypeName}(r)",
                ValueEncoding.StringValue    => "ExiPrimitives.readStringValue(r)",
                ValueEncoding.UnsignedInt    => $"ExiPrimitives.readUnsignedInteger(r).{ToNarrow(c.Type)}",
                ValueEncoding.SignedInt      => $"ExiPrimitives.readSignedInteger(r).{ToNarrow(c.Type)}",
                ValueEncoding.Binary         => "ExiPrimitives.readBinary(r)",
                ValueEncoding.EnumIndex ei   => $"{ei.EnumName}.entries[r.readBits({ei.BitWidth}).toInt()]",
                ValueEncoding.NBitUnsigned nb => nb.Bias == 0
                                                    ? $"r.readBits({nb.BitWidth}).{ToNarrow(c.Type)}"
                                                    : $"(r.readBits({nb.BitWidth}).toLong() + {nb.Bias}L).{ToNarrow(c.Type)}",
                _ => throw new NotSupportedException($"Kotlin back end: value encoding {c.Value.GetType().Name}."),
            };

            /// <summary>Kotlin has no implicit numeric conversions — every read needs an explicit narrowing.</summary>
            private static string ToNarrow(TypeRef t) => t switch
            {
                TypeRef.Primitive p => p.Kind switch
                {
                    PrimitiveKind.Int8   => "toByte()",
                    PrimitiveKind.Int16  => "toShort()",
                    PrimitiveKind.Int32  => "toInt()",
                    PrimitiveKind.Int64  => "toLong()",
                    PrimitiveKind.UInt8  => "toUByte()",
                    PrimitiveKind.UInt16 => "toUShort()",
                    PrimitiveKind.UInt32 => "toUInt()",
                    PrimitiveKind.UInt64 => "toULong()",
                    PrimitiveKind.Bool   => "toInt() != 0",
                    _ => throw new NotSupportedException($"Kotlin back end: narrowing for {p.Kind}."),
                },
                _ => throw new NotSupportedException("Kotlin back end: narrowing for a named type."),
            };

            /// <summary>
            /// Occurrence bounds of a repeating child. For the "single repeating element" shape the
            /// builder records them on the <see cref="SequencePlan"/> and leaves the
            /// <see cref="ChildPlan"/>'s at zero; a repeating child among siblings carries its own.
            /// </summary>
            private static (int Min, int Max) ListBounds(ChildPlan c, SequencePlan sp) =>
                c.ListMax != 0 ? (Math.Max(c.ListMin, 1), c.ListMax)
                               : (Math.Max(sp.ListMin, 1), sp.ListMax);

            /// <summary>⌈log₂(n)⌉, with the EXI convention that n = 1 needs 0 bits.</summary>
            private static int BitsFor(int n)
            {
                var bits = 0;
                while ((1 << bits) < n) bits++;
                return bits;
            }
        }
    }
}
