using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Vanaheimr.V2G.Exi.SourceGenerator.Grammar;

namespace Vanaheimr.V2G.Exi.SourceGenerator.Emit
{
    /// <summary>
    /// Kotlin back end — the second target through <see cref="ICodecEmitter"/>, and the proof
    /// that the front end is genuinely language-neutral.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Scope: deliberately partial.</b> This covers the constructs the AppProtocol schema
    /// exercises — enums, records, required/optional/repeating children, and the
    /// string / unsigned-integer / n-bit / enum-index value encodings. Everything else
    /// (substitution groups, inline choices, attributes, simple content, opaque elements,
    /// fragments) throws <see cref="NotSupportedException"/> rather than emitting something
    /// plausible, following the generator's fail-loud rule: an unhandled construct must break
    /// the build, never produce silently wrong bytes.
    /// </para>
    /// <para>
    /// Bit-level behaviour mirrors <see cref="CodecEmitter"/> exactly — same event codes, same
    /// widths, same order — because both are driven by the same <see cref="SchemaPlan"/>. The
    /// vectors under <c>Vanaheimr.V2G.Exi.Tests/Vectors/</c> are the shared oracle.
    /// </para>
    /// </remarks>
    internal sealed class KotlinCodecEmitter : ICodecEmitter
    {
        public static readonly KotlinCodecEmitter Instance = new();

        public string Language      => "kotlin";
        public string FileExtension => ".kt";

        public string Emit(SchemaPlan plan, string targetNamespace, string codecClassName) =>
            new Writer(plan, targetNamespace, codecClassName).Run();

        private sealed class Writer(SchemaPlan plan, string package, string codecObject)
        {
            private readonly StringBuilder _sb = new();
            private readonly HashSet<string> _emitted = new(StringComparer.Ordinal);
            private readonly HashSet<string> _codecs  = new(StringComparer.Ordinal);
            private HashSet<string> _baseNames = new(StringComparer.Ordinal);
            private int _run;

            public string Run()
            {
                Reject(plan);

                _sb.AppendLine("// <auto-generated/>");
                _sb.AppendLine("// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.");
                _sb.AppendLine();
                _sb.Append("package ").AppendLine(package);
                _sb.AppendLine();
                _sb.AppendLine("import cloud.charging.v2g.exi.BitReader");
                _sb.AppendLine("import cloud.charging.v2g.exi.BitWriter");
                _sb.AppendLine("import cloud.charging.v2g.exi.ExiPrimitives");
                _sb.AppendLine();

                EmitEnums();
                EmitRecords();
                EmitCodec();
                return _sb.ToString();
            }

            /// <summary>Fail loud on anything this back end does not model yet.</summary>
            private static void Reject(SchemaPlan p)
            {
                if (p.Fragments.Count != 0)
                    throw new NotSupportedException("Kotlin back end: EXI fragment codecs (XMLDSig) are not implemented yet.");

                foreach (var sp in p.ComplexTypes.Values)
                {
                    ValidateAttributes(p, sp);

                    foreach (var c in sp.Children)
                    {
                        // Only an optional wildcard is modelled — it then rides in an optional run,
                        // where TrailingAny() checks the position cbexigen's code layout requires.
                        if (c.IsWildcardAny && c.Shape != ChildShape.OptionalSingle)
                            throw new NotSupportedException(
                                $"Kotlin back end: the xs:any wildcard '{sp.RecordName}.{c.FieldName}' is " +
                                $"{c.Shape}; only an optional wildcard is implemented.");
                        _ = c.Value switch
                        {
                            ValueEncoding.StringValue or ValueEncoding.UnsignedInt or ValueEncoding.SignedInt
                                or ValueEncoding.Binary or ValueEncoding.NBitUnsigned or ValueEncoding.EnumIndex
                                or ValueEncoding.ComplexRef or ValueEncoding.OpaqueElement
                                or ValueEncoding.SubstitutionChoice => true,
                            _ => throw new NotSupportedException(
                                     $"Kotlin back end: value encoding {c.Value.GetType().Name} " +
                                     $"('{sp.RecordName}.{c.FieldName}') is not implemented yet."),
                        };
                    }
                }
            }

            /// <summary>
            /// Attribute shapes this back end models: either a single required attribute, or any
            /// number of optional ones, all string-typed. On a derived type they are only safe while
            /// the base contributes no constructor parameters of its own — attributes go first, so
            /// otherwise they would have to interleave with the base's. (The common -2 case, a body
            /// type extending the empty <c>BodyBaseType</c>, is fine.)
            /// </summary>
            private static void ValidateAttributes(SchemaPlan plan, SequencePlan sp)
            {
                if (sp.Attributes is null or { Count: 0 })
                    return;

                if (sp.BaseRecordName is not null
                    && plan.ComplexTypes.TryGetValue(sp.BaseRecordName, out var basePlan)
                    && (basePlan.Children.Count > 0 || basePlan.Attributes is { Count: > 0 }))
                    throw new NotSupportedException(
                        $"Kotlin back end: attributes on '{sp.RecordName}', whose base type " +
                        $"'{sp.BaseRecordName}' contributes constructor parameters, are not implemented yet.");

                // Optional attributes ride along as leading optionals of the *content run*, which an
                // xs:choice does not have — they would be dropped silently. (A required attribute is
                // written before the content and is unaffected.)
                if (sp.IsChoice && RequiredAttr(sp) is null)
                    throw new NotSupportedException(
                        $"Kotlin back end: optional attributes on the xs:choice type '{sp.RecordName}' " +
                        "are not implemented yet.");

                foreach (var a in sp.Attributes)
                {
                    if (a.Value is not ValueEncoding.StringValue)
                        throw new NotSupportedException(
                            $"Kotlin back end: only string-typed attributes are supported " +
                            $"('{sp.RecordName}.{a.FieldName}' is {a.Value.GetType().Name}).");
                    if (a.Required && sp.Attributes.Count != 1)
                        throw new NotSupportedException(
                            $"Kotlin back end: '{sp.RecordName}' combines a required attribute with others; " +
                            "only a lone required attribute, or an all-optional set, is modelled.");
                }
            }

            /// <summary>
            /// The record field carrying an xs:simpleContent value. Matches the C# emitter's name, so
            /// both back ends expose the same shape.
            /// </summary>
            private const string SimpleContentField = "Value";

            /// <summary>A synthetic child standing in for the simpleContent value.</summary>
            private static ChildPlan SimpleContentChild(SequencePlan sp) =>
                new(SimpleContentField, sp.SimpleContentType!, IsValueType: false,
                    ChildShape.RequiredSingle, sp.SimpleContent!);

            /// <summary>The lone required attribute of a type, or null.</summary>
            private static AttrPlan? RequiredAttr(SequencePlan sp) =>
                sp.Attributes is { Count: 1 } && sp.Attributes[0].Required ? sp.Attributes[0] : null;

            /// <summary>
            /// Whether a type carries optional attributes. ValidateAttributes has already ruled out
            /// mixtures, so "has attributes and none is the lone required one" means all are optional.
            /// </summary>
            private static bool HasOptionalAttributes(SequencePlan sp) =>
                sp.Attributes is { Count: > 0 } && RequiredAttr(sp) is null;

            /// <summary>
            /// Optional attributes are the leading optionals of the content run: the AT event is the
            /// first production of the content's initial grammar state, and when the attribute is
            /// absent the same code doubles as the first SE (cbexigen model, as in
            /// <see cref="CodecEmitter"/>). Prepending them lets the general run machine handle them.
            /// </summary>
            private static IReadOnlyList<ChildPlan> WithOptionalAttributes(SequencePlan sp)
            {
                if (sp.Attributes is null or { Count: 0 } || RequiredAttr(sp) is not null)
                    return sp.Children;

                var list = new List<ChildPlan>(sp.Attributes.Count + sp.Children.Count);
                foreach (var a in sp.Attributes)
                    list.Add(new ChildPlan(a.FieldName, a.Type, IsValueType: false,
                                           ChildShape.OptionalSingle, new ValueEncoding.AttributeValue()));
                list.AddRange(sp.Children);
                return list;
            }

            /// <summary>
            /// Whether a child's value is framed by a value-start bit and a child EE. An AT value is
            /// not: the run's event code *was* the AT event. A complex child frames itself. An opaque
            /// (un-modelled XMLDSig) child is never really read — it throws — so framing it would
            /// consume a bit before failing and leave the rest unreachable.
            /// </summary>
            private static bool WrapsValue(ChildPlan c) =>
                c.Value is not ValueEncoding.ComplexRef
                       and not ValueEncoding.AttributeValue
                       and not ValueEncoding.OpaqueElement;

            // ---------------------------------------------------------------- naming

            /// <summary>
            /// Kotlin's hard keywords. Lower-casing a PascalCase schema name can land on one — the
            /// C# emitter never hits this because it keeps the name PascalCase. XMLDSig's
            /// <c>Object</c> element is the real-world case.
            /// </summary>
            private static readonly HashSet<string> KotlinKeywords = new(StringComparer.Ordinal)
            {
                "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
                "interface", "is", "null", "object", "package", "return", "super", "this", "throw",
                "true", "try", "typealias", "typeof", "val", "var", "when", "while",
            };

            /// <summary>Kotlin properties are camelCase; the plan's field names are PascalCase.</summary>
            private static string Camel(string pascal) =>
                pascal.Length == 0 ? pascal : char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);

            /// <summary>
            /// A property name as written in declarations and accessors — back-quoted when the
            /// camelCase form collides with a keyword.
            /// </summary>
            private static string Prop(string pascal)
            {
                var name = Camel(pascal);
                return KotlinKeywords.Contains(name) ? "`" + name + "`" : name;
            }

            /// <summary>
            /// The decoder's local for a field. Built from the unescaped name: the leading underscore
            /// already makes it a legal identifier, and back-quotes would not survive concatenation.
            /// </summary>
            private static string Local(string pascal) => "_" + Camel(pascal);

            private static string Type(TypeRef t) => t switch
            {
                TypeRef.Primitive p => p.Kind switch
                {
                    PrimitiveKind.Bool   => "Boolean",
                    PrimitiveKind.Int8   => "Byte",
                    PrimitiveKind.Int16  => "Short",
                    PrimitiveKind.Int32  => "Int",
                    PrimitiveKind.Int64  => "Long",
                    PrimitiveKind.UInt8  => "UByte",
                    PrimitiveKind.UInt16 => "UShort",
                    PrimitiveKind.UInt32 => "UInt",
                    PrimitiveKind.UInt64 => "ULong",
                    PrimitiveKind.String => "String",
                    PrimitiveKind.Binary => "ByteArray",
                    _ => throw new NotSupportedException($"Kotlin back end: primitive {p.Kind}."),
                },
                TypeRef.Named n => n.Name,
                _ => throw new NotSupportedException("Kotlin back end: untyped child."),
            };

            /// <summary>Declared type of a child, including Kotlin's nullability / list wrapping.</summary>
            private static string DeclType(ChildPlan c) => c.Shape switch
            {
                ChildShape.BoundedRepeating => $"List<{Type(c.Type)}>",
                ChildShape.OptionalSingle   => Type(c.Type) + "?",
                _                           => Type(c.Type),
            };

            // ---------------------------------------------------------------- types

            private void EmitEnums()
            {
                foreach (var e in plan.Enums)
                {
                    _sb.Append("enum class ").Append(e.Name).AppendLine(" {");
                    for (var i = 0; i < e.Members.Count; i++)
                        _sb.Append("    ").Append(e.Members[i]).AppendLine(i == e.Members.Count - 1 ? "" : ",");
                    _sb.AppendLine("}");
                    _sb.AppendLine();
                }
            }

            /// <summary>
            /// Kotlin resolves top-level declarations regardless of order, so — unlike the C#
            /// emitter — no dependency or base-before-derived sorting is needed here.
            /// </summary>
            private void EmitRecords()
            {
                foreach (var t in plan.OpaqueTypes)
                {
                    _sb.Append("/** Opaque placeholder for the un-modelled XMLDSig element `").Append(t)
                       .AppendLine("`.");
                    _sb.AppendLine(" *  Only ever encoded/decoded as absent; a present instance fails loud. */");
                    _sb.Append("class ").AppendLine(t);
                    _sb.AppendLine();
                }

                // Not .ToHashSet(): this file is also compiled into the netstandard2.0 analyzer
                // project, whose LINQ has no such overload.
                _baseNames = new HashSet<string>(plan.ComplexTypes.Values
                                                     .Select(s => s.BaseRecordName)
                                                     .Where(n => n is not null)!,
                                                 StringComparer.Ordinal);

                foreach (var ge in plan.GlobalElements)
                    EmitRecord(ge.Body, ge.TypeName);
                foreach (var sp in plan.ComplexTypes.Values)
                    EmitRecord(sp, sp.RecordName);
            }

            private void EmitRecord(SequencePlan sp, string name)
            {
                if (!_emitted.Add(name)) return;

                // A type others extend must be `open`; an abstract one `abstract`. Only leaves that
                // take part in no hierarchy can be `data` classes.
                var extended = _baseNames.Contains(name);
                var keyword  = sp.IsAbstract ? "abstract class"
                             : extended      ? "open class"
                             : sp.BaseRecordName is not null ? "class"
                             : "data class";

                // Inheritance: the first N flattened children belong to the base, are re-declared
                // here as `override`, and are handed straight to the base constructor.
                var baseChildren = sp.BaseRecordName is not null
                                   && plan.ComplexTypes.TryGetValue(sp.BaseRecordName, out var basePlan)
                                       ? basePlan.Children.Count
                                       : 0;

                _sb.Append(keyword).Append(' ').Append(name);

                if (sp.Children.Count == 0 && sp.Attributes is null or { Count: 0 } && sp.SimpleContent is null)
                {
                    _sb.Append(sp.BaseRecordName is not null ? " : " + sp.BaseRecordName + "()" : "").AppendLine();
                    _sb.AppendLine();
                    return;
                }

                // Attributes come first, matching the AT-before-content order of the grammar (and the
                // C# emitter's parameter order). They never belong to a base type — Reject() bars
                // attributes on a derived type — so the base-child indices below are unaffected.
                var parms = new List<string>();
                if (sp.Attributes is not null)
                    foreach (var a in sp.Attributes)
                        parms.Add(((sp.IsAbstract || extended) ? "open val " : "val ")
                                  + Prop(a.FieldName) + ": " + Type(a.Type) + (a.Required ? "" : "?"));

                // xs:simpleContent contributes a single value parameter and has no children.
                if (sp.SimpleContent is not null)
                    parms.Add(((sp.IsAbstract || extended) ? "open val " : "val ")
                              + Prop(SimpleContentField) + ": " + Type(sp.SimpleContentType!));

                for (var i = 0; i < sp.Children.Count; i++)
                {
                    var c = sp.Children[i];
                    var modifier = i < baseChildren ? "override val "
                                 : (sp.IsAbstract || extended) ? "open val "
                                 : "val ";
                    parms.Add(modifier + Prop(c.FieldName) + ": " + DeclType(c));
                }

                _sb.AppendLine("(");
                for (var i = 0; i < parms.Count; i++)
                    _sb.Append("    ").Append(parms[i]).AppendLine(i == parms.Count - 1 ? "" : ",");
                _sb.Append(")");

                if (sp.BaseRecordName is not null)
                {
                    var args = string.Join(", ", sp.Children.Take(baseChildren).Select(c => Prop(c.FieldName)));
                    _sb.Append(" : ").Append(sp.BaseRecordName).Append('(').Append(args).Append(')');
                }
                _sb.AppendLine();
                _sb.AppendLine();
            }

            // ---------------------------------------------------------------- codec

            private void EmitCodec()
            {
                _sb.Append("object ").Append(codecObject).AppendLine(" {");
                _sb.AppendLine();
                _sb.AppendLine("    const val EXI_HEADER: Byte = 0x80.toByte()");
                _sb.AppendLine();
                _sb.AppendLine("    /** Generous upper bound; encode() returns a right-sized copy. */");
                _sb.AppendLine("    private const val MAX_MESSAGE_BYTES = 65536");
                _sb.AppendLine();

                foreach (var ge in plan.GlobalElements)
                {
                    _sb.Append("    fun encode(msg: ").Append(ge.TypeName).AppendLine("): ByteArray {");
                    _sb.AppendLine("        val buf = ByteArray(MAX_MESSAGE_BYTES)");
                    _sb.AppendLine("        buf[0] = EXI_HEADER");
                    _sb.AppendLine("        val w = BitWriter(buf, 1)");
                    _sb.Append("        w.writeBits(").Append(ge.DocumentIndex).Append("u, ")
                       .Append(plan.DocumentSelectorBits).AppendLine(")   // document element selector");
                    _sb.Append("        encode").Append(ge.TypeName).AppendLine("(w, msg)");
                    _sb.AppendLine("        w.alignToByte()");
                    _sb.AppendLine("        return buf.copyOf(1 + w.bytesWritten)");
                    _sb.AppendLine("    }");
                    _sb.AppendLine();
                }

                _sb.AppendLine("    fun decodeAny(src: ByteArray): Any {");
                _sb.AppendLine("        require(src.isNotEmpty() && src[0] == EXI_HEADER) { \"Invalid EXI header.\" }");
                _sb.AppendLine("        val r = BitReader(src, 1)");
                _sb.Append("        return when (val sel = r.readBits(").Append(plan.DocumentSelectorBits).AppendLine(")) {");
                foreach (var ge in plan.GlobalElements)
                    _sb.Append("            ").Append(ge.DocumentIndex).Append("u -> decode")
                       .Append(ge.TypeName).AppendLine("(r)");
                _sb.AppendLine("            else -> throw IllegalArgumentException(\"Unknown document index $sel.\")");
                _sb.AppendLine("        }");
                _sb.AppendLine("    }");
                _sb.AppendLine();

                foreach (var sp in plan.ComplexTypes.Values)
                    EmitSequenceCodec(sp, sp.RecordName);
                foreach (var ge in plan.GlobalElements)
                    EmitSequenceCodec(ge.Body, ge.TypeName);

                _sb.AppendLine("}");
            }

            /// <summary>
            /// A global element's body is also registered in <c>ComplexTypes</c>, so the two
            /// emission loops overlap; emit each codec pair once.
            /// </summary>
            private void EmitSequenceCodec(SequencePlan sp, string name)
            {
                // An abstract type is never encoded or decoded through its own name — substitution
                // dispatch always names a concrete member — and a decoder for one would have to
                // instantiate it. The C# emitter skips them for the same reason.
                if (sp.IsAbstract) return;
                if (!_codecs.Add(name)) return;
                EmitEncode(sp, name);
                EmitDecode(sp, name);
            }

            private void EmitEncode(SequencePlan sp, string name)
            {
                _sb.Append("    private fun encode").Append(name).Append("(w: BitWriter, msg: ")
                   .Append(name).AppendLine(") {");

                // A required attribute is unconditional: a 1-bit AT event, then a bare value.
                if (RequiredAttr(sp) is { } req)
                {
                    _sb.AppendLine("        w.writeBits(0u, 1)   // AT(required attribute)");
                    _sb.Append("        ExiPrimitives.writeStringValue(w, msg.").Append(Prop(req.FieldName)).AppendLine(")");
                }

                if (sp.SimpleContent is not null)
                {
                    if (HasOptionalAttributes(sp))
                        EmitEncodeSimpleContentOptionalAttrs(sp);
                    else
                    {
                        _sb.AppendLine("        w.writeBits(0u, 1)   // CONTENT event");
                        EmitEncodeBareValue(SimpleContentChild(sp), "msg." + Prop(SimpleContentField), "        ");
                    }
                    _sb.AppendLine("        w.writeBits(0u, 1)   // element EE");
                    _sb.AppendLine("    }");
                    _sb.AppendLine();
                    return;
                }

                if (sp.IsChoice)
                {
                    EmitEncodeChoice(sp);
                    _sb.AppendLine("        w.writeBits(0u, 1)   // element EE");
                    _sb.AppendLine("    }");
                    _sb.AppendLine();
                    return;
                }

                var kids = WithOptionalAttributes(sp);
                for (var i = 0; i < kids.Count;)
                {
                    var c = kids[i];
                    if (c.Shape == ChildShape.BoundedRepeating)
                    {
                        if (kids.Count == 1)
                            EmitEncodeList(c, sp);
                        else if (c.ListMin > 0 && i == kids.Count - 1)
                            EmitEncodeRepeatingChild(c, "        ");
                        else
                            throw new NotSupportedException(
                                $"Kotlin back end: the repeating child '{name}.{c.FieldName}' is neither the " +
                                "sequence's only child nor a required list closing it; not implemented yet.");
                        i++;   // the list's own terminator doubles as the element EE
                        continue;
                    }
                    if (c.Shape == ChildShape.OptionalSingle)
                    {
                        // A run of optionals ends either at the element EE or at the first required
                        // child, which then carries the run's highest event code.
                        var e    = RunEnd(kids, i);
                        var term = e < kids.Count ? kids[e] : null;
                        RejectRunTerminator(term, name);

                        EmitEncodeOptionalRun(kids, i, e, term);

                        i = term is null ? kids.Count : e + 1;
                        // A repeating terminator closes the element with its own list-end EE.
                        if (term is not null && term.Shape != ChildShape.BoundedRepeating && i == kids.Count)
                            _sb.AppendLine("        w.writeBits(0u, 1)   // element EE");
                        continue;
                    }

                    // A substitution reference is dispatched by its own event code; that code IS the
                    // selector, so no SE precedes it.
                    if (c.Value is ValueEncoding.SubstitutionChoice sub)
                    {
                        EmitEncodeSubstitution(c, sub);
                        i++;
                        if (i == kids.Count)
                            _sb.AppendLine("        w.writeBits(0u, 1)   // element EE");
                        continue;
                    }

                    _sb.AppendLine("        w.writeBits(0u, 1)   // SE");
                    EmitEncodeValue(c, "msg." + Prop(c.FieldName), "        ");
                    i++;
                    if (i == kids.Count)
                        _sb.AppendLine("        w.writeBits(0u, 1)   // element EE");
                }

                if (kids.Count == 0)
                    _sb.AppendLine("        w.writeBits(0u, 1)   // element EE");

                _sb.AppendLine("    }");
                _sb.AppendLine();
            }

            /// <summary>
            /// xs:simpleContent with optional attributes: a bare value (CONTENT) preceded by an
            /// optional run of AT productions. State k offers <c>{attr_k … attr_{n-1}, CONTENT}</c>
            /// over ceil(log2(count+1)) bits — the same grammar <c>CodecEmitter</c> emits, verified
            /// there against SignatureValueType. The element EE is a separate 1-bit production the
            /// caller writes.
            /// </summary>
            private void EmitEncodeSimpleContentOptionalAttrs(SequencePlan sp)
            {
                var oa    = sp.Attributes!;
                var n     = oa.Count;
                var id    = _run++;
                var value = SimpleContentChild(sp);
                const string ind = "                    ";

                _sb.Append("        var st").Append(id).AppendLine(" = 0");
                _sb.Append("        var done").Append(id).AppendLine(" = false");
                _sb.Append("        while (!done").Append(id).AppendLine(") {");
                _sb.Append("            when (st").Append(id).AppendLine(") {");

                for (var k = 0; k <= n; k++)
                {
                    // remaining optional attributes + CONTENT, plus the non-strict phantom
                    var width = BitsFor((n - k + 1) + 1);
                    _sb.Append("                ").Append(k).AppendLine(" -> {");

                    var code  = 0;
                    var first = true;
                    for (var i = k; i < n; i++, code++, first = false)
                    {
                        var prop = "msg." + Prop(oa[i].FieldName);
                        _sb.Append(ind).Append(first ? "if (" : "} else if (").Append(prop).AppendLine(" != null) {");
                        _sb.Append(ind).Append("    w.writeBits(").Append(code).Append("u, ").Append(width)
                           .Append(")   // AT(").Append(oa[i].FieldName).AppendLine(")");
                        _sb.Append(ind).Append("    ExiPrimitives.writeStringValue(w, ").Append(prop).AppendLine("!!)");
                        _sb.Append(ind).Append("    st").Append(id).Append(" = ").Append(i + 1).AppendLine();
                    }

                    var tail = first ? ind : ind + "    ";
                    if (!first)
                        _sb.Append(ind).AppendLine("} else {");

                    _sb.Append(tail).Append("w.writeBits(").Append(code).Append("u, ").Append(width)
                       .AppendLine(")   // CONTENT");
                    EmitEncodeBareValue(value, "msg." + Prop(SimpleContentField), tail);
                    _sb.Append(tail).Append("done").Append(id).AppendLine(" = true");

                    if (!first)
                        _sb.Append(ind).AppendLine("}");

                    _sb.AppendLine("                }");
                }

                _sb.AppendLine("            }");
                _sb.AppendLine("        }");
            }

            /// <summary>
            /// xs:choice content: exactly one alternative is present, and its index — not an SE — is
            /// the event code, over a width covering the alternatives plus the non-strict phantom.
            /// The caller writes the element EE afterwards.
            /// </summary>
            private void EmitEncodeChoice(SequencePlan sp)
            {
                if (sp.Children.Count == 0)
                    throw new NotSupportedException($"Kotlin back end: '{sp.RecordName}' is an empty xs:choice.");

                var width = BitsFor(sp.Children.Count + 1);
                for (var i = 0; i < sp.Children.Count; i++)
                {
                    var c    = sp.Children[i];
                    var prop = "msg." + Prop(c.FieldName);
                    _sb.Append("        ").Append(i == 0 ? "if (" : "} else if (").Append(prop).AppendLine(" != null) {");
                    _sb.Append("            w.writeBits(").Append(i).Append("u, ").Append(width)
                       .Append(")   // ").AppendLine(c.FieldName);
                    EmitEncodeValue(c, prop + "!!", "            ");
                }
                _sb.AppendLine("        } else {");
                _sb.Append("            throw IllegalArgumentException(\"no choice alternative set for ")
                   .Append(sp.RecordName).AppendLine("\")");
                _sb.AppendLine("        }");
            }

            /// <summary>
            /// A repeating child: first item takes a 1-bit SE, every following item and the
            /// terminator a 2-bit event code (item = 0, EE = 1). Mirrors <c>CodecEmitter</c>.
            /// </summary>
            private void EmitEncodeList(ChildPlan c, SequencePlan sp)
            {
                var (min, max) = ListBounds(c, sp);
                _sb.Append("        val list = msg.").AppendLine(Prop(c.FieldName));
                EmitEncodeRepeating(c, "list", min, max, "        ");
            }

            /// <summary>
            /// A required list closing a sequence that has other children too. Unlike the lone-child
            /// case the bounds sit on the child, and the local is named after the field so it cannot
            /// collide with a sibling's.
            /// </summary>
            private void EmitEncodeRepeatingChild(ChildPlan c, string indent)
            {
                var list = ListLocal(c);
                _sb.Append(indent).Append("val ").Append(list).Append(" = msg.").AppendLine(Prop(c.FieldName));
                EmitEncodeRepeating(c, list, Math.Max(1, c.ListMin), c.ListMax, indent);
            }

            private static string ListLocal(ChildPlan c) => Camel(c.FieldName) + "List";

            /// <summary>
            /// A repeating element inside an optional run. The first item takes the run state's event
            /// code; every further item and the closing EE use the 2-bit loop code {item = 0, EE = 1}.
            /// </summary>
            private void EmitEncodeRepeatingItems(ChildPlan p, int firstCode, int width, string indent, string after)
            {
                var list = "msg." + Prop(p.FieldName);
                _sb.Append(indent).Append("w.writeBits(").Append(firstCode).Append("u, ").Append(width)
                   .Append(")   // ").AppendLine(p.FieldName);
                EmitEncodeValue(p, list + "[0]", indent);
                _sb.Append(indent).Append("for (ci in 1 until ").Append(list).AppendLine(".size) {");
                _sb.Append(indent).Append("    w.writeBits(0u, 2)   // ").AppendLine(p.FieldName);
                EmitEncodeValue(p, list + "[ci]", indent + "    ");
                _sb.Append(indent).AppendLine("}");
                _sb.Append(indent).AppendLine("w.writeBits(1u, 2)   // element EE (list end)");
                _sb.Append(indent).AppendLine(after);
            }

            /// <summary>
            /// Declares a run particle's local in record order: a list gets an empty collection (an
            /// empty one also encodes "absent"), everything else a nullable.
            /// </summary>
            private void DeclareRunLocal(ChildPlan c, List<string> ctor)
            {
                if (c.Shape == ChildShape.BoundedRepeating)
                {
                    _sb.Append("        val ").Append(ListLocal(c)).Append(" = ArrayList<")
                       .Append(Type(c.Type)).AppendLine(">()");
                    ctor.Add(ListLocal(c));
                    return;
                }
                _sb.Append("        var ").Append(Local(c.FieldName)).Append(": ").Append(DeclType(c))
                   .AppendLine(" = null");
                ctor.Add(Local(c.FieldName));
            }

            /// <summary>Decode mirror of <see cref="EmitEncodeRepeatingItems"/>.</summary>
            private void EmitDecodeRepeatingItems(ChildPlan p, string list, string indent, string after)
            {
                EmitDecodeItem(p, list, list + "First", indent);   // the event code was its SE
                _sb.Append(indent).AppendLine("while (true) {");
                _sb.Append(indent).AppendLine("    val lc = r.readBits(2)");
                _sb.Append(indent).AppendLine("    if (lc == 1u) break   // element EE (list end)");
                _sb.Append(indent).Append("    require(lc == 0u && ").Append(list).Append(".size < ")
                   .Append(p.ListMax).AppendLine(") { \"invalid repeating-element event code\" }");
                EmitDecodeItem(p, list, list + "Next", indent + "    ");
                _sb.Append(indent).AppendLine("}");
                _sb.Append(indent).AppendLine(after);
            }

            /// <summary>
            /// The item loop of a bounded-repeating child: the first item takes a 1-bit SE, every
            /// following item a 2-bit event code. Mirrors <c>CodecEmitter</c>.
            /// </summary>
            private void EmitEncodeRepeating(ChildPlan c, string list, int min, int max, string indent)
            {
                _sb.Append(indent).Append("require(").Append(list).Append(".size in ").Append(min)
                   .Append("..").Append(max).AppendLine(") { \"list size out of schema range\" }");
                _sb.Append(indent).Append("for (i in ").Append(list).AppendLine(".indices) {");
                _sb.Append(indent).AppendLine("    w.writeBits(0u, if (i == 0) 1 else 2)   // SE(item)");
                EmitEncodeValue(c, list + "[i]", indent + "    ");
                _sb.Append(indent).AppendLine("}");
                EmitEncodeListTerminator(list, max, indent);
            }

            /// <summary>
            /// At maxOccurs=2 a full list has no "another item" production left, so the grammar closes
            /// it with the 1-bit element EE rather than the 2-bit terminator.
            /// </summary>
            private void EmitEncodeListTerminator(string list, int max, string indent)
            {
                if (max == 2)
                {
                    _sb.Append(indent).Append("if (").Append(list)
                       .AppendLine(".size >= 2) w.writeBits(0u, 1)   // element EE (list at max)");
                    _sb.Append(indent).AppendLine("else w.writeBits(1u, 2)   // element EE");
                }
                else
                    _sb.Append(indent).AppendLine("w.writeBits(1u, 2)   // list terminator / element EE");
            }

            /// <summary>
            /// The exclusive end of the optional run starting at <paramref name="i"/>: consecutive
            /// optionals, and — as <c>CodecEmitter</c> does — at most one optional bounded-repeating
            /// particle among them, since an empty list is itself the "absent" encoding.
            /// </summary>
            /// <summary>
            /// An optional list inside a run must be its last particle. cbexigen encodes a mid-run
            /// list with a different, narrower grammar (the particles after it become unreachable
            /// until an item is written, and it is hard-capped at two items); that shape is modelled
            /// in <c>CodecEmitter</c> but not here, and it must not silently take this path.
            /// </summary>
            private static void RejectMidRunList(IReadOnlyList<ChildPlan> kids, int start, int end)
            {
                for (var p = start; p < end - 1; p++)
                    if (kids[p].Shape == ChildShape.BoundedRepeating)
                        throw new NotSupportedException(
                            $"Kotlin back end: the optional list '{kids[p].FieldName}' is not the last " +
                            "particle of its run; that grammar is not implemented yet.");
            }

            private static int RunEnd(IReadOnlyList<ChildPlan> kids, int i)
            {
                var j = i;
                while (j < kids.Count && kids[j].Shape == ChildShape.OptionalSingle) j++;
                if (j < kids.Count && kids[j].Shape == ChildShape.BoundedRepeating && kids[j].ListMin == 0)
                {
                    j++;
                    while (j < kids.Count && kids[j].Shape == ChildShape.OptionalSingle) j++;
                }
                return j;
            }

            /// <summary>
            /// Only a plain required child may close an optional run so far; anything else would
            /// need extra productions in the run's tail code.
            /// </summary>
            private static void RejectRunTerminator(ChildPlan? term, string owner)
            {
                if (term is null)
                    return;
                if (term.Shape == ChildShape.BoundedRepeating && term.ListMin == 0)
                    throw new NotSupportedException(
                        $"Kotlin back end: '{owner}.{term.FieldName}' terminates an optional run but is an " +
                        "optional list; only a required one is modelled here.");
                if (term.Shape is not (ChildShape.RequiredSingle or ChildShape.BoundedRepeating))
                    throw new NotSupportedException(
                        $"Kotlin back end: '{owner}.{term.FieldName}' terminates an optional run but is {term.Shape}.");
            }

            /// <summary>
            /// A run of optional children spanning [start, end). It is closed either by the element
            /// EE (<paramref name="term"/> is null) or by the required child at <paramref name="end"/>,
            /// which then occupies the run's highest event code. At each state the code width covers
            /// the still-possible productions plus the non-strict phantom, exactly as
            /// <c>CodecEmitter</c> computes it.
            /// </summary>
            private void EmitEncodeOptionalRun(IReadOnlyList<ChildPlan> kids, int start, int end, ChildPlan? term)
            {
                var m           = end - start;
                var id          = _run++;
                var trailingAny = TrailingAny(kids, start, end, term);
                RejectMidRunList(kids, start, end);
                const string ind = "                    ";

                _sb.Append("        var st").Append(id).AppendLine(" = 0");
                _sb.Append("        var done").Append(id).AppendLine(" = false");
                _sb.Append("        while (!done").Append(id).AppendLine(") {");
                _sb.Append("            when (st").Append(id).AppendLine(") {");

                // State k: the cursor sits at particle start+k; any particle from there on may be
                // the next one present, so each state offers all of them.
                for (var k = 0; k <= m; k++)
                {
                    var totalProd = term is null ? 1                        // the element EE
                                                 : ProductionCount(term);   // or the required child
                    for (var i = k; i < m; i++) totalProd += ProductionCount(kids[start + i]);
                    var width = BitsFor(totalProd + 1);                  // + the non-strict phantom

                    _sb.Append("                ").Append(k).AppendLine(" -> {");

                    var code   = 0;
                    var first  = true;
                    var optEnd = trailingAny ? m - 1 : m;   // the ANY is handled with the tail

                    EmitEncodeRunSubLocals(kids, start, k, optEnd, term, ind);

                    for (var i = k; i < optEnd; i++)
                    {
                        // A list consumes the rest of the element: its own list-end EE closes it.
                        var after = kids[start + i].Shape == ChildShape.BoundedRepeating
                                        ? $"done{id} = true"
                                        : $"st{id} = {i + 1}";
                        code = EmitEncodeRunParticle(kids[start + i], code, width, ref first, ind, after);
                    }

                    var eeCode = code;
                    if (trailingAny && k < m)
                    {
                        // cbexigen ordering: [normal optionals], the generic-wildcard slot (reserved,
                        // never emitted), the element EE, then the typed ANY element. Selecting ANY
                        // advances to the EE-only state.
                        EmitEncodeRunParticle(kids[end - 1], code + 2, width, ref first, ind, $"st{id} = {m}");
                        eeCode = code + 1;
                    }

                    // A required repeating terminator: its first item takes the run's tail code, and
                    // its own list-end EE closes the element.
                    if (term?.Shape == ChildShape.BoundedRepeating)
                    {
                        var repTail = first ? ind : ind + "    ";
                        if (!first)
                            _sb.Append(ind).AppendLine("} else {");
                        _sb.Append(repTail).Append("require(msg.").Append(Prop(term.FieldName))
                           .Append(".size in 1..").Append(term.ListMax)
                           .AppendLine(") { \"list size out of schema range\" }");
                        EmitEncodeRepeatingItems(term, eeCode, width, repTail, $"done{id} = true");
                        if (!first)
                            _sb.Append(ind).AppendLine("}");
                        _sb.AppendLine("                }");
                        continue;
                    }

                    // A substitution terminator has one production per member, so it extends the
                    // chain rather than closing it; the chain then ends in a throw, because a
                    // required child must be set.
                    if (term?.Value is ValueEncoding.SubstitutionChoice)
                    {
                        EmitEncodeRunParticle(term, eeCode, width, ref first, ind, $"done{id} = true");
                        _sb.Append(ind).AppendLine("} else {");
                        _sb.Append(ind).Append("    throw IllegalArgumentException(\"no value set for ")
                           .Append(term.FieldName).AppendLine("\")");
                        _sb.Append(ind).AppendLine("}");
                        _sb.AppendLine("                }");
                        continue;
                    }

                    // The highest remaining code closes the run: the element EE, or the required
                    // child — whose content then follows inline.
                    var tail = first ? ind : ind + "    ";
                    if (!first)
                        _sb.Append(ind).AppendLine("} else {");

                    _sb.Append(tail).Append("w.writeBits(").Append(eeCode).Append("u, ").Append(width);
                    if (term is null)
                        _sb.AppendLine(")   // element EE");
                    else
                    {
                        _sb.Append(")   // SE(").Append(term.FieldName).AppendLine(")");
                        EmitEncodeValue(term, "msg." + Prop(term.FieldName), tail);
                    }
                    _sb.Append(tail).Append("done").Append(id).AppendLine(" = true");

                    if (!first)
                        _sb.Append(ind).AppendLine("}");

                    _sb.AppendLine("                }");
                }

                _sb.AppendLine("            }");
                _sb.AppendLine("        }");
            }

            /// <summary>
            /// One particle of an optional run: an optional element (one production) or an optional
            /// substitution reference (one production per member, the abstract head reserving a code
            /// slot without a branch). Emits an <c>if</c> / <c>} else if</c> link of the state's
            /// chain and returns the next free event code.
            /// </summary>
            private int EmitEncodeRunParticle(ChildPlan p, int code, int width, ref bool first,
                                              string indent, string after)
            {
                var prop = "msg." + Prop(p.FieldName);

                if (p.Shape == ChildShape.BoundedRepeating)
                {
                    // An empty list means this optional element is absent.
                    _sb.Append(indent).Append(first ? "if (" : "} else if (").Append(prop).AppendLine(".isNotEmpty()) {");
                    _sb.Append(indent).Append("    require(").Append(prop).Append(".size <= ").Append(p.ListMax)
                       .AppendLine(") { \"list size out of schema range\" }");
                    EmitEncodeRepeatingItems(p, code, width, indent + "    ", after);
                    first = false;
                    return code + 1;
                }

                if (p.Value is ValueEncoding.SubstitutionChoice sc)
                {
                    // Hoisted into a local because `is` cannot smart-cast an `open`/`override` property,
                    // which generated base types declare.
                    // The local is declared by EmitEncodeRunSubLocals before the chain opens; every
                    // branch must use it, because a `val` cannot be introduced mid-chain and `is`
                    // cannot smart-cast the `open`/`override` property a generated base type declares.
                    var local    = SubLocal(p);
                    var baseCode = code;
                    var ordered  = sc.Members
                                     .Select((mm, i) => (Member: mm, Wire: baseCode + i))
                                     .Where(x => !x.Member.IsAbstractHead)
                                     .OrderByDescending(x => InheritanceDepth(x.Member.TypeName));

                    foreach (var (mbr, wire) in ordered)
                    {
                        _sb.Append(indent).Append(first ? "if (" : "} else if (")
                           .Append(local).Append(" is ").Append(mbr.TypeName).AppendLine(") {");
                        _sb.Append(indent).Append("    w.writeBits(").Append(wire).Append("u, ").Append(width)
                           .Append(")   // ").AppendLine(mbr.ElementName);
                        _sb.Append(indent).Append("    encode").Append(mbr.TypeName).Append("(w, ")
                           .Append(local).AppendLine(")");
                        _sb.Append(indent).Append("    ").AppendLine(after);
                        first = false;
                    }
                    return code + sc.Members.Count;
                }

                _sb.Append(indent).Append(first ? "if (" : "} else if (").Append(prop).AppendLine(" != null) {");
                _sb.Append(indent).Append("    w.writeBits(").Append(code).Append("u, ").Append(width)
                   .Append(")   // ").AppendLine(p.FieldName);
                EmitEncodeValue(p, prop + "!!", indent + "    ");
                _sb.Append(indent).Append("    ").AppendLine(after);
                first = false;
                return code + 1;
            }

            /// <summary>The read-once local a substitution particle dispatches on.</summary>
            private static string SubLocal(ChildPlan p) => "sub_" + Camel(p.FieldName);

            /// <summary>
            /// Declares the dispatch local of every substitution particle a state's if/else-if chain
            /// will touch. They have to exist before the chain opens — Kotlin has no way to introduce
            /// a `val` between two `else if` links.
            /// </summary>
            private void EmitEncodeRunSubLocals(IReadOnlyList<ChildPlan> kids, int start, int from,
                                                int optEnd, ChildPlan? term, string indent)
            {
                for (var i = from; i < optEnd; i++)
                    DeclareSubLocal(kids[start + i], indent);
                DeclareSubLocal(term, indent);
            }

            private void DeclareSubLocal(ChildPlan? p, string indent)
            {
                if (p?.Value is not ValueEncoding.SubstitutionChoice)
                    return;
                _sb.Append(indent).Append("val ").Append(SubLocal(p)).Append(" = msg.")
                   .AppendLine(Prop(p.FieldName));
            }

            /// <summary>
            /// How many grammar productions a run particle occupies: a substitution reference
            /// contributes one per member (the abstract head included), an xs:any wildcard two (the
            /// generic wildcard event and the typed element), everything else one.
            /// </summary>
            private static int ProductionCount(ChildPlan c) =>
                c.Value is ValueEncoding.SubstitutionChoice sc ? sc.Members.Count
                : c.IsWildcardAny ? 2
                : 1;

            /// <summary>
            /// Whether the run ends in an xs:any wildcard, and a guard that it appears nowhere else.
            /// cbexigen only splits a wildcard into its two productions as the last particle of an
            /// EE-terminated run (verified there against SignatureMethodType / DigestMethodType);
            /// anywhere else the code layout would differ and this back end does not model it.
            /// </summary>
            private static bool TrailingAny(IReadOnlyList<ChildPlan> kids, int start, int end, ChildPlan? term)
            {
                for (var p = start; p < end; p++)
                    if (kids[p].IsWildcardAny && (p != end - 1 || term is not null))
                        throw new NotSupportedException(
                            $"Kotlin back end: xs:any wildcard '{kids[p].FieldName}' must be the last child " +
                            "of an EE-terminated sequence.");

                return term is null && end > start && kids[end - 1].IsWildcardAny;
            }

            /// <summary>
            /// Substitution dispatch. Branches are emitted most-derived-first because Kotlin's
            /// `is` checks, like C#'s type patterns, also match subtypes — members can extend each
            /// other, not just the common head. The wire code stays each member's own (alphabetical,
            /// cbV2G-verified) position, independent of emission order.
            /// </summary>
            private void EmitEncodeSubstitution(ChildPlan c, ValueEncoding.SubstitutionChoice sc)
            {
                var prop = "msg." + Prop(c.FieldName);
                var ordered = sc.Members
                                .Select((m, i) => (Member: m, Code: i))
                                .Where(x => !x.Member.IsAbstractHead)
                                .OrderByDescending(x => InheritanceDepth(x.Member.TypeName))
                                .ToList();

                _sb.Append("        when (val v = ").Append(prop).AppendLine(") {");
                foreach (var (m, code) in ordered)
                {
                    _sb.Append("            is ").Append(m.TypeName).AppendLine(" -> {");
                    _sb.Append("                w.writeBits(").Append(code).Append("u, ").Append(sc.BitWidth)
                       .Append(")   // ").AppendLine(m.ElementName);
                    _sb.Append("                encode").Append(m.TypeName).AppendLine("(w, v)");
                    _sb.AppendLine("            }");
                }
                _sb.Append("            else -> throw IllegalArgumentException(\"unsupported substitution member for ")
                   .Append(c.FieldName).AppendLine("\")");
                _sb.AppendLine("        }");
            }

            /// <summary>How many base links separate a type from its root; 0 for a type with no base.</summary>
            private int InheritanceDepth(string typeName)
            {
                var depth = 0;
                var current = typeName;
                while (plan.ComplexTypes.TryGetValue(current, out var sp) && sp.BaseRecordName is not null)
                {
                    depth++;
                    current = sp.BaseRecordName;
                }
                return depth;
            }

            private void EmitEncodeValue(ChildPlan c, string accessor, string indent, bool inList = false)
            {
                if (c.Value is ValueEncoding.OpaqueElement oe)
                {
                    // Only reached with a present instance; absence is handled by the optional run.
                    _sb.Append(indent).Append("throw UnsupportedOperationException(\"Encoding a present ")
                       .Append(oe.TypeName).AppendLine(" (XMLDSig) is not implemented in the Kotlin back end.\")");
                    return;
                }
                if (c.Value is ValueEncoding.ComplexRef cr)
                {
                    _sb.Append(indent).Append("encode").Append(cr.TypeName).Append("(w, ").Append(accessor).AppendLine(")");
                    return;
                }
                if (c.Value is ValueEncoding.AttributeValue)
                {
                    // Bare string — the run's event code was the AT event itself.
                    _sb.Append(indent).Append("ExiPrimitives.writeStringValue(w, ").Append(accessor).AppendLine(")");
                    return;
                }

                _sb.Append(indent).AppendLine("w.writeBits(0u, 1)   // value-start");
                EmitEncodeBareValue(c, accessor, indent);
                _sb.Append(indent).AppendLine("w.writeBits(0u, 1)   // child EE");
            }

            /// <summary>
            /// A value with no framing around it. Used on its own for an AT value and for
            /// xs:simpleContent, where the preceding event code already selected the production.
            /// </summary>
            private void EmitEncodeBareValue(ChildPlan c, string accessor, string indent)
            {
                switch (c.Value)
                {
                    case ValueEncoding.StringValue:
                        _sb.Append(indent).Append("ExiPrimitives.writeStringValue(w, ").Append(accessor).AppendLine(")");
                        break;
                    case ValueEncoding.UnsignedInt:
                        _sb.Append(indent).Append("ExiPrimitives.writeUnsignedInteger(w, ").Append(accessor).AppendLine(".toULong())");
                        break;
                    case ValueEncoding.SignedInt:
                        _sb.Append(indent).Append("ExiPrimitives.writeSignedInteger(w, ").Append(accessor).AppendLine(".toLong())");
                        break;
                    case ValueEncoding.Binary:
                        _sb.Append(indent).Append("ExiPrimitives.writeBinary(w, ").Append(accessor).AppendLine(")");
                        break;
                    case ValueEncoding.EnumIndex ei:
                        _sb.Append(indent).Append("w.writeBits(").Append(accessor).Append(".ordinal.toUInt(), ")
                           .Append(ei.BitWidth).AppendLine(")");
                        break;
                    case ValueEncoding.NBitUnsigned nb when IsBool(c):
                        // xs:boolean is a 1-bit n-bit unsigned, and Kotlin's Boolean has no numeric
                        // conversion — same special case as in CodecEmitter.
                        _sb.Append(indent).Append("w.writeBits(if (").Append(accessor).Append(") 1u else 0u, ")
                           .Append(nb.BitWidth).AppendLine(")");
                        break;
                    case ValueEncoding.NBitUnsigned nb:
                        var expr = nb.Bias == 0
                                       ? accessor + ".toLong()"
                                       : "(" + accessor + ".toLong() - " + nb.Bias + "L)";
                        _sb.Append(indent).Append("w.writeBits(").Append(expr).Append(".toUInt(), ")
                           .Append(nb.BitWidth).AppendLine(")");
                        break;
                    default:
                        throw new NotSupportedException($"Kotlin back end: value encoding {c.Value.GetType().Name}.");
                }
            }

            private void EmitDecode(SequencePlan sp, string name)
            {
                _sb.Append("    private fun decode").Append(name).Append("(r: BitReader): ")
                   .Append(name).AppendLine(" {");

                var ctor = new List<string>();

                if (RequiredAttr(sp) is { } req)
                {
                    _sb.AppendLine("        r.readBits(1)   // AT(required attribute)");
                    _sb.Append("        val ").Append(Local(req.FieldName))
                       .AppendLine(" = ExiPrimitives.readStringValue(r)");
                    ctor.Add(Local(req.FieldName));
                }

                if (sp.SimpleContent is not null)
                {
                    if (HasOptionalAttributes(sp))
                        EmitDecodeSimpleContentOptionalAttrs(sp, ctor);
                    else
                    {
                        _sb.AppendLine("        r.readBits(1)   // CONTENT event");
                        _sb.Append("        val ").Append(Local(SimpleContentField)).Append(" = ")
                           .AppendLine(DecodeValueExpr(SimpleContentChild(sp)));
                        ctor.Add(Local(SimpleContentField));
                    }
                    _sb.AppendLine("        r.readBits(1)   // element EE");
                    _sb.Append("        return ").Append(name).Append("(").Append(string.Join(", ", ctor)).AppendLine(")");
                    _sb.AppendLine("    }");
                    _sb.AppendLine();
                    return;
                }

                if (sp.IsChoice)
                {
                    EmitDecodeChoice(sp, ctor);
                    _sb.Append("        return ").Append(name).Append("(").Append(string.Join(", ", ctor)).AppendLine(")");
                    _sb.AppendLine("    }");
                    _sb.AppendLine();
                    return;
                }

                var kids = WithOptionalAttributes(sp);

                for (var i = 0; i < kids.Count;)
                {
                    var c = kids[i];
                    if (c.Shape == ChildShape.BoundedRepeating)
                    {
                        if (kids.Count == 1)
                        {
                            EmitDecodeRepeating(c, "list", ListBounds(c, sp).Max, "        ");
                            ctor.Add("list");
                        }
                        else
                        {
                            EmitDecodeRepeating(c, ListLocal(c), c.ListMax, "        ");
                            ctor.Add(ListLocal(c));
                        }
                        i++;
                        continue;
                    }
                    if (c.Shape == ChildShape.OptionalSingle)
                    {
                        var e    = RunEnd(kids, i);
                        var term = e < kids.Count ? kids[e] : null;
                        RejectRunTerminator(term, name);

                        EmitDecodeOptionalRun(kids, i, e, term, ctor);

                        i = term is null ? kids.Count : e + 1;
                        if (term is not null && term.Shape != ChildShape.BoundedRepeating && i == kids.Count)
                            _sb.AppendLine("        r.readBits(1)   // element EE");
                        continue;
                    }

                    var v = Local(c.FieldName);
                    if (c.Value is ValueEncoding.SubstitutionChoice sub)
                    {
                        _sb.Append("        val ").Append(v).Append(": ").Append(Type(c.Type))
                           .Append(" = when (r.readBits(").Append(sub.BitWidth).AppendLine(")) {");
                        for (var k = 0; k < sub.Members.Count; k++)
                        {
                            var m = sub.Members[k];
                            if (m.IsAbstractHead)
                                _sb.Append("            ").Append(k)
                                   .AppendLine("u -> throw IllegalArgumentException(\"abstract substitution head cannot be decoded\")");
                            else
                                _sb.Append("            ").Append(k).Append("u -> decode")
                                   .Append(m.TypeName).AppendLine("(r)");
                        }
                        _sb.AppendLine("            else -> throw IllegalArgumentException(\"unknown substitution index\")");
                        _sb.AppendLine("        }");
                        ctor.Add(v);
                        i++;
                        if (i == kids.Count)
                            _sb.AppendLine("        r.readBits(1)   // element EE");
                        continue;
                    }

                    _sb.AppendLine("        r.readBits(1)   // SE");
                    if (!WrapsValue(c))
                    {
                        _sb.Append("        val ").Append(v).Append(" = ").AppendLine(DecodeValueExpr(c));
                    }
                    else
                    {
                        _sb.AppendLine("        r.readBits(1)   // value-start");
                        _sb.Append("        val ").Append(v).Append(" = ").AppendLine(DecodeValueExpr(c));
                        _sb.AppendLine("        r.readBits(1)   // child EE");
                    }
                    ctor.Add(v);
                    i++;
                    if (i == kids.Count)
                        _sb.AppendLine("        r.readBits(1)   // element EE");
                }

                if (kids.Count == 0)
                    _sb.AppendLine("        r.readBits(1)   // element EE");

                _sb.Append("        return ").Append(name).Append("(").Append(string.Join(", ", ctor)).AppendLine(")");
                _sb.AppendLine("    }");
                _sb.AppendLine();
            }

            /// <summary>Decode mirror of <see cref="EmitEncodeRepeating"/>.</summary>
            private void EmitDecodeRepeating(ChildPlan c, string list, int max, string indent)
            {
                _sb.Append(indent).Append("val ").Append(list).Append(" = ArrayList<")
                   .Append(Type(c.Type)).AppendLine(">()");
                _sb.Append(indent).AppendLine("r.readBits(1)   // SE(item) first");
                EmitDecodeItem(c, list, list + "First", indent);

                _sb.Append(indent).AppendLine("while (true) {");
                if (max == 2)
                    _sb.Append(indent).Append("    if (").Append(list)
                       .AppendLine(".size >= 2) { r.readBits(1); break }   // element EE (list at max)");
                _sb.Append(indent).AppendLine("    val ec = r.readBits(2)");
                _sb.Append(indent).AppendLine("    if (ec == 1u) break   // element EE");
                _sb.Append(indent).Append("    require(ec == 0u && ").Append(list).Append(".size < ")
                   .Append(max).AppendLine(") { \"invalid repeating-element event code\" }");
                EmitDecodeItem(c, list, list + "Next", indent + "    ");
                _sb.Append(indent).AppendLine("}");
            }

            /// <summary>
            /// One list item. A value needing framing has to be read into a local so the value-start
            /// and child EE can bracket it; a self-framing complex item is appended directly.
            /// </summary>
            private void EmitDecodeItem(ChildPlan c, string list, string local, string indent)
            {
                if (!WrapsValue(c))
                {
                    _sb.Append(indent).Append(list).Append(".add(").Append(DecodeValueExpr(c)).AppendLine(")");
                    return;
                }
                _sb.Append(indent).AppendLine("r.readBits(1)   // value-start");
                _sb.Append(indent).Append("val ").Append(local).Append(" = ").AppendLine(DecodeValueExpr(c));
                _sb.Append(indent).AppendLine("r.readBits(1)   // child EE");
                _sb.Append(indent).Append(list).Append(".add(").Append(local).AppendLine(")");
            }

            /// <summary>Decode mirror of <see cref="EmitEncodeSimpleContentOptionalAttrs"/>.</summary>
            private void EmitDecodeSimpleContentOptionalAttrs(SequencePlan sp, List<string> ctor)
            {
                var oa    = sp.Attributes!;
                var n     = oa.Count;
                var id    = _run++;
                var value = SimpleContentChild(sp);
                const string ind = "                        ";

                foreach (var a in oa)
                {
                    _sb.Append("        var ").Append(Local(a.FieldName)).Append(": ").Append(Type(a.Type))
                       .AppendLine("? = null");
                    ctor.Add(Local(a.FieldName));
                }
                _sb.Append("        var ").Append(Local(SimpleContentField)).Append(": ")
                   .Append(Type(sp.SimpleContentType!)).AppendLine("? = null");
                ctor.Add(Local(SimpleContentField) + "!!");

                _sb.Append("        var st").Append(id).AppendLine(" = 0");
                _sb.Append("        var done").Append(id).AppendLine(" = false");
                _sb.Append("        while (!done").Append(id).AppendLine(") {");
                _sb.Append("            when (st").Append(id).AppendLine(") {");

                for (var k = 0; k <= n; k++)
                {
                    var width = BitsFor((n - k + 1) + 1);
                    _sb.Append("                ").Append(k).AppendLine(" -> {");
                    _sb.Append("                    when (r.readBits(").Append(width).AppendLine(")) {");

                    for (var i = k; i < n; i++)
                    {
                        _sb.Append(ind).Append(i - k).Append("u -> {   // AT(").Append(oa[i].FieldName).AppendLine(")");
                        _sb.Append(ind).Append("    ").Append(Local(oa[i].FieldName))
                           .AppendLine(" = ExiPrimitives.readStringValue(r)");
                        _sb.Append(ind).Append("    st").Append(id).Append(" = ").Append(i + 1).AppendLine();
                        _sb.Append(ind).AppendLine("}");
                    }

                    _sb.Append(ind).Append(n - k).AppendLine("u -> {   // CONTENT");
                    _sb.Append(ind).Append("    ").Append(Local(SimpleContentField)).Append(" = ")
                       .AppendLine(DecodeValueExpr(value));
                    _sb.Append(ind).Append("    done").Append(id).AppendLine(" = true");
                    _sb.Append(ind).AppendLine("}");
                    _sb.Append(ind).AppendLine("else -> throw IllegalArgumentException(\"invalid simpleContent event code\")");
                    _sb.AppendLine("                    }");
                    _sb.AppendLine("                }");
                }

                _sb.AppendLine("            }");
                _sb.AppendLine("        }");
            }

            /// <summary>Decode mirror of <see cref="EmitEncodeChoice"/>.</summary>
            private void EmitDecodeChoice(SequencePlan sp, List<string> ctor)
            {
                var width = BitsFor(sp.Children.Count + 1);

                foreach (var c in sp.Children)
                {
                    _sb.Append("        var ").Append(Local(c.FieldName)).Append(": ").Append(DeclType(c))
                       .AppendLine(" = null");
                    ctor.Add(Local(c.FieldName));
                }

                _sb.Append("        when (r.readBits(").Append(width).AppendLine(")) {");
                for (var i = 0; i < sp.Children.Count; i++)
                {
                    var c = sp.Children[i];
                    _sb.Append("            ").Append(i).Append("u -> {   // ").AppendLine(c.FieldName);
                    if (WrapsValue(c))
                        _sb.AppendLine("                r.readBits(1)   // value-start");
                    _sb.Append("                ").Append(Local(c.FieldName)).Append(" = ")
                       .AppendLine(DecodeValueExpr(c));
                    if (WrapsValue(c))
                        _sb.AppendLine("                r.readBits(1)   // child EE");
                    _sb.AppendLine("            }");
                }
                _sb.AppendLine("            else -> throw IllegalArgumentException(\"unknown choice event code\")");
                _sb.AppendLine("        }");
                _sb.AppendLine("        r.readBits(1)   // element EE");
            }

            private void EmitDecodeOptionalRun(IReadOnlyList<ChildPlan> kids, int start, int end,
                                               ChildPlan? term, List<string> ctor)
            {
                var id          = _run++;
                var trailingAny = TrailingAny(kids, start, end, term);
                RejectMidRunList(kids, start, end);

                for (var s = start; s < end; s++)
                    DeclareRunLocal(kids[s], ctor);

                // The terminator is required, but it is only assigned inside the state machine, so a
                // non-list one has to be declared nullable and unwrapped at the constructor call.
                if (term is not null)
                {
                    if (term.Shape == ChildShape.BoundedRepeating)
                        DeclareRunLocal(term, ctor);
                    else
                    {
                        _sb.Append("        var ").Append(Local(term.FieldName)).Append(": ").Append(Type(term.Type))
                           .AppendLine("? = null");
                        ctor.Add(Local(term.FieldName) + "!!");
                    }
                }

                _sb.Append("        var st").Append(id).AppendLine(" = 0");
                _sb.Append("        var done").Append(id).AppendLine(" = false");
                _sb.Append("        while (!done").Append(id).AppendLine(") {");
                _sb.Append("            when (st").Append(id).AppendLine(") {");

                var m = end - start;
                for (var k = 0; k <= m; k++)
                {
                    var totalProd = term is null ? 1                        // the element EE
                                                 : ProductionCount(term);   // or the required child
                    for (var i = k; i < m; i++) totalProd += ProductionCount(kids[start + i]);
                    var width = BitsFor(totalProd + 1);                  // + the non-strict phantom

                    _sb.Append("                ").Append(k).AppendLine(" -> {");
                    _sb.Append("                    when (r.readBits(").Append(width).AppendLine(")) {");

                    const string ind = "                        ";
                    var code   = 0;
                    var optEnd = trailingAny ? m - 1 : m;   // the ANY is handled with the tail

                    for (var i = k; i < optEnd; i++)
                    {
                        var c     = kids[start + i];
                        var field = Local(c.FieldName);

                        if (c.Shape == ChildShape.BoundedRepeating)
                        {
                            // A list consumes the rest of the element; its list-end EE closes it.
                            _sb.Append(ind).Append(code).Append("u -> {   // ").AppendLine(c.FieldName);
                            EmitDecodeRepeatingItems(c, ListLocal(c), ind + "    ", $"done{id} = true");
                            _sb.Append(ind).AppendLine("}");
                            code++;
                            continue;
                        }

                        if (c.Value is ValueEncoding.SubstitutionChoice sc)
                        {
                            for (var j = 0; j < sc.Members.Count; j++)
                            {
                                var mbr = sc.Members[j];
                                if (mbr.IsAbstractHead)
                                {
                                    _sb.Append(ind).Append(code + j)
                                       .AppendLine("u -> throw IllegalArgumentException(\"abstract substitution head cannot be decoded\")");
                                    continue;
                                }
                                _sb.Append(ind).Append(code + j).AppendLine("u -> {");
                                _sb.Append(ind).Append("    ").Append(field).Append(" = decode")
                                   .Append(mbr.TypeName).AppendLine("(r)");
                                _sb.Append(ind).Append("    st").Append(id).Append(" = ").Append(i + 1).AppendLine();
                                _sb.Append(ind).AppendLine("}");
                            }
                            code += sc.Members.Count;
                            continue;
                        }

                        _sb.Append(ind).Append(code).AppendLine("u -> {");
                        if (WrapsValue(c))
                            _sb.Append(ind).AppendLine("    r.readBits(1)   // value-start");
                        _sb.Append(ind).Append("    ").Append(field).Append(" = ").AppendLine(DecodeValueExpr(c));
                        if (WrapsValue(c))
                            _sb.Append(ind).AppendLine("    r.readBits(1)   // child EE");
                        _sb.Append(ind).Append("    st").Append(id).Append(" = ").Append(i + 1).AppendLine();
                        _sb.Append(ind).AppendLine("}");
                        code++;
                    }

                    if (trailingAny && k < m)
                    {
                        // `code` is the generic-wildcard slot: no branch, so it falls through to the
                        // error case — a generic wildcard event is not modelled. The element EE takes
                        // code+1, the typed ANY element code+2.
                        var any = kids[end - 1];
                        _sb.Append(ind).Append(code + 1).Append("u -> done").Append(id).AppendLine(" = true   // element EE");
                        _sb.Append(ind).Append(code + 2).Append("u -> {   // ").AppendLine(any.FieldName);
                        if (WrapsValue(any))
                            _sb.Append(ind).AppendLine("    r.readBits(1)   // value-start");
                        _sb.Append(ind).Append("    ").Append(Local(any.FieldName)).Append(" = ")
                           .AppendLine(DecodeValueExpr(any));
                        if (WrapsValue(any))
                            _sb.Append(ind).AppendLine("    r.readBits(1)   // child EE");
                        _sb.Append(ind).Append("    st").Append(id).Append(" = ").Append(m).AppendLine();
                        _sb.Append(ind).AppendLine("}");
                    }
                    else if (term is null)
                        _sb.Append(ind).Append(code).Append("u -> done").Append(id).AppendLine(" = true   // element EE");
                    else if (term.Shape == ChildShape.BoundedRepeating)
                    {
                        _sb.Append(ind).Append(code).Append("u -> {   // ").AppendLine(term.FieldName);
                        EmitDecodeRepeatingItems(term, ListLocal(term), ind + "    ", $"done{id} = true");
                        _sb.Append(ind).AppendLine("}");
                    }
                    else if (term.Value is ValueEncoding.SubstitutionChoice tsc)
                    {
                        // One case per member, at the run's highest codes.
                        var field = Local(term.FieldName);
                        for (var j = 0; j < tsc.Members.Count; j++)
                        {
                            var mbr = tsc.Members[j];
                            if (mbr.IsAbstractHead)
                            {
                                _sb.Append(ind).Append(code + j)
                                   .AppendLine("u -> throw IllegalArgumentException(\"abstract substitution head cannot be decoded\")");
                                continue;
                            }
                            _sb.Append(ind).Append(code + j).Append("u -> {   // ").AppendLine(mbr.ElementName);
                            _sb.Append(ind).Append("    ").Append(field).Append(" = decode")
                               .Append(mbr.TypeName).AppendLine("(r)");
                            _sb.Append(ind).Append("    done").Append(id).AppendLine(" = true");
                            _sb.Append(ind).AppendLine("}");
                        }
                    }
                    else
                    {
                        var field = Local(term.FieldName);
                        _sb.Append(ind).Append(code).Append("u -> {   // SE(").Append(term.FieldName).AppendLine(")");
                        if (WrapsValue(term))
                            _sb.Append(ind).AppendLine("    r.readBits(1)   // value-start");
                        _sb.Append(ind).Append("    ").Append(field).Append(" = ").AppendLine(DecodeValueExpr(term));
                        if (WrapsValue(term))
                            _sb.Append(ind).AppendLine("    r.readBits(1)   // child EE");
                        _sb.Append(ind).Append("    done").Append(id).AppendLine(" = true");
                        _sb.Append(ind).AppendLine("}");
                    }
                    _sb.Append(ind).AppendLine("else -> throw IllegalArgumentException(\"invalid optional-run event code\")");
                    _sb.AppendLine("                    }");
                    _sb.AppendLine("                }");
                }

                _sb.AppendLine("            }");
                _sb.AppendLine("        }");
            }

            private string DecodeValueExpr(ChildPlan c) => c.Value switch
            {
                ValueEncoding.OpaqueElement oe =>
                    $"throw UnsupportedOperationException(\"Decoding a present {oe.TypeName} " +
                    "(XMLDSig) is not implemented in the Kotlin back end.\")",
                ValueEncoding.ComplexRef cr  => $"decode{cr.TypeName}(r)",
                // An AT value is a bare string, like StringValue but without the value framing.
                ValueEncoding.AttributeValue => "ExiPrimitives.readStringValue(r)",
                ValueEncoding.StringValue    => "ExiPrimitives.readStringValue(r)",
                ValueEncoding.UnsignedInt    => $"ExiPrimitives.readUnsignedInteger(r).{ToNarrow(c.Type)}",
                ValueEncoding.SignedInt      => $"ExiPrimitives.readSignedInteger(r).{ToNarrow(c.Type)}",
                ValueEncoding.Binary         => "ExiPrimitives.readBinary(r)",
                ValueEncoding.EnumIndex ei   => $"{ei.EnumName}.entries[r.readBits({ei.BitWidth}).toInt()]",
                ValueEncoding.NBitUnsigned nb => nb.Bias == 0
                                                    ? $"r.readBits({nb.BitWidth}).{ToNarrow(c.Type)}"
                                                    : $"(r.readBits({nb.BitWidth}).toLong() + {nb.Bias}L).{ToNarrow(c.Type)}",
                _ => throw new NotSupportedException($"Kotlin back end: value encoding {c.Value.GetType().Name}."),
            };

            /// <summary>Kotlin has no implicit numeric conversions — every read needs an explicit narrowing.</summary>
            private static bool IsBool(ChildPlan c) =>
                c.Type is TypeRef.Primitive { Kind: PrimitiveKind.Bool };

            private static string ToNarrow(TypeRef t) => t switch
            {
                TypeRef.Primitive p => p.Kind switch
                {
                    PrimitiveKind.Int8   => "toByte()",
                    PrimitiveKind.Int16  => "toShort()",
                    PrimitiveKind.Int32  => "toInt()",
                    PrimitiveKind.Int64  => "toLong()",
                    PrimitiveKind.UInt8  => "toUByte()",
                    PrimitiveKind.UInt16 => "toUShort()",
                    PrimitiveKind.UInt32 => "toUInt()",
                    PrimitiveKind.UInt64 => "toULong()",
                    PrimitiveKind.Bool   => "toInt() != 0",
                    _ => throw new NotSupportedException($"Kotlin back end: narrowing for {p.Kind}."),
                },
                _ => throw new NotSupportedException("Kotlin back end: narrowing for a named type."),
            };

            /// <summary>
            /// Occurrence bounds of a repeating child. For the "single repeating element" shape the
            /// builder records them on the <see cref="SequencePlan"/> and leaves the
            /// <see cref="ChildPlan"/>'s at zero; a repeating child among siblings carries its own.
            /// </summary>
            private static (int Min, int Max) ListBounds(ChildPlan c, SequencePlan sp) =>
                c.ListMax != 0 ? (Math.Max(c.ListMin, 1), c.ListMax)
                               : (Math.Max(sp.ListMin, 1), sp.ListMax);

            /// <summary>⌈log₂(n)⌉, with the EXI convention that n = 1 needs 0 bits.</summary>
            private static int BitsFor(int n)
            {
                var bits = 0;
                while ((1 << bits) < n) bits++;
                return bits;
            }
        }
    }
}
