/*
 * Copyright (c) 2021-2025 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Net;

using NUnit.Framework;

using Org.BouncyCastle.Tls;

using cloud.charging.open.protocols.ISO15118.PKI;

using Vanaheimr.V2G.Simulation.Sap;
using Vanaheimr.V2G.Simulation.StateMachines;
using Vanaheimr.V2G.Simulation.StateMachines.Iso20;
using Vanaheimr.V2G.Simulation.Tests.TestData;
using Vanaheimr.V2G.Simulation.Tests.Timing;
using Vanaheimr.V2G.Simulation.Transport;
using Vanaheimr.V2G.Simulation.Transport.BouncyCastle;

namespace Vanaheimr.V2G.Simulation.Tests.E2E
{
    /// <summary>
    /// ISO 15118-20 over mutual TLS using the <b>BouncyCastle</b> TLS backend — the -20-faithful profile
    /// (TLS 1.3, the -20 cipher suites, secp521r1 / Ed448 certificates) that Windows Schannel cannot do.
    /// SECC leaf = server, Vehicle leaf = client, generated by the WWCP PKI builder; the DC happy path
    /// runs to SessionStop over the bilaterally-authenticated BouncyCastle stream. See <c>docs/pki-model.md</c>.
    /// </summary>
    [TestFixture]
    public class BcMutualTlsLoopbackTests
    {
        private static async Task RunIso20DcSession(BcTlsOptions secc, BcTlsOptions evcc)
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(20));
            using var listener = new TcpV2GListener(new IPEndPoint(IPAddress.Loopback, 0), secc);

            var seccTask = Task.Run(async () =>
            {
                using var seccStream = await listener.AcceptAsync(cts.Token);
                await SapHandshake.RunSeccSideAsync(seccStream, ProtocolVariant.Iso15118_20, cts.Token);
                var machine = new Secc20Dc(TimeSpan.FromSeconds(60), TimeProvider.System);
                await machine.RunAsync(seccStream, cts.Token);
                return machine;
            }, cts.Token);

            using var evccStream = await TcpV2GClient.ConnectAsync("localhost", listener.LocalEndpoint.Port, evcc, cts.Token);
            await SapHandshake.RunEvccSideAsync(evccStream, ProtocolVariant.Iso15118_20, cts.Token);

            var e = new Evcc20Dc(evccStream, TimeProvider.System, new ImmediateAsyncDelay(), LoopbackTimeouts.PerMessage);
            var eTask = e.RunAsync(cts.Token);
            await Task.WhenAll(eTask, seccTask);

            Assert.That((await seccTask).IsDone, Is.True);
            Assert.That(e.Exchanges, Is.GreaterThan(0));
        }

        [Test]
        public async Task Iso20Dc_P521_MutualTls()
        {
            var (secc, evcc) = V2GBcTlsFixture.MutualTls(V2GAlgorithm.EcdsaP521, SignatureScheme.ecdsa_secp521r1_sha512);
            await RunIso20DcSession(secc, evcc);
        }

        [Test]
        public async Task Iso20Dc_Ed448_MutualTls()
        {
            var (secc, evcc) = V2GBcTlsFixture.MutualTls(V2GAlgorithm.Ed448, SignatureScheme.ed448);
            await RunIso20DcSession(secc, evcc);
        }
    }
}
